-- File generated by MOTE (Mangos Online Translation Editor) v0.01
SET NAMES 'utf8';
UPDATE db_script_string SET content_loc5='這是活的!' WHERE entry=2000000231; /* content: It\'s alive! */
UPDATE db_script_string SET content_loc5='成功!' WHERE entry=2000000637; /* content: Success! */

SET NAMES 'latin1';
