-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE locales_page_text SET text_loc5='(獸人語)Lok\'tar ogar!不勝即亡 - 就是這幾個字讓我跟部落連結在一起!對任何一個部落的戰士而言，這幾個字是最神聖且基本的真理。$B$B我將我的血肉無條件獻給大酋長，我將完成所有大酋長的意志，我就是大酋長命令下的武器。$B$B從此刻起我活著，直到世界末日英勇赴死 - 為了部落!' WHERE entry=3068;
UPDATE locales_page_text SET text_loc5='許久以前，當只有北風精靈統治群山時，一個強大坦卡族酋長的兄弟試圖將這些土地據為己有。' WHERE entry=3280;
UPDATE locales_page_text SET text_loc5='獻給那些在冰凍荒原和天譴軍團交戰時倒下的人們。' WHERE entry=3605;

SET NAMES 'latin1';
