-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE mangos_string SET content_loc5='隱形' WHERE entry=42; /* content: invisible */
UPDATE mangos_string SET content_loc5='DONE' WHERE entry=43; /* content: done */
UPDATE mangos_string SET content_loc5='UNUSED' WHERE entry=235; /* content: UNUSED */
UPDATE mangos_string SET content_loc5='UNUSED' WHERE entry=242; /* content: UNUSED */
UPDATE mangos_string SET content_loc5='UNUSED' WHERE entry=243; /* content: UNUSED */
UPDATE mangos_string SET content_loc5='UNUSED' WHERE entry=244; /* content: UNUSED */
UPDATE mangos_string SET content_loc5='UNUSED' WHERE entry=245; /* content: UNUSED */
UPDATE mangos_string SET content_loc5='UNUSED' WHERE entry=251; /* content: UNUSED */
UPDATE mangos_string SET content_loc5='中立' WHERE entry=321; /* content: Neutral */
UPDATE mangos_string SET content_loc5='友方' WHERE entry=322; /* content: Friendly */
UPDATE mangos_string SET content_loc5='是' WHERE entry=421; /* content: Yes */
UPDATE mangos_string SET content_loc5='否' WHERE entry=422; /* content: No */
UPDATE mangos_string SET content_loc5='聯盟' WHERE entry=457; /* content: alliance */
UPDATE mangos_string SET content_loc5='部落' WHERE entry=458; /* content: horde */
UPDATE mangos_string SET content_loc5='聯盟勝利了!' WHERE entry=600; /* content: The Alliance wins! */
UPDATE mangos_string SET content_loc5='部落勝利了!' WHERE entry=601; /* content: The Horde wins! */
UPDATE mangos_string SET content_loc5='戰歌峽谷戰鬥將在1分鐘內開始。' WHERE entry=602; /* content: The battle for Warsong Gulch begins in 1 minute. */
UPDATE mangos_string SET content_loc5='$n奪取了部落的旗幟!' WHERE entry=605; /* content: $n captured the Horde flag! */
UPDATE mangos_string SET content_loc5='$n奪取了聯盟的旗幟!' WHERE entry=606; /* content: $n captured the Alliance flag! */
UPDATE mangos_string SET content_loc5='部落的旗幟被$n丟掉了!' WHERE entry=607; /* content: The Horde flag was dropped by $n! */
UPDATE mangos_string SET content_loc5='聯盟的旗幟被$n丟掉了!' WHERE entry=608; /* content: The Alliance Flag was dropped by $n! */
UPDATE mangos_string SET content_loc5='聯盟的旗幟被$n歸還到它的基地了!' WHERE entry=609; /* content: The Alliance Flag was returned to its base by $n! */
UPDATE mangos_string SET content_loc5='部落旗幟被$n歸還到它的基地了!' WHERE entry=610; /* content: The Horde flag was returned to its base by $n! */
UPDATE mangos_string SET content_loc5='部落的旗幟被$n拔起了!' WHERE entry=611; /* content: The Horde flag was picked up by $n! */
UPDATE mangos_string SET content_loc5='聯盟的旗幟被$n拔掉了!' WHERE entry=612; /* content: The Alliance Flag was picked up by $n! */
UPDATE mangos_string SET content_loc5='旗幟被重新放置在它們的基地之中。' WHERE entry=613; /* content: The flags are now placed at their bases. */
UPDATE mangos_string SET content_loc5='聯盟的旗幟現被放置在它的基地中。' WHERE entry=614; /* content: The Alliance flag is now placed at its base. */
UPDATE mangos_string SET content_loc5='部落的旗幟現被放置在它的基地中。' WHERE entry=615; /* content: The Horde flag is now placed at its base. */
UPDATE mangos_string SET content_loc5='聯盟' WHERE entry=650; /* content: alliance */
UPDATE mangos_string SET content_loc5='部落' WHERE entry=651; /* content: horde */
UPDATE mangos_string SET content_loc5='獸欄' WHERE entry=652; /* content: stables */
UPDATE mangos_string SET content_loc5='鐵匠舖' WHERE entry=653; /* content: blacksmith */
UPDATE mangos_string SET content_loc5='農田' WHERE entry=654; /* content: farm */
UPDATE mangos_string SET content_loc5='伐木場' WHERE entry=655; /* content: lumber mill */
UPDATE mangos_string SET content_loc5='全是我的' WHERE entry=656; /* content: mine */
UPDATE mangos_string SET content_loc5='聯盟已經收集到$1776W資源，離勝利不遠了!' WHERE entry=664; /* content: The Alliance has gathered $1776W resources, and is near victory! */
UPDATE mangos_string SET content_loc5='部落已經收集到$1777W資源，離勝利不遠了!' WHERE entry=665; /* content: The Horde has gathered $1777W resources, and is near victory! */
UPDATE mangos_string SET content_loc5='聯盟獲得了法師塔的控制權!' WHERE entry=667; /* content: The Alliance has taken control of the Mage Tower! */
UPDATE mangos_string SET content_loc5='部落獲得了法師塔的控制權!' WHERE entry=668; /* content: The Horde has taken control of the Mage Tower! */
UPDATE mangos_string SET content_loc5='聯盟獲得了德萊尼廢墟的控制權!' WHERE entry=669; /* content: The Alliance has taken control of the Draenei Ruins! */
UPDATE mangos_string SET content_loc5='部落獲得了德萊尼廢墟的控制權!' WHERE entry=670; /* content: The Horde has taken control of the Draenei Ruins! */
UPDATE mangos_string SET content_loc5='聯盟獲得了血精靈哨塔的控制權!' WHERE entry=671; /* content: The Alliance has taken control of the Blood Elf Tower! */
UPDATE mangos_string SET content_loc5='部落獲得了血精靈哨塔的控制權!' WHERE entry=672; /* content: The Horde has taken control of the Blood Elf Tower! */
UPDATE mangos_string SET content_loc5='聯盟獲得了惡魔劫奪者廢墟的控制權!' WHERE entry=673; /* content: The Alliance has taken control of the Fel Reaver Ruins! */
UPDATE mangos_string SET content_loc5='部落獲得了惡魔劫奪者廢墟的控制權!' WHERE entry=674; /* content: The Horde has taken control of the Fel Reaver Ruins! */
UPDATE mangos_string SET content_loc5='聯盟失去了法師塔的控制權!' WHERE entry=675; /* content: The Alliance has lost control of the Mage Tower! */
UPDATE mangos_string SET content_loc5='部落失去了法師塔的控制權!' WHERE entry=676; /* content: The Horde has lost control of the Mage Tower! */
UPDATE mangos_string SET content_loc5='聯盟失去了德萊尼廢墟的控制權!' WHERE entry=677; /* content: The Alliance has lost control of the Draenei Ruins! */
UPDATE mangos_string SET content_loc5='部落失去了德萊尼廢墟的控制權!' WHERE entry=678; /* content: The Horde has lost control of the Draenei Ruins! */
UPDATE mangos_string SET content_loc5='聯盟失去了血精靈哨塔的控制權!' WHERE entry=679; /* content: The Alliance has lost control of the Blood Elf Tower! */
UPDATE mangos_string SET content_loc5='部落失去了血精靈哨塔的控制權!' WHERE entry=680; /* content: The Horde has lost control of the Blood Elf Tower! */
UPDATE mangos_string SET content_loc5='聯盟失去了惡魔劫奪者廢墟的控制權!' WHERE entry=681; /* content: The Alliance has lost control of the Fel Reaver Ruins! */
UPDATE mangos_string SET content_loc5='部落失去了惡魔劫奪者廢墟的控制權!' WHERE entry=682; /* content: The Horde has lost control of the Fel Reaver Ruins! */
UPDATE mangos_string SET content_loc5='聯盟已奪得旗幟!' WHERE entry=684; /* content: The Alliance have captured the flag! */
UPDATE mangos_string SET content_loc5='部落已奪得旗幟!' WHERE entry=685; /* content: The Horde have captured the flag! */
UPDATE mangos_string SET content_loc5='旗幟已重置。' WHERE entry=687; /* content: The flag has been reset. */
UPDATE mangos_string SET content_loc5='1分鐘後競技場戰鬥開始!' WHERE entry=701; /* content: One minute until the Arena battle begins! */
UPDATE mangos_string SET content_loc5='30秒後競技場戰鬥開始!' WHERE entry=702; /* content: Thirty seconds until the Arena battle begins! */
UPDATE mangos_string SET content_loc5='競技場的戰鬥將在十五秒後開始!' WHERE entry=703; /* content: Fifteen seconds until the Arena battle begins! */
UPDATE mangos_string SET content_loc5='競技場的戰鬥開始了!' WHERE entry=704; /* content: The Arena battle has begun! */
UPDATE mangos_string SET content_loc5='深鐵礦坑' WHERE entry=766; /* content: Irondeep Mine */
UPDATE mangos_string SET content_loc5='冷齒礦坑' WHERE entry=767; /* content: Coldtooth Mine */
UPDATE mangos_string SET content_loc5='雷矛急救站' WHERE entry=768; /* content: Stormpike Aid Station */
UPDATE mangos_string SET content_loc5='丹巴達爾南部碉堡' WHERE entry=769; /* content: Dun Baldar South Bunker */
UPDATE mangos_string SET content_loc5='丹巴達爾北部碉堡' WHERE entry=770; /* content: Dun Baldar North Bunker */
UPDATE mangos_string SET content_loc5='雷矛墓地' WHERE entry=771; /* content: Stormpike Graveyard */
UPDATE mangos_string SET content_loc5='你達到了階級1:下士' WHERE entry=771; /* content: You have reached Rank 1: Corporal */
UPDATE mangos_string SET content_loc5='冰翼碉堡' WHERE entry=772; /* content: Icewing Bunker */
UPDATE mangos_string SET content_loc5='你達到了階級2:中尉' WHERE entry=772; /* content: You have reached Rank 2: First Lieutenant */
UPDATE mangos_string SET content_loc5='石爐墓地' WHERE entry=773; /* content: Stonehearth Graveyard */
UPDATE mangos_string SET content_loc5='石爐碉堡' WHERE entry=774; /* content: Stonehearth Bunker */
UPDATE mangos_string SET content_loc5='落雪墓地' WHERE entry=775; /* content: Snowfall Graveyard */
UPDATE mangos_string SET content_loc5='冰血哨塔' WHERE entry=776; /* content: Iceblood Tower */
UPDATE mangos_string SET content_loc5='冰血墓地' WHERE entry=777; /* content: Iceblood Graveyard */
UPDATE mangos_string SET content_loc5='哨塔高地' WHERE entry=778; /* content: Tower Point */
UPDATE mangos_string SET content_loc5='霜狼墓地' WHERE entry=779; /* content: Frostwolf Graveyard */
UPDATE mangos_string SET content_loc5='東部霜狼哨塔' WHERE entry=780; /* content: East Frostwolf Tower */
UPDATE mangos_string SET content_loc5='西部霜狼哨塔' WHERE entry=781; /* content: West Frostwolf Tower */
UPDATE mangos_string SET content_loc5='霜狼急救站' WHERE entry=782; /* content: Frostwolf Relief Hut */
UPDATE mangos_string SET content_loc5='奧特蘭克山谷一分鐘後開始戰鬥。' WHERE entry=784; /* content: 1 minute until the battle for Alterac Valley begins. */
UPDATE mangos_string SET content_loc5='奧特蘭克山谷的戰鬥開始了!' WHERE entry=786; /* content: The battle for Alterac Valley has begun! */
UPDATE mangos_string SET content_loc5='聯盟方的戰力即將耗盡了!' WHERE entry=787; /* content: The Alliance Team is running out of reinforcements! */
UPDATE mangos_string SET content_loc5='部落方的戰力即將耗盡了!' WHERE entry=788; /* content: The Horde Team is running out of reinforcements! */
UPDATE mangos_string SET content_loc5='部落的將軍死了!' WHERE entry=789; /* content: The Frostwolf General is Dead! */
UPDATE mangos_string SET content_loc5='雷矛將軍死了!' WHERE entry=790; /* content: The Stormpike General is Dead! */
UPDATE mangos_string SET content_loc5='公會註冊員' WHERE entry=811; /* content: Guild Master */
UPDATE mangos_string SET content_loc5='警告:你進入了禁航區，即將解除坐騎!' WHERE entry=816; /* content: Warning: You\'ve entered a no-fly zone and are about to be dismounted! */
UPDATE mangos_string SET content_loc5='警告:你進入了禁航區，即將解除坐騎!' WHERE entry=817; /* content: Warning: You\'ve entered a no-fly zone and are about to be dismounted! */
UPDATE mangos_string SET content_loc5='綠色' WHERE entry=1170; /* content: Green */
UPDATE mangos_string SET content_loc5='藍色' WHERE entry=1171; /* content: Blue */
UPDATE mangos_string SET content_loc5='紫色' WHERE entry=1172; /* content: Purple */
UPDATE mangos_string SET content_loc5='柳橙' WHERE entry=1173; /* content: Orange */
UPDATE mangos_string SET content_loc5='黃色' WHERE entry=1174; /* content: Yellow */
UPDATE mangos_string SET content_loc5='綠色' WHERE entry=1185; /* content: Green */
UPDATE mangos_string SET content_loc5='藍色' WHERE entry=1186; /* content: Blue */
UPDATE mangos_string SET content_loc5='紫色' WHERE entry=1187; /* content: Purple */
UPDATE mangos_string SET content_loc5='柳橙' WHERE entry=1188; /* content: Orange */
UPDATE mangos_string SET content_loc5='黃色' WHERE entry=1189; /* content: Yellow */
UPDATE mangos_string SET content_loc5='戰鬥將在1分鐘後開始。' WHERE entry=1206; /* content: The battle will begin in 1 minute. */
UPDATE mangos_string SET content_loc5='|cffffff00北地哨塔已被部落奪去!|r' WHERE entry=1600; /* content: |cffffff00Northpass Tower has been taken by the Horde!|r */
UPDATE mangos_string SET content_loc5='|cffffff00北地哨塔已被聯盟奪去!|r' WHERE entry=1601; /* content: |cffffff00Northpass Tower has been taken by the Alliance!|r */
UPDATE mangos_string SET content_loc5='|cffffff00皇冠哨塔已被部落奪去!|r' WHERE entry=1602; /* content: |cffffff00Crown Guard Tower has been taken by the Horde!|r */
UPDATE mangos_string SET content_loc5='|cffffff00皇冠哨塔已被聯盟奪去!|r' WHERE entry=1603; /* content: |cffffff00Crown Guard Tower has been taken by the Alliance!|r */
UPDATE mangos_string SET content_loc5='|cffffff00東牆之塔已被部落奪去!|r' WHERE entry=1604; /* content: |cffffff00Eastwall Tower has been taken by the Horde!|r */
UPDATE mangos_string SET content_loc5='|cffffff00東牆之塔已被聯盟奪去!|r' WHERE entry=1605; /* content: |cffffff00Eastwall Tower has been taken by the Alliance!|r */
UPDATE mangos_string SET content_loc5='|cffffff00病木林哨塔已被部落奪去!|r' WHERE entry=1606; /* content: |cffffff00The Plaguewood Tower has been taken by the Horde!|r */
UPDATE mangos_string SET content_loc5='|cffffff00病木林哨塔已被聯盟奪去!|r' WHERE entry=1607; /* content: |cffffff00The Plaguewood Tower has been taken by the Alliance!|r */
UPDATE mangos_string SET content_loc5='|cffffff00望海崖已被部落佔領!|r' WHERE entry=1608; /* content: |cffffff00The Overlook has been taken by the Horde!|r */
UPDATE mangos_string SET content_loc5='|cffffff00望海崖已被聯盟佔領!|r' WHERE entry=1609; /* content: |cffffff00The Overlook has been taken by the Alliance!|r */
UPDATE mangos_string SET content_loc5='|cffffff00競技場已被部落佔領!|r' WHERE entry=1610; /* content: |cffffff00The Stadium has been taken by the Horde!|r */
UPDATE mangos_string SET content_loc5='|cffffff00競技場已被聯盟佔領!|r' WHERE entry=1611; /* content: |cffffff00The Stadium has been taken by the Alliance!|r */
UPDATE mangos_string SET content_loc5='|cffffff00破碎之丘已被部落佔領!|r' WHERE entry=1612; /* content: |cffffff00Broken Hill has been taken by the Horde!|r */
UPDATE mangos_string SET content_loc5='|cffffff00破碎之丘已被聯盟佔領!|r' WHERE entry=1613; /* content: |cffffff00Broken Hill has been taken by the Alliance!|r */
UPDATE mangos_string SET content_loc5='|cffffff00部落已奪去東部哨塔控制權!|r' WHERE entry=1614; /* content: |cffffff00The Horde has taken control of the East Beacon!|r */
UPDATE mangos_string SET content_loc5='|cffffff00聯盟已奪去東部哨塔控制權!|r' WHERE entry=1615; /* content: |cffffff00The Alliance has taken control of the East Beacon!|r */
UPDATE mangos_string SET content_loc5='|cffffff00部落已奪去西部哨塔控制權!|r' WHERE entry=1616; /* content: |cffffff00The Horde has taken control of the West Beacon!|r */
UPDATE mangos_string SET content_loc5='|cffffff00聯盟已奪去西部哨塔控制權!|r' WHERE entry=1617; /* content: |cffffff00The Alliance has taken control of the West Beacon!|r */
UPDATE mangos_string SET content_loc5='|cffffff00部落已經控制住這兩座烽火臺!|r' WHERE entry=1618; /* content: |cffffff00The Horde has taken control of both beacons!|r */
UPDATE mangos_string SET content_loc5='|cffffff00聯盟已經控制住這座烽火臺!|r' WHERE entry=1619; /* content: |cffffff00The Alliance has taken control of both beacons!|r */
UPDATE mangos_string SET content_loc5='|cffffff00部落戰場斥候現在開始發送戰旗。|r' WHERE entry=1620; /* content: |cffffff00The Horde Field Scout is now issuing battle standards.|r */
UPDATE mangos_string SET content_loc5='|cffffff00聯盟戰場斥候現在開始發送戰旗。|r' WHERE entry=1621; /* content: |cffffff00The Alliance Field Scout is now issuing battle standards.|r */
UPDATE mangos_string SET content_loc5='|cffffff00部落已奪去雙塔廢墟控制權!|r' WHERE entry=1622; /* content: |cffffff00The Horde has taken control of Twin Spire Ruins!|r */
UPDATE mangos_string SET content_loc5='|cffffff00聯盟已奪去雙塔廢墟控制權!|r' WHERE entry=1623; /* content: |cffffff00The Alliance has taken control of Twin Spire Ruins!|r */
UPDATE mangos_string SET content_loc5='|cffffff00部落已經控制住一座靈魂尖塔!|r' WHERE entry=1624; /* content: |cffffff00The Horde has taken control of a Spirit Tower!|r */
UPDATE mangos_string SET content_loc5='|cffffff00聯盟已經控制住一座靈魂尖塔!|r' WHERE entry=1625; /* content: |cffffff00The Alliance has taken control of a Spirit Tower!|r */
UPDATE mangos_string SET content_loc5='|cffffff00部落已經失去一座靈魂尖塔的控制權!|r' WHERE entry=1626; /* content: |cffffff00The Horde has lost control of a Spirit Tower!|r */
UPDATE mangos_string SET content_loc5='|cffffff00聯盟已經失去一座靈魂尖塔的控制權!|r' WHERE entry=1627; /* content: |cffffff00The Alliance has lost control of a Spirit Tower!|r */
UPDATE mangos_string SET content_loc5='|cffffff00部落已經控制住白骨荒野!|r' WHERE entry=1628; /* content: |cffffff00The Horde has taken control of The Bone Wastes!|r */
UPDATE mangos_string SET content_loc5='|cffffff00聯盟已經控制住白骨荒野!|r' WHERE entry=1629; /* content: |cffffff00The Alliance has taken control of The Bone Wastes!|r */
UPDATE mangos_string SET content_loc5='|cffffff00部落獲得哈剌的控制權!|r' WHERE entry=1630; /* content: |cffffff00The Horde is gaining control of Halaa!|r */
UPDATE mangos_string SET content_loc5='|cffffff00聯盟獲得哈剌的控制權!|r' WHERE entry=1631; /* content: |cffffff00The Alliance is gaining control of Halaa!|r */
UPDATE mangos_string SET content_loc5='|cffffff00部落已經控制了哈剌!|r' WHERE entry=1632; /* content: |cffffff00The Horde has taken control of Halaa!|r */
UPDATE mangos_string SET content_loc5='|cffffff00聯盟已經控制了哈剌!|r' WHERE entry=1633; /* content: |cffffff00The Alliance has taken control of Halaa!|r */
UPDATE mangos_string SET content_loc5='|cffffff00哈剌毫無防禦!|r' WHERE entry=1634; /* content: |cffffff00Halaa is defenseless!|r */

SET NAMES 'latin1';
