-- File generated by MOTE (Mangos Online Translation Editor) v0.01
SET NAMES 'utf8';
UPDATE script_texts SET content_loc9='Arrivederci.' WHERE entry=-1000735; /* content: Farewell. */
UPDATE script_texts SET content_loc9='STATE IN GUARDIA!' WHERE entry=-1603116; /* content: Beware! */

SET NAMES 'latin1';
