-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `locales_achievement_reward` SET `subject_loc9`='Per l\'Alleanza!' WHERE `entry`=614;
UPDATE `locales_achievement_reward` SET `subject_loc9`='Avanti tutta, Ammiraglio!' WHERE `entry`=871;
UPDATE `locales_achievement_reward` SET `subject_loc9`='Il Diplomatico' WHERE `entry`=942;
UPDATE `locales_achievement_reward` SET `subject_loc9`='Il Diplomatico' WHERE `entry`=943;
UPDATE `locales_achievement_reward` SET `subject_loc9`='Grazie!' WHERE `entry`=1793;
UPDATE `locales_achievement_reward` SET `subject_loc9`='Grazie!' WHERE `entry`=1793;

SET NAMES 'latin1';
