-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE gossip_texts SET content_loc8='[PH] SD3 неизвестный текст' WHERE entry=-3000000; /* content: [PH] SD3 unknown text */
UPDATE gossip_texts SET content_loc8='Тарук послал меня, чтобы собрать то, что ты должен.' WHERE entry=-3000101; /* content: Taruk send me to collect what you owe. */
UPDATE gossip_texts SET content_loc8='Плати по счетам, Гарри!' WHERE entry=-3000102; /* content: Pay up, Harry! */
UPDATE gossip_texts SET content_loc8='Сейчас я готов отправиться в деревню.' WHERE entry=-3000103; /* content: I am ready to travel to you village now. */
UPDATE gossip_texts SET content_loc8='<Проверить импульс ...>' WHERE entry=-3000104; /* content: <Check for pulse...> */
UPDATE gossip_texts SET content_loc8='Иезекииль сказал, что у вас есть одна книга...' WHERE entry=-3000105; /* content: Ezekiel said that you might have a certain book... */
UPDATE gossip_texts SET content_loc8='Пусть маршал Виндзор знает, что я готова.' WHERE entry=-3000106; /* content: Let Marshal Windsor know that I am ready. */
UPDATE gossip_texts SET content_loc8='Я готова, как и мои войска. Давайте закончим этот маскарад!' WHERE entry=-3000107; /* content: I am ready, as are my forces. Let us end this masquerade! */
UPDATE gossip_texts SET content_loc8='Уделите мне минутку вашего времени, сэр.' WHERE entry=-3000108; /* content: I need a moment of your time, sir. */
UPDATE gossip_texts SET content_loc8='Я готова, Оронок. Давай уничтожим Цируха и освободим духов!' WHERE entry=-3000109; /* content: I am ready, Oronok. Let us destroy Cyrukh and free the elements! */
UPDATE gossip_texts SET content_loc8='Почему ... да, конечно. Мне есть что показать тебе прямо в этом здании, мистер Анвилвард.' WHERE entry=-3000110; /* content: Why... yes, of course. I\'ve something to show you right inside this building, Mr. Anvilward. */
UPDATE gossip_texts SET content_loc8='Поверните ключ, чтобы запустить механизм.' WHERE entry=-3000111; /* content: Turn the key to start the machine. */
UPDATE gossip_texts SET content_loc8='Я готов - давай убираемся отсюда.' WHERE entry=-3000112; /* content: I\'m ready - let\'s get out of here. */
UPDATE gossip_texts SET content_loc8='Продолжай, ты свободен. Убирайся отсюда!' WHERE entry=-3000113; /* content: Go on, you\'re free. Get out of here! */
UPDATE gossip_texts SET content_loc8='Э-э... Поддатый! Я готова начать дистилляцию.' WHERE entry=-3000114; /* content: I\'m ready to start the distillation, uh, Tipsy. */
UPDATE gossip_texts SET content_loc8='Я готов, Анкорит. Давайте начнем экзорцизм.' WHERE entry=-3006669; /* content: I am ready, Anchorite. Let us begin the exorcism. */
UPDATE gossip_texts SET content_loc8='Открой дверь во внутренний двор.' WHERE entry=-3033000; /* content: Please unlock the courtyard door. */
UPDATE gossip_texts SET content_loc8='Идем!' WHERE entry=-3043000; /* content: Let the event begin! */
UPDATE gossip_texts SET content_loc8='Я готова.' WHERE entry=-3090000; /* content: I am ready to begin. */
UPDATE gossip_texts SET content_loc8='Ты свободен, Дугал! Выбирайся отсюда!' WHERE entry=-3230000; /* content: You\'re free, Dughal! Get out of here! */
UPDATE gossip_texts SET content_loc8='Выбирайся отсюда, Тобиас, ты свободен!' WHERE entry=-3230001; /* content: Get out of here, Tobias, you\'re free! */
UPDATE gossip_texts SET content_loc8='Ваше рабство заканчивается, Doom\'rel. Я бросаю вам вызов!' WHERE entry=-3230002; /* content: Your bondage is at an end, Doom\'rel. I challenge you! */
UPDATE gossip_texts SET content_loc8='Почему бы вам с Камнеузлом не пойти и найти какое-нибудь укромное место...' WHERE entry=-3230003; /* content: Why don\'t you and Rocknot go find somewhere private... */
UPDATE gossip_texts SET content_loc8='Расскажите подробнее.' WHERE entry=-3409000; /* content: Tell me more. */
UPDATE gossip_texts SET content_loc8='Что еще вы хотели сказать?' WHERE entry=-3409001; /* content: What else do you have to say? */
UPDATE gossip_texts SET content_loc8='Вы бросили вызов нам, и мы пришли. Где этот мастер, о котором вы говорите?' WHERE entry=-3409002; /* content: You challenged us and we have come. Where is this master you speak of? */
UPDATE gossip_texts SET content_loc8='Я не сделала ни одной ошибки.' WHERE entry=-3469000; /* content: I\'ve made no mistakes. */
UPDATE gossip_texts SET content_loc8='Ты совсем свихнулся, Нефарий. Ты разговариваешь загадками.' WHERE entry=-3469001; /* content: You have lost your mind, Nefarius. You speak in riddles. */
UPDATE gossip_texts SET content_loc8='Давай.' WHERE entry=-3469002; /* content: Please do. */
UPDATE gossip_texts SET content_loc8='Не могу, Валестраз! Ведь есть же какой-то способ тебя вылечить!' WHERE entry=-3469003; /* content: I cannot, Vaelastrasz! Surely something can be done to heal you! */
UPDATE gossip_texts SET content_loc8='Валестраз, нет!!!' WHERE entry=-3469004; /* content: Vaelastrasz, no!!! */
UPDATE gossip_texts SET content_loc8='Давай разберемся.' WHERE entry=-3509000; /* content: Let\'s find out. */
UPDATE gossip_texts SET content_loc8='Посмотрим, что у тебя есть.' WHERE entry=-3509001; /* content: Let\'s see what you have. */
UPDATE gossip_texts SET content_loc8='Телепортируйте меня в Библиотеку Хранителя' WHERE entry=-3532000; /* content: Teleport me to the Guardian\'s Library */
UPDATE gossip_texts SET content_loc8='Я не актер.' WHERE entry=-3532001; /* content: I\'m not an actor. */
UPDATE gossip_texts SET content_loc8='Хорошо, тогда я попробую.' WHERE entry=-3532002; /* content: Ok, I\'ll give it a try, then. */
UPDATE gossip_texts SET content_loc8='Никогда еще не была так готова!' WHERE entry=-3532003; /* content: I\'ve never been more ready. */
UPDATE gossip_texts SET content_loc8='Волк будет побежден.' WHERE entry=-3532004; /* content: The wolf\'s going down. */
UPDATE gossip_texts SET content_loc8='Какая у вас бабушка phat lewtz?' WHERE entry=-3532005; /* content: What phat lewtz you have grandmother? */
UPDATE gossip_texts SET content_loc8='Управление Рубакой' WHERE entry=-3532006; /* content: Control Orc Grunt */
UPDATE gossip_texts SET content_loc8='Управление Волком' WHERE entry=-3532007; /* content: Control Orc Wolf */
UPDATE gossip_texts SET content_loc8='Управление Призванным демоном' WHERE entry=-3532008; /* content: Control Summoned Daemon */
UPDATE gossip_texts SET content_loc8='Управление Чернокнижником' WHERE entry=-3532009; /* content: Control Orc Warlock */
UPDATE gossip_texts SET content_loc8='Управление Некролитом' WHERE entry=-3532010; /* content: Control Orc Necrolyte */
UPDATE gossip_texts SET content_loc8='Управление Боевым вождем Черноруком' WHERE entry=-3532011; /* content: Control Warchief Blackhand */
UPDATE gossip_texts SET content_loc8='Контроль над пехотинцем людей' WHERE entry=-3532012; /* content: Control Human Footman */
UPDATE gossip_texts SET content_loc8='Контрольное зарядное устройство человека' WHERE entry=-3532013; /* content: Control Human Charger */
UPDATE gossip_texts SET content_loc8='Элемент управления связанным водным элементом' WHERE entry=-3532014; /* content: Control Conjured Water Elemental */
UPDATE gossip_texts SET content_loc8='Управление Кудесником' WHERE entry=-3532015; /* content: Control Human Conjurer */
UPDATE gossip_texts SET content_loc8='Управление Священником' WHERE entry=-3532016; /* content: Control Human Cleric */
UPDATE gossip_texts SET content_loc8='Управление королем Ллейном' WHERE entry=-3532017; /* content: Control King Llane */
UPDATE gossip_texts SET content_loc8='Пожалуйста, расставь фигуры заново: мы хотим сыграть еще раз.' WHERE entry=-3532018; /* content: Please reset the chess board, we would like to play again. */
UPDATE gossip_texts SET content_loc8='Мои спутники и я – с вами, леди Праудмур.' WHERE entry=-3534000; /* content: My companions and I are with you, Lady Proudmoore. */
UPDATE gossip_texts SET content_loc8='Мы готовы встретить любого, кого пошлет Архимонд, леди Праудмур.' WHERE entry=-3534001; /* content: We are ready for whatever Archimonde might send our way, Lady Proudmoore. */
UPDATE gossip_texts SET content_loc8='До новой встречи, леди Праудмур!' WHERE entry=-3534002; /* content: Until we meet again, Lady Proudmoore. */
UPDATE gossip_texts SET content_loc8='Я с тобой, Тралл.' WHERE entry=-3534003; /* content: I am with you, Thrall. */
UPDATE gossip_texts SET content_loc8='Нам нечего бояться.' WHERE entry=-3534004; /* content: We have nothing to fear. */
UPDATE gossip_texts SET content_loc8='До встречи, Тралл.' WHERE entry=-3534005; /* content: Until we meet again, Thrall. */
UPDATE gossip_texts SET content_loc8='Любая ваша помощь будет неоценима, жрица.' WHERE entry=-3534006; /* content: I would be grateful for any aid you can provide, Priestess. */
UPDATE gossip_texts SET content_loc8='Мы готовы забрать тебя отсюда, Тралл! Пошли!' WHERE entry=-3560000; /* content: We are ready to get you out of here, Thrall. Let\'s go! */
UPDATE gossip_texts SET content_loc8='Мне нужна упаковка зажигательных бомб.' WHERE entry=-3560001; /* content: I need a pack of Incendiary Bombs. */
UPDATE gossip_texts SET content_loc8='Тарета тебя не видит, Тралл.' WHERE entry=-3560002; /* content: Taretha cannot see you, Thrall. */
UPDATE gossip_texts SET content_loc8='Все очень непросто, Тралл. Тебе сейчас лучше будет укрыться в горах, пока не пришли новые бойцы Блэкмора. Мы проследим, чтобы Тарета оказалась в безопасности.' WHERE entry=-3560003; /* content: The situation is rather complicated, Thrall. It would be best for you to head into the mountains now, before more of Blackmoore\'s men show up. We\'ll make sure Taretha is safe. */
UPDATE gossip_texts SET content_loc8='Мы готовы, Тралл!' WHERE entry=-3560004; /* content: We\'re ready, Thrall. */
UPDATE gossip_texts SET content_loc8='Странный волшебник?' WHERE entry=-3560005; /* content: Strange wizard? */
UPDATE gossip_texts SET content_loc8='Мы вытащим тебя. Тарета. Не волнуйся. Я сомневаюсь, что волшебник блуждает слишком далеко.' WHERE entry=-3560006; /* content: We\'ll get you out. Taretha. Don\'t worry. I doubt the wizard would wander too far away. */
UPDATE gossip_texts SET content_loc8='Мельница Таррен' WHERE entry=-3560007; /* content: Tarren Mill. */
UPDATE gossip_texts SET content_loc8='Я с тобой, Акама.' WHERE entry=-3564000; /* content: I\'m with you, Akama. */
UPDATE gossip_texts SET content_loc8='Я готова, Акама!' WHERE entry=-3564001; /* content: I\'m ready, Akama. */
UPDATE gossip_texts SET content_loc8='Мы готовы встретиться с Иллиданом лицом к лицу.' WHERE entry=-3564002; /* content: We\'re ready to face Illidan. */
UPDATE gossip_texts SET content_loc8='Спасибо на добром слове, но мы хотим побродить по Зул\'Аману.' WHERE entry=-3568000; /* content: Thanks for the concern, but we intend to explore Zul\'Aman. */
UPDATE gossip_texts SET content_loc8='Что они, по-твоему, замышляют?' WHERE entry=-3595000; /* content: What do you think they\'re up to? */
UPDATE gossip_texts SET content_loc8='Что ты хочешь, чтобы я сделал?' WHERE entry=-3595001; /* content: You want me to do what? */
UPDATE gossip_texts SET content_loc8='Отлично, Хроми.' WHERE entry=-3595002; /* content: Very well, Chromie. */
UPDATE gossip_texts SET content_loc8='Почему меня отправили именно в это время и место?' WHERE entry=-3595003; /* content: Why have I been sent back to this particular place and time? */
UPDATE gossip_texts SET content_loc8='Какое решение было принято?' WHERE entry=-3595004; /* content: What was this decision? */
UPDATE gossip_texts SET content_loc8='И как драконы Бесконечности собираются вмешаться?' WHERE entry=-3595005; /* content: So how does the Infinite Dragonflight plan to interfere? */
UPDATE gossip_texts SET content_loc8='Хроми, мы оба прекрасно знаем, что случится в этом временном потоке. Мы это уже проходили.$B$BДавай, что ли, ближе к делу.' WHERE entry=-3595006; /* content: Chromie, you and I both know what\'s going to happen in this time stream. We\'ve seen this all before.$B$BCan you just skip us ahead to all the real action? */
UPDATE gossip_texts SET content_loc8='Да, пожалуйста!' WHERE entry=-3595007; /* content: Yes, please! */
UPDATE gossip_texts SET content_loc8='Бранн, это было бы честью для нас!' WHERE entry=-3599000; /* content: Brann, it would be our honor! */
UPDATE gossip_texts SET content_loc8='Давайте переместим Бранна, достаточно урока истории!' WHERE entry=-3599001; /* content: Let\'s move Brann, enough of the history lessons! */
UPDATE gossip_texts SET content_loc8='Перенестись в Главный лагерь экспедиции.' WHERE entry=-3603000; /* content: Teleport to the Expedition Base Camp. */
UPDATE gossip_texts SET content_loc8='Перенестись на Плац.' WHERE entry=-3603001; /* content: Teleport to the Formation Grounds. */
UPDATE gossip_texts SET content_loc8='Перенестись в Гигантскую кузню.' WHERE entry=-3603002; /* content: Teleport to the Colossal Forge. */
UPDATE gossip_texts SET content_loc8='Перенестись на Мусорную свалку.' WHERE entry=-3603003; /* content: Teleport to the Scrapyard. */
UPDATE gossip_texts SET content_loc8='Перенестись в Вестибюль.' WHERE entry=-3603004; /* content: Teleport to the Antechamber of Ulduar. */
UPDATE gossip_texts SET content_loc8='Перенестись в Обвалившуюся галерею.' WHERE entry=-3603005; /* content: Teleport to the Shattered Walkway. */
UPDATE gossip_texts SET content_loc8='Перенестись в Оранжерею Жизни.' WHERE entry=-3603006; /* content: Teleport to the Conservatory of Life. */
UPDATE gossip_texts SET content_loc8='Перенестись в Искру Воображения.' WHERE entry=-3603007; /* content: Teleport to the Spark of Imagination. */
UPDATE gossip_texts SET content_loc8='Перенестись в темницу Йогг-Сарона.' WHERE entry=-3603008; /* content: Teleport to the Prison of Yogg-Saron. */
UPDATE gossip_texts SET content_loc8='Мы готовы помочь!' WHERE entry=-3603009; /* content: We are ready to help! */
UPDATE gossip_texts SET content_loc8='Активировать вторичные оборонные системы.' WHERE entry=-3603010; /* content: Activate secondary defensive systems. */
UPDATE gossip_texts SET content_loc8='Подтверждаю.' WHERE entry=-3603011; /* content: Confirmed. */
UPDATE gossip_texts SET content_loc8='Мы готовы. Начнем наступление!' WHERE entry=-3603012; /* content: We\'re ready. Begin the assault! */
UPDATE gossip_texts SET content_loc8='Помоги нам, хранитель. Вместе мы одолеем Йогг-Сарона.' WHERE entry=-3603013; /* content: Lend us your aid, keeper. Together we will defeat Yogg-Saron. */
UPDATE gossip_texts SET content_loc8='Да.' WHERE entry=-3603014; /* content: Yes. */
UPDATE gossip_texts SET content_loc8='Активируйте кристаллы, когда мы попадаем в беду, не так ли?' WHERE entry=-3608000; /* content: Activate the crystals when we get in trouble, right? */
UPDATE gossip_texts SET content_loc8='Уведи своих в безопасное укрытие, мы будем держать оборону.' WHERE entry=-3608001; /* content: Get your people to safety, we\'ll keep the Blue Dragonflight\'s forces at bay. */
UPDATE gossip_texts SET content_loc8='Я не сражаюсь, пошлите меня!' WHERE entry=-3608002; /* content: I\'m not fighting, so send me in now! */
UPDATE gossip_texts SET content_loc8='Я вызываю тебя на бой, рыцарь смерти!' WHERE entry=-3609000; /* content: I challenge you, death knight! */
UPDATE gossip_texts SET content_loc8='Я готов, верховный лорд. Да начнется осада часовни Последней Надежды!' WHERE entry=-3609001; /* content: I am ready, Highlord. Let the siege of Light\'s Hope begin! */
UPDATE gossip_texts SET content_loc8='Мы готовы к грядущим испытаниям.' WHERE entry=-3649000; /* content: Yes. We are prepared for the challenges ahead of us. */
UPDATE gossip_texts SET content_loc8='Начинайте первое испытание!' WHERE entry=-3649001; /* content: Bring forth the first challenge! */
UPDATE gossip_texts SET content_loc8='Мы хотим еще раз попробовать сразиться с этими чудовищами!' WHERE entry=-3649002; /* content: We want another shot at those beasts! */
UPDATE gossip_texts SET content_loc8='Какое испытание ожидает нас дальше?' WHERE entry=-3649003; /* content: What new challenge awaits us? */
UPDATE gossip_texts SET content_loc8='Мы готовы снова сразиться с чародеем.' WHERE entry=-3649004; /* content: We\'re ready to fight the sorceror again. */
UPDATE gossip_texts SET content_loc8='Конечно!' WHERE entry=-3649005; /* content: Of course! */
UPDATE gossip_texts SET content_loc8='Подавай сигнал! Мы готовы!' WHERE entry=-3649006; /* content: Give the signal! We\'re ready to go! */
UPDATE gossip_texts SET content_loc8='Это в самом деле было так сложно?' WHERE entry=-3649007; /* content: That tough, huh? */
UPDATE gossip_texts SET content_loc8='Валькир? Мы готовы к ним' WHERE entry=-3649008; /* content: Val\'kyr? We\'re ready for them */
UPDATE gossip_texts SET content_loc8='Благодарим за добрые слова, распорядитель Колизея.' WHERE entry=-3649009; /* content: Your words of praise are appreciated, Coliseum Master. */
UPDATE gossip_texts SET content_loc8='Как странно...' WHERE entry=-3649010; /* content: That is strange... */
UPDATE gossip_texts SET content_loc8='Я готов.' WHERE entry=-3650000; /* content: I am ready. */
UPDATE gossip_texts SET content_loc8='Я готова. Только давай обойдемся без показухи.' WHERE entry=-3650001; /* content: I am ready. However, I\'d like to skip the pageantry. */
UPDATE gossip_texts SET content_loc8='Я готова к следующему испытанию.' WHERE entry=-3650002; /* content: I am ready for the next challenge. */

SET NAMES 'latin1';
