-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE gossip_texts SET content_loc7='[PH] SD3 texto desconocido' WHERE entry=-3000000; /* content: [PH] SD3 unknown text */
UPDATE gossip_texts SET content_loc7='Taruk me envía a recoger lo que debes.' WHERE entry=-3000101; /* content: Taruk send me to collect what you owe. */
UPDATE gossip_texts SET content_loc7='¡Paga, Harry!' WHERE entry=-3000102; /* content: Pay up, Harry! */
UPDATE gossip_texts SET content_loc7='Estoy listo para viajar a tu pueblo ahora.' WHERE entry=-3000103; /* content: I am ready to travel to you village now. */
UPDATE gossip_texts SET content_loc7='<Buscar pulso ...>' WHERE entry=-3000104; /* content: <Check for pulse...> */
UPDATE gossip_texts SET content_loc7='Ezekiel dijo que tú podrías tener cierto libro...' WHERE entry=-3000105; /* content: Ezekiel said that you might have a certain book... */
UPDATE gossip_texts SET content_loc7='Haz saber al mariscal Windsor que ya estoy lista.' WHERE entry=-3000106; /* content: Let Marshal Windsor know that I am ready. */
UPDATE gossip_texts SET content_loc7='Estoy lista; y también lo están mis tropas. ¡Acabemos con esta farsa!' WHERE entry=-3000107; /* content: I am ready, as are my forces. Let us end this masquerade! */
UPDATE gossip_texts SET content_loc7='Necesito un momento de su tiempo, señor.' WHERE entry=-3000108; /* content: I need a moment of your time, sir. */
UPDATE gossip_texts SET content_loc7='Estoy preparada, Oronok. ¡Destruyamos a Cyrukh y liberemos los elementos!' WHERE entry=-3000109; /* content: I am ready, Oronok. Let us destroy Cyrukh and free the elements! */
UPDATE gossip_texts SET content_loc7='Por qué ... sí, por supuesto. Tengo algo que mostrarle dentro de este edificio, Sr. Anvilward.' WHERE entry=-3000110; /* content: Why... yes, of course. I\'ve something to show you right inside this building, Mr. Anvilward. */
UPDATE gossip_texts SET content_loc7='Gira la llave para poner en marcha la máquina.' WHERE entry=-3000111; /* content: Turn the key to start the machine. */
UPDATE gossip_texts SET content_loc7='Estoy listo, salgamos de aquí.' WHERE entry=-3000112; /* content: I\'m ready - let\'s get out of here. */
UPDATE gossip_texts SET content_loc7='Sigue, eres libre. ¡Sal de aquí!' WHERE entry=-3000113; /* content: Go on, you\'re free. Get out of here! */
UPDATE gossip_texts SET content_loc7='Estoy lista para empezar la destilación, eh, Chispa.' WHERE entry=-3000114; /* content: I\'m ready to start the distillation, uh, Tipsy. */
UPDATE gossip_texts SET content_loc7='Estoy listo, anacoreta. Comencemos el exorcismo.' WHERE entry=-3006669; /* content: I am ready, Anchorite. Let us begin the exorcism. */
UPDATE gossip_texts SET content_loc7='Por favor, abre la cerradura de la puerta del patio.' WHERE entry=-3033000; /* content: Please unlock the courtyard door. */
UPDATE gossip_texts SET content_loc7='¡Que empiece la sesión!' WHERE entry=-3043000; /* content: Let the event begin! */
UPDATE gossip_texts SET content_loc7='Estoy lista para empezar.' WHERE entry=-3090000; /* content: I am ready to begin. */
UPDATE gossip_texts SET content_loc7='¡Eres libre, Dughal! ¡Márchate!' WHERE entry=-3230000; /* content: You\'re free, Dughal! Get out of here! */
UPDATE gossip_texts SET content_loc7='¡Sal de aquí, Tobias! ¡Eres libre!' WHERE entry=-3230001; /* content: Get out of here, Tobias, you\'re free! */
UPDATE gossip_texts SET content_loc7='Tu esclavitud ha llegado a su fin, Doom\'rel. ¡Te desafío!' WHERE entry=-3230002; /* content: Your bondage is at an end, Doom\'rel. I challenge you! */
UPDATE gossip_texts SET content_loc7='¿Por qué tú y Sinroca no buscáis un lugar más tranquilito...?' WHERE entry=-3230003; /* content: Why don\'t you and Rocknot go find somewhere private... */
UPDATE gossip_texts SET content_loc7='Cuéntame más.' WHERE entry=-3409000; /* content: Tell me more. */
UPDATE gossip_texts SET content_loc7='¿Qué más tienes que decir?' WHERE entry=-3409001; /* content: What else do you have to say? */
UPDATE gossip_texts SET content_loc7='Nos desafiaste y hemos venido. ¿De dónde es este maestro del que hablas?' WHERE entry=-3409002; /* content: You challenged us and we have come. Where is this master you speak of? */
UPDATE gossip_texts SET content_loc7='No he cometido ningún error.' WHERE entry=-3469000; /* content: I\'ve made no mistakes. */
UPDATE gossip_texts SET content_loc7='Has perdido la cabeza, Nefarius. Hablas con acertijos.' WHERE entry=-3469001; /* content: You have lost your mind, Nefarius. You speak in riddles. */
UPDATE gossip_texts SET content_loc7='Hazlo, por favor.' WHERE entry=-3469002; /* content: Please do. */
UPDATE gossip_texts SET content_loc7='¡No puedo, Vaelastrasz! ¡Tiene que haber algo que podamos hacer para curarte!' WHERE entry=-3469003; /* content: I cannot, Vaelastrasz! Surely something can be done to heal you! */
UPDATE gossip_texts SET content_loc7='¡¡¡Vaelastrasz, no!!!' WHERE entry=-3469004; /* content: Vaelastrasz, no!!! */
UPDATE gossip_texts SET content_loc7='Comprobémoslo.' WHERE entry=-3509000; /* content: Let\'s find out. */
UPDATE gossip_texts SET content_loc7='Veamos qué tienes.' WHERE entry=-3509001; /* content: Let\'s see what you have. */
UPDATE gossip_texts SET content_loc7='Teletransportarme a la biblioteca del guardián' WHERE entry=-3532000; /* content: Teleport me to the Guardian\'s Library */
UPDATE gossip_texts SET content_loc7='No soy actriz.' WHERE entry=-3532001; /* content: I\'m not an actor. */
UPDATE gossip_texts SET content_loc7='De acuerdo, lo intentaré.' WHERE entry=-3532002; /* content: Ok, I\'ll give it a try, then. */
UPDATE gossip_texts SET content_loc7='Nunca he estado más preparada.' WHERE entry=-3532003; /* content: I\'ve never been more ready. */
UPDATE gossip_texts SET content_loc7='El lobo está bajando.' WHERE entry=-3532004; /* content: The wolf\'s going down. */
UPDATE gossip_texts SET content_loc7='¿Qué phat lewtz tienes abuela?' WHERE entry=-3532005; /* content: What phat lewtz you have grandmother? */
UPDATE gossip_texts SET content_loc7='Controlar bruto orco' WHERE entry=-3532006; /* content: Control Orc Grunt */
UPDATE gossip_texts SET content_loc7='Controlar lobo orco' WHERE entry=-3532007; /* content: Control Orc Wolf */
UPDATE gossip_texts SET content_loc7='Controlar belcebú invocado' WHERE entry=-3532008; /* content: Control Summoned Daemon */
UPDATE gossip_texts SET content_loc7='Controlar orco brujo' WHERE entry=-3532009; /* content: Control Orc Warlock */
UPDATE gossip_texts SET content_loc7='Controlar necrólito orco' WHERE entry=-3532010; /* content: Control Orc Necrolyte */
UPDATE gossip_texts SET content_loc7='Controlar jefe de guerra Puño Negro' WHERE entry=-3532011; /* content: Control Warchief Blackhand */
UPDATE gossip_texts SET content_loc7='Controlar lacayo humano' WHERE entry=-3532012; /* content: Control Human Footman */
UPDATE gossip_texts SET content_loc7='Control del Cargador Humano' WHERE entry=-3532013; /* content: Control Human Charger */
UPDATE gossip_texts SET content_loc7='Control de Elemento de Agua Conjurada' WHERE entry=-3532014; /* content: Control Conjured Water Elemental */
UPDATE gossip_texts SET content_loc7='Controlar conjurador humano' WHERE entry=-3532015; /* content: Control Human Conjurer */
UPDATE gossip_texts SET content_loc7='Controlar clérigo humano' WHERE entry=-3532016; /* content: Control Human Cleric */
UPDATE gossip_texts SET content_loc7='Controlar rey Llane' WHERE entry=-3532017; /* content: Control King Llane */
UPDATE gossip_texts SET content_loc7='Reinicia el tablero, queremos jugar de nuevo.' WHERE entry=-3532018; /* content: Please reset the chess board, we would like to play again. */
UPDATE gossip_texts SET content_loc7='Mis compañeros y yo estamos contigo, Lady Valiente.' WHERE entry=-3534000; /* content: My companions and I are with you, Lady Proudmoore. */
UPDATE gossip_texts SET content_loc7='Estamos listos para cualquier cosa que Archimonde nos mande, lady Valiente.' WHERE entry=-3534001; /* content: We are ready for whatever Archimonde might send our way, Lady Proudmoore. */
UPDATE gossip_texts SET content_loc7='Hasta que nos volvamos a encontrar, Lady Valiente.' WHERE entry=-3534002; /* content: Until we meet again, Lady Proudmoore. */
UPDATE gossip_texts SET content_loc7='Estoy contigo, Thrall.' WHERE entry=-3534003; /* content: I am with you, Thrall. */
UPDATE gossip_texts SET content_loc7='No tenemos nada que temer.' WHERE entry=-3534004; /* content: We have nothing to fear. */
UPDATE gossip_texts SET content_loc7='Hasta que nos volvamos a encontrar, Thrall.' WHERE entry=-3534005; /* content: Until we meet again, Thrall. */
UPDATE gossip_texts SET content_loc7='Agradecería cualquier ayuda que me pudieras prestar, sacerdotisa.' WHERE entry=-3534006; /* content: I would be grateful for any aid you can provide, Priestess. */
UPDATE gossip_texts SET content_loc7='Estamos listos para sacarte de aquí, Thrall. ¡Vamos!' WHERE entry=-3560000; /* content: We are ready to get you out of here, Thrall. Let\'s go! */
UPDATE gossip_texts SET content_loc7='Necesito un paquete de bombas incendiarias.' WHERE entry=-3560001; /* content: I need a pack of Incendiary Bombs. */
UPDATE gossip_texts SET content_loc7='Taretha no puede verte, Thrall.' WHERE entry=-3560002; /* content: Taretha cannot see you, Thrall. */
UPDATE gossip_texts SET content_loc7='La situación es bastante compleja, Thrall. Por ahora lo mejor será que te dirijas a las montañas antes de que aparezcan los hombres de Lodonegro. Me aseguraré de que Taretha no corra peligro.' WHERE entry=-3560003; /* content: The situation is rather complicated, Thrall. It would be best for you to head into the mountains now, before more of Blackmoore\'s men show up. We\'ll make sure Taretha is safe. */
UPDATE gossip_texts SET content_loc7='Estamos listos, Thrall.' WHERE entry=-3560004; /* content: We\'re ready, Thrall. */
UPDATE gossip_texts SET content_loc7='¿Un zahorí extraño?' WHERE entry=-3560005; /* content: Strange wizard? */
UPDATE gossip_texts SET content_loc7='Te sacaremos. Taretha. No te preocupes. Dudo que el mago se aleje demasiado.' WHERE entry=-3560006; /* content: We\'ll get you out. Taretha. Don\'t worry. I doubt the wizard would wander too far away. */
UPDATE gossip_texts SET content_loc7='Molino Tarren.' WHERE entry=-3560007; /* content: Tarren Mill. */
UPDATE gossip_texts SET content_loc7='Estoy contigo, Akama.' WHERE entry=-3564000; /* content: I\'m with you, Akama. */
UPDATE gossip_texts SET content_loc7='Estoy listo, Akama.' WHERE entry=-3564001; /* content: I\'m ready, Akama. */
UPDATE gossip_texts SET content_loc7='Estamos listos para enfrentarnos a Illidan.' WHERE entry=-3564002; /* content: We\'re ready to face Illidan. */
UPDATE gossip_texts SET content_loc7='Gracias por tu interés, pero tenemos intención de explorar Zul\'Aman.' WHERE entry=-3568000; /* content: Thanks for the concern, but we intend to explore Zul\'Aman. */
UPDATE gossip_texts SET content_loc7='¿Qué crees que se traen entre manos?' WHERE entry=-3595000; /* content: What do you think they\'re up to? */
UPDATE gossip_texts SET content_loc7='¿Quieres que haga qué?' WHERE entry=-3595001; /* content: You want me to do what? */
UPDATE gossip_texts SET content_loc7='Muy bien, Cromi.' WHERE entry=-3595002; /* content: Very well, Chromie. */
UPDATE gossip_texts SET content_loc7='¿Por qué me han enviado de vuelta a este lugar concreto en este momento en particular?' WHERE entry=-3595003; /* content: Why have I been sent back to this particular place and time? */
UPDATE gossip_texts SET content_loc7='¿Qué ha sido esta decisión?' WHERE entry=-3595004; /* content: What was this decision? */
UPDATE gossip_texts SET content_loc7='¿Cómo pretende interferir el Vuelo Infinito?' WHERE entry=-3595005; /* content: So how does the Infinite Dragonflight plan to interfere? */
UPDATE gossip_texts SET content_loc7='Cromi, tú y yo sabemos lo que va a ocurrir a continuación. Ya lo hemos visto antes.$B$B¿No podemos saltárnoslo todo y pasar a la acción de verdad?' WHERE entry=-3595006; /* content: Chromie, you and I both know what\'s going to happen in this time stream. We\'ve seen this all before.$B$BCan you just skip us ahead to all the real action? */
UPDATE gossip_texts SET content_loc7='¡Sí, por favor!' WHERE entry=-3595007; /* content: Yes, please! */
UPDATE gossip_texts SET content_loc7='¡Brann, será un honor!' WHERE entry=-3599000; /* content: Brann, it would be our honor! */
UPDATE gossip_texts SET content_loc7='¡Muevamos Brann, ya basta de la lección de historia!' WHERE entry=-3599001; /* content: Let\'s move Brann, enough of the history lessons! */
UPDATE gossip_texts SET content_loc7='Teletransporte al Campamento Base de la Expedición.' WHERE entry=-3603000; /* content: Teleport to the Expedition Base Camp. */
UPDATE gossip_texts SET content_loc7='Teletransporte al Campo de Formación.' WHERE entry=-3603001; /* content: Teleport to the Formation Grounds. */
UPDATE gossip_texts SET content_loc7='Teletransporte a La Forja Colosal.' WHERE entry=-3603002; /* content: Teleport to the Colossal Forge. */
UPDATE gossip_texts SET content_loc7='Teletransporte a La Chatarrería.' WHERE entry=-3603003; /* content: Teleport to the Scrapyard. */
UPDATE gossip_texts SET content_loc7='Teletransporte a La Antecámara de Ulduar.' WHERE entry=-3603004; /* content: Teleport to the Antechamber of Ulduar. */
UPDATE gossip_texts SET content_loc7='Teletransporte a La Pasarela Devastada.' WHERE entry=-3603005; /* content: Teleport to the Shattered Walkway. */
UPDATE gossip_texts SET content_loc7='Teletransporte a El Invernadero de Vida.' WHERE entry=-3603006; /* content: Teleport to the Conservatory of Life. */
UPDATE gossip_texts SET content_loc7='Teletransporte a La Chispa de la Imaginación.' WHERE entry=-3603007; /* content: Teleport to the Spark of Imagination. */
UPDATE gossip_texts SET content_loc7='Teletransporte a La Prisión de Yogg-Saron.' WHERE entry=-3603008; /* content: Teleport to the Prison of Yogg-Saron. */
UPDATE gossip_texts SET content_loc7='¡Estamos listos para ayudar!' WHERE entry=-3603009; /* content: We are ready to help! */
UPDATE gossip_texts SET content_loc7='Activad sistemas de defensa secundarios.' WHERE entry=-3603010; /* content: Activate secondary defensive systems. */
UPDATE gossip_texts SET content_loc7='Confirmado.' WHERE entry=-3603011; /* content: Confirmed. */
UPDATE gossip_texts SET content_loc7='Estamos listos. ¡Que comience el asalto!' WHERE entry=-3603012; /* content: We\'re ready. Begin the assault! */
UPDATE gossip_texts SET content_loc7='Préstanos tu ayuda, vigilante. Juntos derrotaremos a Yogg-Saron.' WHERE entry=-3603013; /* content: Lend us your aid, keeper. Together we will defeat Yogg-Saron. */
UPDATE gossip_texts SET content_loc7='Sí.' WHERE entry=-3603014; /* content: Yes. */
UPDATE gossip_texts SET content_loc7='Activa los cristales cuando tengamos problemas, ¿verdad?' WHERE entry=-3608000; /* content: Activate the crystals when we get in trouble, right? */
UPDATE gossip_texts SET content_loc7='Pon a salvo a tu gente; nosotros mantendremos a raya a los ejércitos del Vuelo Azul.' WHERE entry=-3608001; /* content: Get your people to safety, we\'ll keep the Blue Dragonflight\'s forces at bay. */
UPDATE gossip_texts SET content_loc7='Yo no me estoy peleando, ¡así que mándame ahí ahora!' WHERE entry=-3608002; /* content: I\'m not fighting, so send me in now! */
UPDATE gossip_texts SET content_loc7='¡Te reto, caballero de la Muerte!' WHERE entry=-3609000; /* content: I challenge you, death knight! */
UPDATE gossip_texts SET content_loc7='Estoy preparada, Alto Señor. ¡Que comience el asedio a Esperanza de la Luz!' WHERE entry=-3609001; /* content: I am ready, Highlord. Let the siege of Light\'s Hope begin! */
UPDATE gossip_texts SET content_loc7='Sí. Estamos preparados para los retos que nos aguardan.' WHERE entry=-3649000; /* content: Yes. We are prepared for the challenges ahead of us. */
UPDATE gossip_texts SET content_loc7='¡Adelante con el primer reto!' WHERE entry=-3649001; /* content: Bring forth the first challenge! */
UPDATE gossip_texts SET content_loc7='¡Queremos volver a intentarlo contra esas bestias!' WHERE entry=-3649002; /* content: We want another shot at those beasts! */
UPDATE gossip_texts SET content_loc7='¿Qué nuevo reto nos aguarda?' WHERE entry=-3649003; /* content: What new challenge awaits us? */
UPDATE gossip_texts SET content_loc7='Estamos preparados para luchar contra el hechicero de nuevo.' WHERE entry=-3649004; /* content: We\'re ready to fight the sorceror again. */
UPDATE gossip_texts SET content_loc7='¡Claro!' WHERE entry=-3649005; /* content: Of course! */
UPDATE gossip_texts SET content_loc7='¡Da la señal! ¡Estamos preparados!' WHERE entry=-3649006; /* content: Give the signal! We\'re ready to go! */
UPDATE gossip_texts SET content_loc7='Tan duro, ¿eh?' WHERE entry=-3649007; /* content: That tough, huh? */
UPDATE gossip_texts SET content_loc7='Val\'kyr? Estamos listos para ellos' WHERE entry=-3649008; /* content: Val\'kyr? We\'re ready for them */
UPDATE gossip_texts SET content_loc7='Apreciamos tus palabras de alabanza, maestro del coliseo.' WHERE entry=-3649009; /* content: Your words of praise are appreciated, Coliseum Master. */
UPDATE gossip_texts SET content_loc7='Esto es extraño...' WHERE entry=-3649010; /* content: That is strange... */
UPDATE gossip_texts SET content_loc7='Estoy preparada.' WHERE entry=-3650000; /* content: I am ready. */
UPDATE gossip_texts SET content_loc7='Estoy preparada, pero me gustaría saltarme las ostentaciones' WHERE entry=-3650001; /* content: I am ready. However, I\'d like to skip the pageantry. */
UPDATE gossip_texts SET content_loc7='Estoy preparada para el siguiente reto.' WHERE entry=-3650002; /* content: I am ready for the next challenge. */

SET NAMES 'latin1';
