-- File generated by Mangos Online Translation Editor (MOTE) v2.06
SET NAMES 'utf8';
UPDATE `trans_words`SET `content_loc3`='"If you need robbers, head to the Old Town. It is in the northeast of Stormwind."' WHERE `word_id`=276845; -- locales_npc_text - Text2_1 : entry=900
UPDATE `trans_words`SET `content_loc3`='No better place to learn First Aid than under the watchful eye of Shaina Fuller at the Cathedral of Light. $B$BTo get there, just look for the yellow rooftops, or the towering spire of the Cathedral itself which you can see from almost anywhere in the city.' WHERE `word_id`=192143; -- locales_npc_text - Text1_0 : entry=923
UPDATE `trans_words`SET `content_loc3`='Well well!  You\'ve come to the right place to learn Mining, $Gboyo : girlie;!  Geofram Bouldertoe himself resides at the Deepmountain Mining Guild. Ye couldn\'t ask for a better instructor than him.' WHERE `word_id`=192678; -- locales_npc_text - Text1_0 : entry=2804
UPDATE `trans_words`SET `content_loc3`='I have so much to do... so much before the plague comes...' WHERE `word_id`=193002; -- locales_npc_text - Text1_1 : entry=3668
UPDATE `trans_words`SET `content_loc3`='"Many entered this sanctuary, but few left it."' WHERE `word_id`=278038; -- locales_npc_text - Text2_1 : entry=6911
UPDATE `trans_words`SET `content_loc3`='Darkmoon Cards? This is to the professor. And I deal with antiquities and artifacts.' WHERE `word_id`=194586; -- locales_npc_text - Text0_1 : entry=7389
UPDATE `trans_words`SET `content_loc3`='Darkmoon Faire Cards?  See the Professor here for those. Come see me if you are a dealer in hard to come by antiquities and artifacts.' WHERE `word_id`=194587; -- locales_npc_text - Text1_1 : entry=7389
UPDATE `trans_words`SET `content_loc3`='The Stormpike Guard is in need of your assistance in the fight against the Frostwolf Clan, $N. Speak to Brogun Stoneshield on the Warrior\'s Terrace and he will help you find your way to Alterac Valley.' WHERE `word_id`=194630; -- locales_npc_text - Text1_1 : entry=7496
UPDATE `trans_words`SET `content_loc3`='The Silverwing Sentinels can use all the help they can get in their fight against the Warsong Outriders. $N, go to Stormwind Keep and speak with Elfarran if you wish to assist them.' WHERE `word_id`=194638; -- locales_npc_text - Text1_0 : entry=7501
UPDATE `trans_words`SET `content_loc3`='There is one that I know of here in Thunder Bluff that can aid you in your journey to Alterac Valley. On the Hunter Rise look for Taim Ragetotem. May you find what you are looking for $N.' WHERE `word_id`=194644; -- locales_npc_text - Text1_0 : entry=7505
UPDATE `trans_words`SET `content_loc3`='If I hold my breath, what color would I turn?' WHERE `word_id`=279813; -- locales_npc_text - Text3_1 : entry=10734
UPDATE `trans_words`SET `content_loc3`='If a horse gets horseshoes, will I get draenei shoes?' WHERE `word_id`=279814; -- locales_npc_text - Text4_1 : entry=10734
UPDATE `trans_words`SET `content_loc3`='How do you drink and eat so much, and not get fat?' WHERE `word_id`=279816; -- locales_npc_text - Text6_1 : entry=10734
UPDATE `trans_words`SET `content_loc3`='Does a naaru turn off the Light when it wants to sleep?' WHERE `word_id`=279817; -- locales_npc_text - Text7_1 : entry=10734
UPDATE `trans_words`SET `content_loc3`='Missing US text' WHERE `word_id`=195146; -- locales_npc_text - Text3_0 : entry=13064
UPDATE `trans_words`SET `content_loc3`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text3_0 : entry=14536
UPDATE `trans_words`SET `content_loc3`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text5_0 : entry=14536
UPDATE `trans_words`SET `content_loc3`='"On the way here from Dun Algaz, I saw a gnoll hunting for hard-toothed in the middle of the lake. Have you ever seen a dog with a spear? That was a sight!"' WHERE `word_id`=279674; -- locales_npc_text - Text0_1 : entry=16528
UPDATE `trans_words`SET `content_loc3`='"On the way here from Dun Algaz, I saw a gnoll hunting for hard-toothed in the middle of the lake. Have you ever seen a dog with a spear? That was a sight!"' WHERE `word_id`=279675; -- locales_npc_text - Text1_0 : entry=16528
UPDATE `trans_words`SET `content_loc3`='Weve located the mark, commander. Ya-six and i have been seperated. Requesting backup.' WHERE `word_id`=196931; -- locales_npc_text - Text0_1 : entry=20551
UPDATE `trans_words`SET `content_loc3`='Weve located the mark, commander. Ya-six and i have been seperated. Requesting backup.' WHERE `word_id`=196932; -- locales_npc_text - Text1_0 : entry=20551
UPDATE `trans_words`SET `content_loc3`='Arxes! Send help! Im pinned down in the mines, I...Im not sure where iam exactly but i had the presence of mind to drop tracers on the gro8und behind me' WHERE `word_id`=196933; -- locales_npc_text - Text1_1 : entry=20551
UPDATE `trans_words`SET `content_loc3`='Copy that, Araxes. Backup is on the way. Hold your position. I repeat, Hold your Position' WHERE `word_id`=196936; -- locales_npc_text - Text0_1 : entry=20564
UPDATE `trans_words`SET `content_loc3`='Copy that, Araxes. Backup is on the way. Hold your position. I repeat, Hold your Position' WHERE `word_id`=196937; -- locales_npc_text - Text1_0 : entry=20564

SET NAMES 'latin1';
