-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE gossip_texts SET content_loc3='[PH] SD3 unbekannter Text' WHERE entry=-3000000; /* content: [PH] SD3 unknown text */
UPDATE gossip_texts SET content_loc3='Taruk schicken Sie mir, um zu sammeln, was Sie schulden.' WHERE entry=-3000101; /* content: Taruk send me to collect what you owe. */
UPDATE gossip_texts SET content_loc3='Zahltag, Harry!' WHERE entry=-3000102; /* content: Pay up, Harry! */
UPDATE gossip_texts SET content_loc3='Ich bin jetzt bereit, in dein Dorf zu reisen.' WHERE entry=-3000103; /* content: I am ready to travel to you village now. */
UPDATE gossip_texts SET content_loc3='<Auf Impuls prüfen ...>' WHERE entry=-3000104; /* content: <Check for pulse...> */
UPDATE gossip_texts SET content_loc3='Ezekiel sagte, Ihr hättet da ein bestimmtes Buch...' WHERE entry=-3000105; /* content: Ezekiel said that you might have a certain book... */
UPDATE gossip_texts SET content_loc3='Wohin würdet Ihr gerne fliegen?' WHERE entry=-3000106; /* content: Let Marshal Windsor know that I am ready. */
UPDATE gossip_texts SET content_loc3='Ich bin bereit, ebenso wie meine Streitkräfte. Lasst uns diese Maskerade beenden!' WHERE entry=-3000107; /* content: I am ready, as are my forces. Let us end this masquerade! */
UPDATE gossip_texts SET content_loc3='Habt Ihr einen Moment Zeit für mich, mein Herr?' WHERE entry=-3000108; /* content: I need a moment of your time, sir. */
UPDATE gossip_texts SET content_loc3='Ich bin bereit, Oronok. Lasst uns Cyrukh zerstören und die Elemente befreien!' WHERE entry=-3000109; /* content: I am ready, Oronok. Let us destroy Cyrukh and free the elements! */
UPDATE gossip_texts SET content_loc3='Warum ... ja, natürlich, ich habe dir etwas zu zeigen, Mr. Anvilward.' WHERE entry=-3000110; /* content: Why... yes, of course. I\'ve something to show you right inside this building, Mr. Anvilward. */
UPDATE gossip_texts SET content_loc3='Dreht den Schlüssel, um die Maschine zu starten.' WHERE entry=-3000111; /* content: Turn the key to start the machine. */
UPDATE gossip_texts SET content_loc3='Ich bin bereit - lass uns hier verschwinden.' WHERE entry=-3000112; /* content: I\'m ready - let\'s get out of here. */
UPDATE gossip_texts SET content_loc3='Mach weiter, du bist frei, verschwinde von hier!' WHERE entry=-3000113; /* content: Go on, you\'re free. Get out of here! */
UPDATE gossip_texts SET content_loc3='Ich bin bereit, mit der Destillation zu beginnen, uh, Schluckspecht.' WHERE entry=-3000114; /* content: I\'m ready to start the distillation, uh, Tipsy. */
UPDATE gossip_texts SET content_loc3='Ich bin bereit, Anachorit Lassen Sie uns den Exorzismus beginnen.' WHERE entry=-3006669; /* content: I am ready, Anchorite. Let us begin the exorcism. */
UPDATE gossip_texts SET content_loc3='Öffnet bitte die Tür zum Hof.' WHERE entry=-3033000; /* content: Please unlock the courtyard door. */
UPDATE gossip_texts SET content_loc3='Lasst das Ereignis beginnen!' WHERE entry=-3043000; /* content: Let the event begin! */
UPDATE gossip_texts SET content_loc3='Ich bin bereit anzufangen.' WHERE entry=-3090000; /* content: I am ready to begin. */
UPDATE gossip_texts SET content_loc3='Ihr seid frei, Dughal! Verschwindet!' WHERE entry=-3230000; /* content: You\'re free, Dughal! Get out of here! */
UPDATE gossip_texts SET content_loc3='Raus hier, Tobias, Ihr seid frei!' WHERE entry=-3230001; /* content: Get out of here, Tobias, you\'re free! */
UPDATE gossip_texts SET content_loc3='Deine Bondage ist zu Ende, Doom\'rel. Ich fordere dich heraus!' WHERE entry=-3230002; /* content: Your bondage is at an end, Doom\'rel. I challenge you! */
UPDATE gossip_texts SET content_loc3='Warum sucht Ihr und Rocknot Euch nicht ein ruhiges Plätzchen...' WHERE entry=-3230003; /* content: Why don\'t you and Rocknot go find somewhere private... */
UPDATE gossip_texts SET content_loc3='Erzählt mir mehr.' WHERE entry=-3409000; /* content: Tell me more. */
UPDATE gossip_texts SET content_loc3='Habt Ihr sonst noch etwas zu sagen?' WHERE entry=-3409001; /* content: What else do you have to say? */
UPDATE gossip_texts SET content_loc3='Du hast uns herausgefordert, und wir sind gekommen, wo sprichst du von diesem Meister?' WHERE entry=-3409002; /* content: You challenged us and we have come. Where is this master you speak of? */
UPDATE gossip_texts SET content_loc3='Ich habe keine Fehler begangen.' WHERE entry=-3469000; /* content: I\'ve made no mistakes. */
UPDATE gossip_texts SET content_loc3='Ihr habt den Verstand verloren, Nefarius. Ihr sprecht in Rätseln.' WHERE entry=-3469001; /* content: You have lost your mind, Nefarius. You speak in riddles. */
UPDATE gossip_texts SET content_loc3='Bitte gern.' WHERE entry=-3469002; /* content: Please do. */
UPDATE gossip_texts SET content_loc3='Ich kann nicht, Vaelastrasz! Mit Sicherheit kann etwas getan werden, um Euch zu heilen!' WHERE entry=-3469003; /* content: I cannot, Vaelastrasz! Surely something can be done to heal you! */
UPDATE gossip_texts SET content_loc3='Nein, Vaelastrasz, nicht!!!' WHERE entry=-3469004; /* content: Vaelastrasz, no!!! */
UPDATE gossip_texts SET content_loc3='Finden wir\'s raus.' WHERE entry=-3509000; /* content: Let\'s find out. */
UPDATE gossip_texts SET content_loc3='Schauen wir mal, was Ihr da habt.' WHERE entry=-3509001; /* content: Let\'s see what you have. */
UPDATE gossip_texts SET content_loc3='Teleportiere mich zur Bibliothek des Wächters' WHERE entry=-3532000; /* content: Teleport me to the Guardian\'s Library */
UPDATE gossip_texts SET content_loc3='Ich bin kein Schauspieler.' WHERE entry=-3532001; /* content: I\'m not an actor. */
UPDATE gossip_texts SET content_loc3='Ok, ich werde es versuchen.' WHERE entry=-3532002; /* content: Ok, I\'ll give it a try, then. */
UPDATE gossip_texts SET content_loc3='Ich war noch nie so bereit, wie jetzt!' WHERE entry=-3532003; /* content: I\'ve never been more ready. */
UPDATE gossip_texts SET content_loc3='Das ist das Ende vom Wolf.' WHERE entry=-3532004; /* content: The wolf\'s going down. */
UPDATE gossip_texts SET content_loc3='Was hast du für eine Großmutter?' WHERE entry=-3532005; /* content: What phat lewtz you have grandmother? */
UPDATE gossip_texts SET content_loc3='Orcgrunzer kontrollieren' WHERE entry=-3532006; /* content: Control Orc Grunt */
UPDATE gossip_texts SET content_loc3='Wolf der Orcs kontrollieren' WHERE entry=-3532007; /* content: Control Orc Wolf */
UPDATE gossip_texts SET content_loc3='Beschworenen Dämon kontrollieren' WHERE entry=-3532008; /* content: Control Summoned Daemon */
UPDATE gossip_texts SET content_loc3='Orchexenmeister kontrollieren' WHERE entry=-3532009; /* content: Control Orc Warlock */
UPDATE gossip_texts SET content_loc3='Orcnekrolyt kontrollieren' WHERE entry=-3532010; /* content: Control Orc Necrolyte */
UPDATE gossip_texts SET content_loc3='Kriegshäuptling Schwarzfaust kontrollieren' WHERE entry=-3532011; /* content: Control Warchief Blackhand */
UPDATE gossip_texts SET content_loc3='Menschenfußsoldat kontrollieren' WHERE entry=-3532012; /* content: Control Human Footman */
UPDATE gossip_texts SET content_loc3='Kontrollieren Sie das menschliche Ladegerät' WHERE entry=-3532013; /* content: Control Human Charger */
UPDATE gossip_texts SET content_loc3='Kontrollbeschworenes Wasserelementar' WHERE entry=-3532014; /* content: Control Conjured Water Elemental */
UPDATE gossip_texts SET content_loc3='Menschenbeschwörer kontrollieren' WHERE entry=-3532015; /* content: Control Human Conjurer */
UPDATE gossip_texts SET content_loc3='Menschenkleriker kontrollieren' WHERE entry=-3532016; /* content: Control Human Cleric */
UPDATE gossip_texts SET content_loc3='König Llane kontrollieren' WHERE entry=-3532017; /* content: Control King Llane */
UPDATE gossip_texts SET content_loc3='Bitte setzt das Schachbrett zurück, wir würden gerne erneut spielen.' WHERE entry=-3532018; /* content: Please reset the chess board, we would like to play again. */
UPDATE gossip_texts SET content_loc3='Meine Gefährten und ich werden Euch zur Seite stehen, Lady Prachtmeer.' WHERE entry=-3534000; /* content: My companions and I are with you, Lady Proudmoore. */
UPDATE gossip_texts SET content_loc3='Was auch immer Archimonde gegen uns ins Feld schicken mag, wir sind bereit, Lady Prachtmeer.' WHERE entry=-3534001; /* content: We are ready for whatever Archimonde might send our way, Lady Proudmoore. */
UPDATE gossip_texts SET content_loc3='Wir werden uns wiedersehen, Lady Prachtmeer.' WHERE entry=-3534002; /* content: Until we meet again, Lady Proudmoore. */
UPDATE gossip_texts SET content_loc3='Ich werde Euch zur Seite stehen, Thrall!' WHERE entry=-3534003; /* content: I am with you, Thrall. */
UPDATE gossip_texts SET content_loc3='Wir haben nichts zu befürchten.' WHERE entry=-3534004; /* content: We have nothing to fear. */
UPDATE gossip_texts SET content_loc3='Wir werden uns wiedersehen, Thrall.' WHERE entry=-3534005; /* content: Until we meet again, Thrall. */
UPDATE gossip_texts SET content_loc3='Ich wäre dankbar für jegliche Hilfe, die Ihr bieten könnt, Priesterin.' WHERE entry=-3534006; /* content: I would be grateful for any aid you can provide, Priestess. */
UPDATE gossip_texts SET content_loc3='Wir sind bereit, um Euch hier herauszuholen, Thrall.' WHERE entry=-3560000; /* content: We are ready to get you out of here, Thrall. Let\'s go! */
UPDATE gossip_texts SET content_loc3='Ich brauche ein Bündel Brandbomben.' WHERE entry=-3560001; /* content: I need a pack of Incendiary Bombs. */
UPDATE gossip_texts SET content_loc3='Taretha kann Euch nicht sehen, Thrall.' WHERE entry=-3560002; /* content: Taretha cannot see you, Thrall. */
UPDATE gossip_texts SET content_loc3='Die Situation ist recht kompliziert, Thrall. Es wäre das Beste für Euch, wenn Ihr nun in die Berge aufbrecht, bevor noch mehr von Schwarzmoors Männer hier auftauchen. Wir stellen sicher, dass Taretha in Sicherheit ist.' WHERE entry=-3560003; /* content: The situation is rather complicated, Thrall. It would be best for you to head into the mountains now, before more of Blackmoore\'s men show up. We\'ll make sure Taretha is safe. */
UPDATE gossip_texts SET content_loc3='Wir sind bereit, Thrall.' WHERE entry=-3560004; /* content: We\'re ready, Thrall. */
UPDATE gossip_texts SET content_loc3='Seltsamer Zauberer?' WHERE entry=-3560005; /* content: Strange wizard? */
UPDATE gossip_texts SET content_loc3='Wir bringen dich raus Taretha Mach dir keine Sorgen, ich bezweifle, dass der Zauberer zu weit weg wandern würde.' WHERE entry=-3560006; /* content: We\'ll get you out. Taretha. Don\'t worry. I doubt the wizard would wander too far away. */
UPDATE gossip_texts SET content_loc3='Tarrens Mühle.' WHERE entry=-3560007; /* content: Tarren Mill. */
UPDATE gossip_texts SET content_loc3='Ich bin bei Euch, Akama.' WHERE entry=-3564000; /* content: I\'m with you, Akama. */
UPDATE gossip_texts SET content_loc3='Ich bin bereit, Akama.' WHERE entry=-3564001; /* content: I\'m ready, Akama. */
UPDATE gossip_texts SET content_loc3='Wir sind bereit, Illidan zu konfrontieren.' WHERE entry=-3564002; /* content: We\'re ready to face Illidan. */
UPDATE gossip_texts SET content_loc3='Danke für den Ratschlag, aber wir haben vor, Zul\'Aman dennoch zu erforschen.' WHERE entry=-3568000; /* content: Thanks for the concern, but we intend to explore Zul\'Aman. */
UPDATE gossip_texts SET content_loc3='Was glaubt Ihr, was sie vorhaben?' WHERE entry=-3595000; /* content: What do you think they\'re up to? */
UPDATE gossip_texts SET content_loc3='Ihr wollt, dass ich was tue?' WHERE entry=-3595001; /* content: You want me to do what? */
UPDATE gossip_texts SET content_loc3='Sehr wohl, Chromie.' WHERE entry=-3595002; /* content: Very well, Chromie. */
UPDATE gossip_texts SET content_loc3='Warum wurde ich zu dieser speziellen Zeit und an diesen speziellen Ort zurückgeschickt?' WHERE entry=-3595003; /* content: Why have I been sent back to this particular place and time? */
UPDATE gossip_texts SET content_loc3='Was war die Entscheidung?' WHERE entry=-3595004; /* content: What was this decision? */
UPDATE gossip_texts SET content_loc3='Also, wie plant der ewige Drachenschwarm einzugreifen?' WHERE entry=-3595005; /* content: So how does the Infinite Dragonflight plan to interfere? */
UPDATE gossip_texts SET content_loc3='Chromie, Ihr und ich wissen beide, was in dieser Zeitlinie passieren wird. Wir haben das alles schon mal gesehen.$B$BKönntet Ihr uns ein wenig vorspringen lassen, dahin, wo wirklich was los ist?' WHERE entry=-3595006; /* content: Chromie, you and I both know what\'s going to happen in this time stream. We\'ve seen this all before.$B$BCan you just skip us ahead to all the real action? */
UPDATE gossip_texts SET content_loc3='Ja, bitte!' WHERE entry=-3595007; /* content: Yes, please! */
UPDATE gossip_texts SET content_loc3='Brann, es wäre uns eine Ehre!' WHERE entry=-3599000; /* content: Brann, it would be our honor! */
UPDATE gossip_texts SET content_loc3='Lass uns Brann bewegen, genug von der Geschichtsstunde!' WHERE entry=-3599001; /* content: Let\'s move Brann, enough of the history lessons! */
UPDATE gossip_texts SET content_loc3='Teleport zum Basislager der Expedition.' WHERE entry=-3603000; /* content: Teleport to the Expedition Base Camp. */
UPDATE gossip_texts SET content_loc3='Teleport zum Gestaltungsgelände.' WHERE entry=-3603001; /* content: Teleport to the Formation Grounds. */
UPDATE gossip_texts SET content_loc3='Teleport zur Kolossalen Schmiede.' WHERE entry=-3603002; /* content: Teleport to the Colossal Forge. */
UPDATE gossip_texts SET content_loc3='Teleport zum Schrottplatz.' WHERE entry=-3603003; /* content: Teleport to the Scrapyard. */
UPDATE gossip_texts SET content_loc3='Teleport zur Vorkammer von Ulduar.' WHERE entry=-3603004; /* content: Teleport to the Antechamber of Ulduar. */
UPDATE gossip_texts SET content_loc3='Teleport zum Zerschmetterten Gang.' WHERE entry=-3603005; /* content: Teleport to the Shattered Walkway. */
UPDATE gossip_texts SET content_loc3='Teleport zum Konservatorium des Lebens.' WHERE entry=-3603006; /* content: Teleport to the Conservatory of Life. */
UPDATE gossip_texts SET content_loc3='Teleport zum Funken der Imagination.' WHERE entry=-3603007; /* content: Teleport to the Spark of Imagination. */
UPDATE gossip_texts SET content_loc3='Teleport zum Gefängnis von Yogg-Saron.' WHERE entry=-3603008; /* content: Teleport to the Prison of Yogg-Saron. */
UPDATE gossip_texts SET content_loc3='Wir sind bereit zu helfen!' WHERE entry=-3603009; /* content: We are ready to help! */
UPDATE gossip_texts SET content_loc3='Sekundäre Verteidigungssysteme aktivieren.' WHERE entry=-3603010; /* content: Activate secondary defensive systems. */
UPDATE gossip_texts SET content_loc3='Bestätigt.' WHERE entry=-3603011; /* content: Confirmed. */
UPDATE gossip_texts SET content_loc3='Wir sind bereit. Lasst den Angriff beginnen!' WHERE entry=-3603012; /* content: We\'re ready. Begin the assault! */
UPDATE gossip_texts SET content_loc3='Bitte gewährt uns Eure Hilfe, Hüter. Gemeinsam werden wir Yogg-Saron vernichten.' WHERE entry=-3603013; /* content: Lend us your aid, keeper. Together we will defeat Yogg-Saron. */
UPDATE gossip_texts SET content_loc3='Ja.' WHERE entry=-3603014; /* content: Yes. */
UPDATE gossip_texts SET content_loc3='Aktivieren Sie die Kristalle, wenn wir in Schwierigkeiten geraten, oder?' WHERE entry=-3608000; /* content: Activate the crystals when we get in trouble, right? */
UPDATE gossip_texts SET content_loc3='Bringt Eure Leute in Sicherheit, wir werden die Streitkräfte des blauen Drachenschwarms in Schach halten.' WHERE entry=-3608001; /* content: Get your people to safety, we\'ll keep the Blue Dragonflight\'s forces at bay. */
UPDATE gossip_texts SET content_loc3='Ich kämpfe gerade nicht, also schickt mich jetzt hin!' WHERE entry=-3608002; /* content: I\'m not fighting, so send me in now! */
UPDATE gossip_texts SET content_loc3='Ich fordere Euch heraus, Todesritter!' WHERE entry=-3609000; /* content: I challenge you, death knight! */
UPDATE gossip_texts SET content_loc3='Ich bin bereit, Hochlord. Die Belagerung der Kapelle des Hoffnungsvollen Lichts kann beginnen!' WHERE entry=-3609001; /* content: I am ready, Highlord. Let the siege of Light\'s Hope begin! */
UPDATE gossip_texts SET content_loc3='Ja. Wir sind bereit für die Prüfungen, die vor uns liegen.' WHERE entry=-3649000; /* content: Yes. We are prepared for the challenges ahead of us. */
UPDATE gossip_texts SET content_loc3='Immer her mit der ersten Herausforderung!' WHERE entry=-3649001; /* content: Bring forth the first challenge! */
UPDATE gossip_texts SET content_loc3='Wir möchten einen weiteren Kampf gegen diese Bestien.' WHERE entry=-3649002; /* content: We want another shot at those beasts! */
UPDATE gossip_texts SET content_loc3='Welche neue Herausforderung erwartet uns?' WHERE entry=-3649003; /* content: What new challenge awaits us? */
UPDATE gossip_texts SET content_loc3='Wir sind bereit, uns erneut dem Zauberer zu stellen.' WHERE entry=-3649004; /* content: We\'re ready to fight the sorceror again. */
UPDATE gossip_texts SET content_loc3='Natürlich!' WHERE entry=-3649005; /* content: Of course! */
UPDATE gossip_texts SET content_loc3='Gebt das Signal! Wir sind bereit!' WHERE entry=-3649006; /* content: Give the signal! We\'re ready to go! */
UPDATE gossip_texts SET content_loc3='So stark, hm?' WHERE entry=-3649007; /* content: That tough, huh? */
UPDATE gossip_texts SET content_loc3='Val\'kyr, wir sind bereit für sie' WHERE entry=-3649008; /* content: Val\'kyr? We\'re ready for them */
UPDATE gossip_texts SET content_loc3='Wir wissen Eure Worte des Lobes zu schätzen, Zeremonienmeister des Kolosseums.' WHERE entry=-3649009; /* content: Your words of praise are appreciated, Coliseum Master. */
UPDATE gossip_texts SET content_loc3='Wie merkwürdig...' WHERE entry=-3649010; /* content: That is strange... */
UPDATE gossip_texts SET content_loc3='Ich bin bereit.' WHERE entry=-3650000; /* content: I am ready. */
UPDATE gossip_texts SET content_loc3='Ich bin so weit. Ich würde allerdings gerne auf den ganzen Prunk verzichten.' WHERE entry=-3650001; /* content: I am ready. However, I\'d like to skip the pageantry. */
UPDATE gossip_texts SET content_loc3='Ich bin bereit für die nächste Herausforderung.' WHERE entry=-3650002; /* content: I am ready for the next challenge. */

SET NAMES 'latin1';
