-- File generated by Mangos Online Translation Editor (MOTE) v2.06
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc8`='Level 80' WHERE `word_id`=333613; -- locales_achievement_reward - subject : entry=13
UPDATE `trans_words` SET `content_loc8`='Congratulations on your conviction to reach the 80th season of adventure. You are undoubtedly dedicated to the cause of ridding Azeroth of the evils which have plagued us.$B$BAnd while the journey thus far has been no minor feat, the true battle lies ahead.$B$BFight on!$B$BRhonin' WHERE `word_id`=333614; -- locales_achievement_reward - text : entry=13
UPDATE `trans_words` SET `content_loc8`='World Explorer' WHERE `word_id`=336876; -- locales_achievement_reward - subject : entry=46
UPDATE `trans_words` SET `content_loc8`='Battlemaster' WHERE `word_id`=336910; -- locales_achievement_reward - subject : entry=230
UPDATE `trans_words` SET `content_loc8`='Realm First! Obsidian Slayer' WHERE `word_id`=336908; -- locales_achievement_reward - subject : entry=456
UPDATE `trans_words` SET `content_loc8`='The Conqueror' WHERE `word_id`=336905; -- locales_achievement_reward - subject : entry=714
UPDATE `trans_words` SET `content_loc8`='Ambassador of the Horde' WHERE `word_id`=336882; -- locales_achievement_reward - subject : entry=762
UPDATE `trans_words` SET `content_loc8`='100000 Honorable Kills' WHERE `word_id`=336880; -- locales_achievement_reward - subject : entry=870
UPDATE `trans_words` SET `content_loc8`='The Justicar' WHERE `word_id`=336906; -- locales_achievement_reward - subject : entry=907
UPDATE `trans_words` SET `content_loc8`='To Honor One\'s Elders' WHERE `word_id`=336873; -- locales_achievement_reward - subject : entry=913
UPDATE `trans_words` SET `content_loc8`='The Argent Champion' WHERE `word_id`=336890; -- locales_achievement_reward - subject : entry=945
UPDATE `trans_words` SET `content_loc8`='Ambassador of the Alliance' WHERE `word_id`=336884; -- locales_achievement_reward - subject : entry=948
UPDATE `trans_words` SET `content_loc8`='Guardian of Cenarius' WHERE `word_id`=336891; -- locales_achievement_reward - subject : entry=953
UPDATE `trans_words` SET `content_loc8`='3000 Quests Completed' WHERE `word_id`=336878; -- locales_achievement_reward - subject : entry=978
UPDATE `trans_words` SET `content_loc8`='40 Exalted Reputations' WHERE `word_id`=336881; -- locales_achievement_reward - subject : entry=1015
UPDATE `trans_words` SET `content_loc8`='The Flame Warden' WHERE `word_id`=336877; -- locales_achievement_reward - subject : entry=1038
UPDATE `trans_words` SET `content_loc8`='The Flame Keeper' WHERE `word_id`=336879; -- locales_achievement_reward - subject : entry=1039
UPDATE `trans_words` SET `content_loc8`='The Arena Master' WHERE `word_id`=336898; -- locales_achievement_reward - subject : entry=1174
UPDATE `trans_words` SET `content_loc8`='Battlemaster' WHERE `word_id`=336910; -- locales_achievement_reward - subject : entry=1175
UPDATE `trans_words` SET `content_loc8`='Realm First! Magic Seeker' WHERE `word_id`=336907; -- locales_achievement_reward - subject : entry=1400
UPDATE `trans_words` SET `content_loc8`='Realm First! Conqueror of Naxxramas' WHERE `word_id`=336909; -- locales_achievement_reward - subject : entry=1402
UPDATE `trans_words` SET `content_loc8`='Accomplished Angler' WHERE `word_id`=336904; -- locales_achievement_reward - subject : entry=1516
UPDATE `trans_words` SET `content_loc8`='Hail to the Chef' WHERE `word_id`=336900; -- locales_achievement_reward - subject : entry=1563
UPDATE `trans_words` SET `content_loc8`='Hallowed Be Thy Name' WHERE `word_id`=336887; -- locales_achievement_reward - subject : entry=1656
UPDATE `trans_words` SET `content_loc8`='Hallowed Be Thy Name' WHERE `word_id`=336887; -- locales_achievement_reward - subject : entry=1657
UPDATE `trans_words` SET `content_loc8`='Champion of the Frozen Wastes' WHERE `word_id`=336892; -- locales_achievement_reward - subject : entry=1658
UPDATE `trans_words` SET `content_loc8`='Brewmaster' WHERE `word_id`=336885; -- locales_achievement_reward - subject : entry=1683
UPDATE `trans_words` SET `content_loc8`='Brewmaster' WHERE `word_id`=336885; -- locales_achievement_reward - subject : entry=1684
UPDATE `trans_words` SET `content_loc8`='Merrymaker' WHERE `word_id`=336893; -- locales_achievement_reward - subject : entry=1691
UPDATE `trans_words` SET `content_loc8`='Merrymaker' WHERE `word_id`=336893; -- locales_achievement_reward - subject : entry=1692
UPDATE `trans_words` SET `content_loc8`='Fool For Love' WHERE `word_id`=336875; -- locales_achievement_reward - subject : entry=1693
UPDATE `trans_words` SET `content_loc8`='Fool For Love' WHERE `word_id`=336875; -- locales_achievement_reward - subject : entry=1707
UPDATE `trans_words` SET `content_loc8`='Hail to the Chef' WHERE `word_id`=336900; -- locales_achievement_reward - subject : entry=1784
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:1793' WHERE `word_id`=333557; -- locales_achievement_reward - subject : entry=1793
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:1793' WHERE `word_id`=333557; -- locales_achievement_reward - subject : entry=1793
UPDATE `trans_words` SET `content_loc8`='The Twilight Zone (10 player)' WHERE `word_id`=336901; -- locales_achievement_reward - subject : entry=2051
UPDATE `trans_words` SET `content_loc8`='The Twilight Zone (25 player)' WHERE `word_id`=336902; -- locales_achievement_reward - subject : entry=2054
UPDATE `trans_words` SET `content_loc8`='Time and Time Again' WHERE `word_id`=333601; -- locales_achievement_reward - subject : entry=2144
UPDATE `trans_words` SET `content_loc8`='With the drums of war pounding in the distance, it is easy for the denizens of Azeroth to forget all that life has to offer.$B$BYou, on the other hand, have maintained the dignity of the good races of Azeroth with your ability to remember what we fight for. To not celebrate our victories is another form of defeat. Remember that well, reveler.$B$BMay others be inspired by your good cheer.$B$BAlexstrasza the Life-Binder' WHERE `word_id`=333602; -- locales_achievement_reward - text : entry=2144
UPDATE `trans_words` SET `content_loc8`='Time and Time Again' WHERE `word_id`=333601; -- locales_achievement_reward - subject : entry=2145
UPDATE `trans_words` SET `content_loc8`='With the drums of war pounding in the distance, it is easy for the denizens of Azeroth to forget all that life has to offer.$B$BYou, on the other hand, have maintained the dignity of the good races of Azeroth with your ability to remember what we fight for. To not celebrate our victories is another form of defeat. Remember that well, reveler.$B$BMay others be inspired by your good cheer.$B$BAlexstrasza the Life-Binder' WHERE `word_id`=333602; -- locales_achievement_reward - text : entry=2145
UPDATE `trans_words` SET `content_loc8`='The Immortal' WHERE `word_id`=336896; -- locales_achievement_reward - subject : entry=2186
UPDATE `trans_words` SET `content_loc8`='The Undying' WHERE `word_id`=336897; -- locales_achievement_reward - subject : entry=2187
UPDATE `trans_words` SET `content_loc8`='Leeeeeeeeeeeeeroy!' WHERE `word_id`=336899; -- locales_achievement_reward - subject : entry=2188
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:2336' WHERE `word_id`=333571; -- locales_achievement_reward - subject : entry=2336
UPDATE `trans_words` SET `content_loc8`='Mountain o\' Mounts' WHERE `word_id`=333597; -- locales_achievement_reward - subject : entry=2536
UPDATE `trans_words` SET `content_loc8`='I\'ve heard your stables are nearly as extensive as mine, now. Impressive! Perhaps we can help one another... I\'ve one too many dragonhawks, and hoped you could give this one a home. Naturally its been trained as a mount and not a hunting pet, and you\'ll find it as loyal and tireless as any other steed I raise.$B$BYours again,$B$BMei' WHERE `word_id`=333598; -- locales_achievement_reward - text : entry=2536
UPDATE `trans_words` SET `content_loc8`='Mountain o\' Mounts' WHERE `word_id`=333597; -- locales_achievement_reward - subject : entry=2537
UPDATE `trans_words` SET `content_loc8`='I\'ve heard your stables are nearly as extensive as mine, now. Impressive! Perhaps we can help one another... I\'ve one too many dragonhawks, and hoped you could give this one a home. Naturally its been trained as a mount and not a hunting pet, and you\'ll find it as loyal and tireless as any other steed I raise.$B$BYours again,$B$BMei' WHERE `word_id`=333598; -- locales_achievement_reward - text : entry=2537
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:2760' WHERE `word_id`=333573; -- locales_achievement_reward - subject : entry=2760
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:2761' WHERE `word_id`=333572; -- locales_achievement_reward - subject : entry=2761
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:2762' WHERE `word_id`=333576; -- locales_achievement_reward - subject : entry=2762
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:2763' WHERE `word_id`=333574; -- locales_achievement_reward - subject : entry=2763
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:2764' WHERE `word_id`=333575; -- locales_achievement_reward - subject : entry=2764
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:2765' WHERE `word_id`=333577; -- locales_achievement_reward - subject : entry=2765
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:2766' WHERE `word_id`=333578; -- locales_achievement_reward - subject : entry=2766
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:2767' WHERE `word_id`=333579; -- locales_achievement_reward - subject : entry=2767
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:2768' WHERE `word_id`=333580; -- locales_achievement_reward - subject : entry=2768
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:2769' WHERE `word_id`=333581; -- locales_achievement_reward - subject : entry=2769
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:2797' WHERE `word_id`=333584; -- locales_achievement_reward - subject : entry=2797
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:2798' WHERE `word_id`=333585; -- locales_achievement_reward - subject : entry=2798
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:2816' WHERE `word_id`=333582; -- locales_achievement_reward - subject : entry=2816
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:2817' WHERE `word_id`=333583; -- locales_achievement_reward - subject : entry=2817
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:2903' WHERE `word_id`=333589; -- locales_achievement_reward - subject : entry=2903
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:2904' WHERE `word_id`=333588; -- locales_achievement_reward - subject : entry=2904
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:3036' WHERE `word_id`=333590; -- locales_achievement_reward - subject : entry=3036
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:3037' WHERE `word_id`=333591; -- locales_achievement_reward - subject : entry=3037
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:3117' WHERE `word_id`=333586; -- locales_achievement_reward - subject : entry=3117
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:3259' WHERE `word_id`=333587; -- locales_achievement_reward - subject : entry=3259
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:3316' WHERE `word_id`=333592; -- locales_achievement_reward - subject : entry=3316
UPDATE `trans_words` SET `content_loc8`='Master of Isle of Conquest' WHERE `word_id`=333621; -- locales_achievement_reward - subject : entry=3957
UPDATE `trans_words` SET `content_loc8`='Honorable $N,$B$BFor your deeds upon the Isle of Conquest,$B$Bit is my honor to present you with this$B$Btabard. Wear it proudly.$B$BOverlord Agmar' WHERE `word_id`=333622; -- locales_achievement_reward - text : entry=3957
UPDATE `trans_words` SET `content_loc8`='Master of Isle of Conquest' WHERE `word_id`=333621; -- locales_achievement_reward - subject : entry=3957
UPDATE `trans_words` SET `content_loc8`='Honorable $N,$B$BFor your deeds upon the Isle of Conquest,$B$Bit is my honor to present you with this$B$Btabard. Wear it proudly.$B$BOverlord Agmar' WHERE `word_id`=333622; -- locales_achievement_reward - text : entry=3957
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:4078' WHERE `word_id`=333595; -- locales_achievement_reward - subject : entry=4078
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:4080' WHERE `word_id`=333596; -- locales_achievement_reward - subject : entry=4080
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:4477' WHERE `word_id`=333607; -- locales_achievement_reward - subject : entry=4477
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:4530' WHERE `word_id`=333604; -- locales_achievement_reward - subject : entry=4530
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:4583' WHERE `word_id`=333612; -- locales_achievement_reward - subject : entry=4583
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:4584' WHERE `word_id`=333603; -- locales_achievement_reward - subject : entry=4584
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:4597' WHERE `word_id`=333605; -- locales_achievement_reward - subject : entry=4597
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:4598' WHERE `word_id`=333606; -- locales_achievement_reward - subject : entry=4598
UPDATE `trans_words` SET `content_loc8`='Emblem Quartermasters in Dalaran\'s Silver Enclave' WHERE `word_id`=333617; -- locales_achievement_reward - subject : entry=4784
UPDATE `trans_words` SET `content_loc8`='Your achievements in Northrend have not gone unnoticed, friend.$B$BThe Emblems you have earned may be used to$B$Bpurchase equipment from the various Emblem Quartermasters in Dalaran.$B$BYou may find us there, in the Sunreaver Sanctuary, where each variety of Emblem has its own quartermaster.$B$BWe look forward to your arrival!' WHERE `word_id`=333616; -- locales_achievement_reward - text : entry=4784
UPDATE `trans_words` SET `content_loc8`='Emblem Quartermasters in Dalaran\'s Sunreaver Sanctuary' WHERE `word_id`=333615; -- locales_achievement_reward - subject : entry=4785
UPDATE `trans_words` SET `content_loc8`='Your achievements in Northrend have not gone unnoticed, friend.$B$BThe Emblems you have earned may be used to$B$Bpurchase equipment from the various Emblem Quartermasters in Dalaran.$B$BYou may find us there, in the Sunreaver Sanctuary, where each variety of Emblem has its own quartermaster.$B$BWe look forward to your arrival!' WHERE `word_id`=333616; -- locales_achievement_reward - text : entry=4785

SET NAMES 'latin1';
