-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc8`='[PH] Get E.C.A.C.' WHERE `word_id`=128451; -- locales_gossip_menu_option - option_text : menu_id=20011-id=0
UPDATE `trans_words` SET `content_loc8`='[PH] Get Thieves\' Tools' WHERE `word_id`=128154; -- locales_gossip_menu_option - option_text : menu_id=20011-id=1
UPDATE `trans_words` SET `content_loc8`='[PH] I want to deliver prisoner.' WHERE `word_id`=129166; -- locales_gossip_menu_option - option_text : menu_id=20002-id=0
UPDATE `trans_words` SET `content_loc8`='[PH] Learn Dimensional Ripper.' WHERE `word_id`=128975; -- locales_gossip_menu_option - option_text : menu_id=20003-id=0
UPDATE `trans_words` SET `content_loc8`='[PH] Learn Ultrasafe Transporter.' WHERE `word_id`=128976; -- locales_gossip_menu_option - option_text : menu_id=20004-id=0
UPDATE `trans_words` SET `content_loc8`='[ph]Learn recipe...' WHERE `word_id`=128221; -- locales_gossip_menu_option - option_text : menu_id=6443-id=0
UPDATE `trans_words` SET `content_loc8`='Can you tell me about this shard?' WHERE `word_id`=127827; -- locales_gossip_menu_option - option_text : menu_id=21-id=1
UPDATE `trans_words` SET `content_loc8`='Do you know where I can find Half Pendant of Aquatic Agility?' WHERE `word_id`=127921; -- locales_gossip_menu_option - option_text : menu_id=4041-id=1
UPDATE `trans_words` SET `content_loc8`='Do you know where I can find Half Pendant of Aquatic Endurance?' WHERE `word_id`=128016; -- locales_gossip_menu_option - option_text : menu_id=4042-id=1
UPDATE `trans_words` SET `content_loc8`='Emblem Gear' WHERE `word_id`=128942; -- locales_gossip_menu_option - option_text : menu_id=10173-id=2
UPDATE `trans_words` SET `content_loc8`='Guide me to the Broken Ring Graveyard.' WHERE `word_id`=128935; -- locales_gossip_menu_option - option_text : menu_id=10128-id=2
UPDATE `trans_words` SET `content_loc8`='Hearthglen? But...' WHERE `word_id`=127883; -- locales_gossip_menu_option - option_text : menu_id=2904-id=0
UPDATE `trans_words` SET `content_loc8`='I am ready! Let\'s finish Dimensius!' WHERE `word_id`=129039; -- locales_gossip_menu_option - option_text : menu_id=8228-id=1
UPDATE `trans_words` SET `content_loc8`='I have a book that might interest you. Would you like to take a look?' WHERE `word_id`=129145; -- locales_gossip_menu_option - option_text : menu_id=10212-id=0
UPDATE `trans_words` SET `content_loc8`='I have pald your price, Gloom\'rel. Now teach me your secrets!' WHERE `word_id`=128541; -- locales_gossip_menu_option - option_text : menu_id=1945-id=1
UPDATE `trans_words` SET `content_loc8`='I know this is rather silly but a young ward who is a bit shy would like your hoofprint.' WHERE `word_id`=127943; -- locales_gossip_menu_option - option_text : menu_id=5851-id=0
UPDATE `trans_words` SET `content_loc8`='I need to find Dajik, do you have his worn chalk?' WHERE `word_id`=128851; -- locales_gossip_menu_option - option_text : menu_id=9741-id=3
UPDATE `trans_words` SET `content_loc8`='I need to fly to the Windrunner. Official Business!' WHERE `word_id`=129081; -- locales_gossip_menu_option - option_text : menu_id=8894-id=0
UPDATE `trans_words` SET `content_loc8`='Is there anything you would have of me?' WHERE `word_id`=128367; -- locales_gossip_menu_option - option_text : menu_id=20007-id=1
UPDATE `trans_words` SET `content_loc8`='Learn about Dual Talent Specialization.' WHERE `word_id`=128981; -- locales_gossip_menu_option - option_text : menu_id=1403-id=3
UPDATE `trans_words` SET `content_loc8`='Ner\'zhul' WHERE `word_id`=128151; -- locales_gossip_menu_option - option_text : menu_id=4764-id=2
UPDATE `trans_words` SET `content_loc8`='Perhaps I can be of some assistance. I will make a deal with you, Satyr. I shall recover this unforged breastplate and slay the beast. In exchange for this task, you will teach me how to create the breastplate.' WHERE `word_id`=128373; -- locales_gossip_menu_option - option_text : menu_id=20019-id=0
UPDATE `trans_words` SET `content_loc8`='Take Blood Knight Insignia' WHERE `word_id`=129002; -- locales_gossip_menu_option - option_text : menu_id=7486-id=0
UPDATE `trans_words` SET `content_loc8`='Thank you! I will be sure to notify you if I find anything else.' WHERE `word_id`=129146; -- locales_gossip_menu_option - option_text : menu_id=10213-id=0
UPDATE `trans_words` SET `content_loc8`='This Dimensional Imploder sounds dangerous! How can I make one?' WHERE `word_id`=128186; -- locales_gossip_menu_option - option_text : menu_id=6092-id=0
UPDATE `trans_words` SET `content_loc8`='Transcript the Tablet' WHERE `word_id`=128093; -- locales_gossip_menu_option - option_text : menu_id=2187-id=0
UPDATE `trans_words` SET `content_loc8`='What Guardian? I don	 understand any of this.' WHERE `word_id`=128488; -- locales_gossip_menu_option - option_text : menu_id=86-id=0
UPDATE `trans_words` SET `content_loc8`='Yes elder. Tell me more of the book.' WHERE `word_id`=128719; -- locales_gossip_menu_option - option_text : menu_id=8617-id=0
UPDATE `trans_words` SET `content_loc8`='Yes... yes, it\'s me.' WHERE `word_id`=128718; -- locales_gossip_menu_option - option_text : menu_id=8616-id=0
UPDATE `trans_words` SET `content_loc8`='You gave the crew disguises?' WHERE `word_id`=128740; -- locales_gossip_menu_option - option_text : menu_id=8775-id=0

SET NAMES 'latin1';
