-- File generated by Mangos Online Translation Editor (MOTE) v2.06
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc8`='Stormwind Seasoning Salts' WHERE `word_id`=24177; -- locales_item - name : entry=2693
UPDATE `trans_words` SET `content_loc8`='Monster - Item, Lantern - Round' WHERE `word_id`=10049; -- locales_item - name : entry=2715
UPDATE `trans_words` SET `content_loc8`='Sacred Relic' WHERE `word_id`=24186; -- locales_item - name : entry=2920
UPDATE `trans_words` SET `content_loc8`='Blessed Relic' WHERE `word_id`=24187; -- locales_item - name : entry=2921
UPDATE `trans_words` SET `content_loc8`='Spirit Relic' WHERE `word_id`=24188; -- locales_item - name : entry=2922
UPDATE `trans_words` SET `content_loc8`='Relic of the Eye' WHERE `word_id`=24193; -- locales_item - name : entry=3003
UPDATE `trans_words` SET `content_loc8`='Relic of the Dead' WHERE `word_id`=24194; -- locales_item - name : entry=3004
UPDATE `trans_words` SET `content_loc8`='Relic of Truth' WHERE `word_id`=24195; -- locales_item - name : entry=3005
UPDATE `trans_words` SET `content_loc8`='Deprecated Silver-thread Cowl' WHERE `word_id`=24198; -- locales_item - name : entry=3068
UPDATE `trans_words` SET `content_loc8`='Librarian\'s Satchel' WHERE `word_id`=24223; -- locales_item - name : entry=3762
UPDATE `trans_words` SET `content_loc8`='Deprecated Feathered Helm' WHERE `word_id`=24225; -- locales_item - name : entry=4193
UPDATE `trans_words` SET `content_loc8`='Teaches Ritual of Doom.' WHERE `word_id`=11219; -- locales_item - description : entry=4213
UPDATE `trans_words` SET `content_loc8`='Throwing Tomahawk' WHERE `word_id`=24227; -- locales_item - name : entry=4959
UPDATE `trans_words` SET `content_loc8`='Agmond\'s Belt Pouch' WHERE `word_id`=24228; -- locales_item - name : entry=4981
UPDATE `trans_words` SET `content_loc8`='Manual: The Path of Defense' WHERE `word_id`=24297; -- locales_item - name : entry=6619
UPDATE `trans_words` SET `content_loc8`='Large Moneybag' WHERE `word_id`=24298; -- locales_item - name : entry=6754
UPDATE `trans_words` SET `content_loc8`='Obsidian Golem Shard' WHERE `word_id`=24306; -- locales_item - name : entry=7681
UPDATE `trans_words` SET `content_loc8`='Archaedic Shard' WHERE `word_id`=24322; -- locales_item - name : entry=9417
UPDATE `trans_words` SET `content_loc8`='Used Monster Sample' WHERE `word_id`=24323; -- locales_item - name : entry=9443
UPDATE `trans_words` SET `content_loc8`='Glyphic Rune' WHERE `word_id`=14757; -- locales_item - name : entry=9572
UPDATE `trans_words` SET `content_loc8`='Monster - Item, Sparkler Blue' WHERE `word_id`=24324; -- locales_item - name : entry=9700
UPDATE `trans_words` SET `content_loc8`='Monster - Item, Sparkler Red' WHERE `word_id`=24325; -- locales_item - name : entry=9701
UPDATE `trans_words` SET `content_loc8`='Elven Protector' WHERE `word_id`=24326; -- locales_item - name : entry=9888
UPDATE `trans_words` SET `content_loc8`='Dragonstalker Tunic' WHERE `word_id`=24377; -- locales_item - name : entry=13092
UPDATE `trans_words` SET `content_loc8`='Monster - Item, Glass - Purple Wine' WHERE `word_id`=24400; -- locales_item - name : entry=13612
UPDATE `trans_words` SET `content_loc8`='Dreadmaster\'s Shroud' WHERE `word_id`=24407; -- locales_item - name : entry=13936
UPDATE `trans_words` SET `content_loc8`='Sergeant Major\'s Cape' WHERE `word_id`=24426; -- locales_item - name : entry=16315
UPDATE `trans_words` SET `content_loc8`='Sergeant\'s Insignia' WHERE `word_id`=24427; -- locales_item - name : entry=16334
UPDATE `trans_words` SET `content_loc8`='Sergeant Major\'s Cape' WHERE `word_id`=24426; -- locales_item - name : entry=16336
UPDATE `trans_words` SET `content_loc8`='Sergeant Major\'s Cape' WHERE `word_id`=24426; -- locales_item - name : entry=16337
UPDATE `trans_words` SET `content_loc8`='First Sergeant\'s Cloak' WHERE `word_id`=24428; -- locales_item - name : entry=16340
UPDATE `trans_words` SET `content_loc8`='Ring of Critical Testing 2' WHERE `word_id`=21161; -- locales_item - name : entry=18970
UPDATE `trans_words` SET `content_loc8`='Alex\'s Test Beatdown Staff' WHERE `word_id`=21820; -- locales_item - name : entry=19879
UPDATE `trans_words` SET `content_loc8`='Glaive of the Defender' WHERE `word_id`=23918; -- locales_item - name : entry=23051
UPDATE `trans_words` SET `content_loc8`='QR 9867 Hunter Gloves' WHERE `word_id`=27459; -- locales_item - name : entry=25581
UPDATE `trans_words` SET `content_loc8`='68 TEST Green Cloth Belt' WHERE `word_id`=27939; -- locales_item - name : entry=26128
UPDATE `trans_words` SET `content_loc8`='68 TEST Green Cloth Boot' WHERE `word_id`=27940; -- locales_item - name : entry=26129
UPDATE `trans_words` SET `content_loc8`='68 TEST Green Cloth Chest' WHERE `word_id`=27941; -- locales_item - name : entry=26130
UPDATE `trans_words` SET `content_loc8`='68 TEST Green Cloth Hand' WHERE `word_id`=27942; -- locales_item - name : entry=26131
UPDATE `trans_words` SET `content_loc8`='68 TEST Green Cloth Head' WHERE `word_id`=27943; -- locales_item - name : entry=26132
UPDATE `trans_words` SET `content_loc8`='68 TEST Green Cloth Legs' WHERE `word_id`=27944; -- locales_item - name : entry=26133
UPDATE `trans_words` SET `content_loc8`='68 TEST Green Cloth Shoulder' WHERE `word_id`=27945; -- locales_item - name : entry=26134
UPDATE `trans_words` SET `content_loc8`='68 TEST Green Cloth Wrist' WHERE `word_id`=27946; -- locales_item - name : entry=26135
UPDATE `trans_words` SET `content_loc8`='68 TEST Green Cloth Cloak' WHERE `word_id`=27947; -- locales_item - name : entry=26513
UPDATE `trans_words` SET `content_loc8`='68 TEST Green Cloth Ring' WHERE `word_id`=27948; -- locales_item - name : entry=26527
UPDATE `trans_words` SET `content_loc8`='68 TEST Green Cloth Necklace' WHERE `word_id`=27949; -- locales_item - name : entry=26541
UPDATE `trans_words` SET `content_loc8`='68 TEST Green Off Hand' WHERE `word_id`=27950; -- locales_item - name : entry=26569
UPDATE `trans_words` SET `content_loc8`='68 TEST Green Wand' WHERE `word_id`=27951; -- locales_item - name : entry=26765
UPDATE `trans_words` SET `content_loc8`='68 TEST Green Spell Dagger' WHERE `word_id`=27952; -- locales_item - name : entry=26779
UPDATE `trans_words` SET `content_loc8`='Required by jewelcrafters to transmute mercurial adamantite.' WHERE `word_id`=31170; -- locales_item - description : entry=31080
UPDATE `trans_words` SET `content_loc8`='Monster - Work Wrench' WHERE `word_id`=31879; -- locales_item - name : entry=31824
UPDATE `trans_words` SET `content_loc8`='Teaches you how to permanently enchant a cloak to increase defense rating by 12. Requires a level 35 or higher item.' WHERE `word_id`=34918; -- locales_item - description : entry=35756
UPDATE `trans_words` SET `content_loc8`='Currency Token Test Token 1' WHERE `word_id`=47408; -- locales_item - name : entry=37711
UPDATE `trans_words` SET `content_loc8`='A test token for the Currency Token system' WHERE `word_id`=47409; -- locales_item - description : entry=37711
UPDATE `trans_words` SET `content_loc8`='Currency Token Test Token 2' WHERE `word_id`=47410; -- locales_item - name : entry=37742
UPDATE `trans_words` SET `content_loc8`='A second test token for the Currency Token system' WHERE `word_id`=47411; -- locales_item - description : entry=37742
UPDATE `trans_words` SET `content_loc8`='Currency Token Test Token 3' WHERE `word_id`=47413; -- locales_item - name : entry=38644
UPDATE `trans_words` SET `content_loc8`='A third test token for the Currency Token system' WHERE `word_id`=47414; -- locales_item - description : entry=38644
UPDATE `trans_words` SET `content_loc8`='Teaches you how to cook a Gigantic Feast.' WHERE `word_id`=41884; -- locales_item - description : entry=43505
UPDATE `trans_words` SET `content_loc8`='Teaches you how to cook a Small Feast' WHERE `word_id`=41886; -- locales_item - description : entry=43506
UPDATE `trans_words` SET `content_loc8`='zzzOLDDaily Quest Faction Token' WHERE `word_id`=47417; -- locales_item - name : entry=43949
UPDATE `trans_words` SET `content_loc8`='[PH] Bridle of the Argent Charger' WHERE `word_id`=44562; -- locales_item - name : entry=45568

SET NAMES 'latin1';
