-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc8`='A Tribute to Immortality' WHERE `word_id` = 333627; -- locales_achievement_reward - subject : entry=4079
UPDATE `trans_words` SET `content_loc8`='Achievement_Reward text Missing:1793' WHERE `word_id` = 333557; -- locales_achievement_reward - subject : entry=1793
UPDATE `trans_words` SET `content_loc8`='Brutally Dedicated' WHERE `word_id` = 333619; -- locales_achievement_reward - subject : entry=876
UPDATE `trans_words` SET `content_loc8`='Congratulations on your conviction to reach the 80th season of adventure. You are undoubtedly dedicated to the cause of ridding Azeroth of the evils which have plagued us.$B$BAnd while the journey thus far has been no minor feat, the true battle lies ahead.$B$BFight on!$B$BRhonin' WHERE `word_id` = 333614; -- locales_achievement_reward - text : entry=13
UPDATE `trans_words` SET `content_loc8`='Emblem Quartermasters in Dalaran\'s Silver Enclave' WHERE `word_id` = 333617; -- locales_achievement_reward - subject : entry=4784
UPDATE `trans_words` SET `content_loc8`='Emblem Quartermasters in Dalaran\'s Sunreaver Sanctuary' WHERE `word_id` = 333615; -- locales_achievement_reward - subject : entry=4785
UPDATE `trans_words` SET `content_loc8`='Glory of the Hero' WHERE `word_id` = 333564; -- locales_achievement_reward - subject : entry=2136
UPDATE `trans_words` SET `content_loc8`='Greetings from Darnassus' WHERE `word_id` = 333546; -- locales_achievement_reward - subject : entry=1681
UPDATE `trans_words` SET `content_loc8`='Hallowed Be Thy Name' WHERE `word_id` = 336887; -- locales_achievement_reward - subject : entry=1656
UPDATE `trans_words` SET `content_loc8`='Higher Learning' WHERE `word_id` = 333558; -- locales_achievement_reward - subject : entry=1956
UPDATE `trans_words` SET `content_loc8`='Honorable $N,$B$BFor your deeds upon the Isle of Conquest,$B$Bit is my honor to present you with this$B$Btabard. Wear it proudly.$B$BOverlord Agmar' WHERE `word_id` = 333622; -- locales_achievement_reward - text : entry=3957
UPDATE `trans_words` SET `content_loc8`='I\'ve heard your stables are nearly as extensive as mine, now. Impressive! Perhaps we can help one another... I\'ve one too many dragonhawks, and hoped you could give this one a home. Naturally its been trained as a mount and not a hunting pet, and you\'ll find it as loyal and tireless as any other steed I raise.$B$BYours again,$B$BMei' WHERE `word_id` = 333598; -- locales_achievement_reward - text : entry=2536
UPDATE `trans_words` SET `content_loc8`='Leading the Cavalry' WHERE `word_id` = 333566; -- locales_achievement_reward - subject : entry=2143
UPDATE `trans_words` SET `content_loc8`='P.U.G.' WHERE `word_id` = 333624; -- locales_achievement_reward - subject : entry=4478
UPDATE `trans_words` SET `content_loc8`='Quite the Achiever' WHERE `word_id` = 333531; -- locales_achievement_reward - subject : entry=1021
UPDATE `trans_words` SET `content_loc8`='The Coin Master' WHERE `word_id` = 333562; -- locales_achievement_reward - subject : entry=2096
UPDATE `trans_words` SET `content_loc8`='The Loremaster' WHERE `word_id` = 336895; -- locales_achievement_reward - subject : entry=1682
UPDATE `trans_words` SET `content_loc8`='With the drums of war pounding in the distance, it is easy for the denizens of Azeroth to forget all that life has to offer.$B$BYou, on the other hand, have maintained the dignity of the good races of Azeroth with your ability to remember what we fight for. To not celebrate our victories is another form of defeat. Remember that well, reveler.$B$BMay others be inspired by your good cheer.$B$BAlexstrasza the Life-Binder' WHERE `word_id` = 333602; -- locales_achievement_reward - text : entry=2144
UPDATE `trans_words` SET `content_loc8`='Your achievements in Northrend have not gone unnoticed, friend.$B$BThe Emblems you have earned may be used to$B$Bpurchase equipment from the various Emblem Quartermasters in Dalaran.$B$BYou may find us there, in the Sunreaver Sanctuary, where each variety of Emblem has its own quartermaster.$B$BWe look forward to your arrival!' WHERE `word_id` = 333616; -- locales_achievement_reward - text : entry=4784

SET NAMES 'latin1';
