-- File generated by MOTE (Mangos Online Translation Editor) v0.01
SET NAMES 'utf8';
UPDATE gossip_texts SET content_loc8='[PH] SD2 unknown text' WHERE entry=-3000000; /* content: [PH] SD2 unknown text */
UPDATE gossip_texts SET content_loc8='Taruk send me to collect what you owe.' WHERE entry=-3000101; /* content: Taruk send me to collect what you owe. */
UPDATE gossip_texts SET content_loc8='Pay up, Harry!' WHERE entry=-3000102; /* content: Pay up, Harry! */
UPDATE gossip_texts SET content_loc8='I am ready to travel to you village now.' WHERE entry=-3000103; /* content: I am ready to travel to you village now. */
UPDATE gossip_texts SET content_loc8='<Check for pulse...>' WHERE entry=-3000104; /* content: <Check for pulse...> */
UPDATE gossip_texts SET content_loc8='Ezekiel said that you might have a certain book...' WHERE entry=-3000105; /* content: Ezekiel said that you might have a certain book... */
UPDATE gossip_texts SET content_loc8='Let Marshal Windsor know that I am ready.' WHERE entry=-3000106; /* content: Let Marshal Windsor know that I am ready. */
UPDATE gossip_texts SET content_loc8='I am ready, as are my forces. Let us end this masquerade!' WHERE entry=-3000107; /* content: I am ready, as are my forces. Let us end this masquerade! */
UPDATE gossip_texts SET content_loc8='I need a moment of your time, sir.' WHERE entry=-3000108; /* content: I need a moment of your time, sir. */
UPDATE gossip_texts SET content_loc8='I am ready, Oronok. Let us destroy Cyrukh and free the elements!' WHERE entry=-3000109; /* content: I am ready, Oronok. Let us destroy Cyrukh and free the elements! */
UPDATE gossip_texts SET content_loc8='Why... yes, of course. I\'ve something to show you right inside this building, Mr. Anvilward.' WHERE entry=-3000110; /* content: Why... yes, of course. I\'ve something to show you right inside this building, Mr. Anvilward. */
UPDATE gossip_texts SET content_loc8='Turn the key to start the machine.' WHERE entry=-3000111; /* content: Turn the key to start the machine. */
UPDATE gossip_texts SET content_loc8='I\'m ready - let\'s get out of here.' WHERE entry=-3000112; /* content: I\'m ready - let\'s get out of here. */
UPDATE gossip_texts SET content_loc8='Go on, you\'re free. Get out of here!' WHERE entry=-3000113; /* content: Go on, you\'re free. Get out of here! */
UPDATE gossip_texts SET content_loc8='I\'m ready to start the distillation, uh, Tipsy.' WHERE entry=-3000114; /* content: I\'m ready to start the distillation, uh, Tipsy. */
UPDATE gossip_texts SET content_loc8='I am ready, Anchorite. Let us begin the exorcism.' WHERE entry=-3006669; /* content: I am ready, Anchorite. Let us begin the exorcism. */
UPDATE gossip_texts SET content_loc8='Please unlock the courtyard door.' WHERE entry=-3033000; /* content: Please unlock the courtyard door. */
UPDATE gossip_texts SET content_loc8='Let the event begin!' WHERE entry=-3043000; /* content: Let the event begin! */
UPDATE gossip_texts SET content_loc8='I am ready to begin.' WHERE entry=-3090000; /* content: I am ready to begin. */
UPDATE gossip_texts SET content_loc8='You\'re free, Dughal! Get out of here!' WHERE entry=-3230000; /* content: You\'re free, Dughal! Get out of here! */
UPDATE gossip_texts SET content_loc8='Get out of here, Tobias, you\'re free!' WHERE entry=-3230001; /* content: Get out of here, Tobias, you\'re free! */
UPDATE gossip_texts SET content_loc8='Your bondage is at an end, Doom\'rel. I challenge you!' WHERE entry=-3230002; /* content: Your bondage is at an end, Doom\'rel. I challenge you! */
UPDATE gossip_texts SET content_loc8='Why don\'t you and Rocknot go find somewhere private...' WHERE entry=-3230003; /* content: Why don\'t you and Rocknot go find somewhere private... */
UPDATE gossip_texts SET content_loc8='What else do you have to say?' WHERE entry=-3409001; /* content: What else do you have to say? */
UPDATE gossip_texts SET content_loc8='You challenged us and we have come. Where is this master you speak of?' WHERE entry=-3409002; /* content: You challenged us and we have come. Where is this master you speak of? */
UPDATE gossip_texts SET content_loc8='I\'ve made no mistakes.' WHERE entry=-3469000; /* content: I\'ve made no mistakes. */
UPDATE gossip_texts SET content_loc8='You have lost your mind, Nefarius. You speak in riddles.' WHERE entry=-3469001; /* content: You have lost your mind, Nefarius. You speak in riddles. */
UPDATE gossip_texts SET content_loc8='Please do.' WHERE entry=-3469002; /* content: Please do. */
UPDATE gossip_texts SET content_loc8='I cannot, Vaelastrasz! Surely something can be done to heal you!' WHERE entry=-3469003; /* content: I cannot, Vaelastrasz! Surely something can be done to heal you! */
UPDATE gossip_texts SET content_loc8='Vaelastrasz, no!!!' WHERE entry=-3469004; /* content: Vaelastrasz, no!!! */
UPDATE gossip_texts SET content_loc8='Let\'s find out.' WHERE entry=-3509000; /* content: Let\'s find out. */
UPDATE gossip_texts SET content_loc8='Teleport me to the Guardian\'s Library' WHERE entry=-3532000; /* content: Teleport me to the Guardian\'s Library */
UPDATE gossip_texts SET content_loc8='Ok, I\'ll give it a try, then.' WHERE entry=-3532002; /* content: Ok, I\'ll give it a try, then. */
UPDATE gossip_texts SET content_loc8='I\'ve never been more ready.' WHERE entry=-3532003; /* content: I\'ve never been more ready. */
UPDATE gossip_texts SET content_loc8='The wolf\'s going down.' WHERE entry=-3532004; /* content: The wolf\'s going down. */
UPDATE gossip_texts SET content_loc8='What phat lewtz you have grandmother?' WHERE entry=-3532005; /* content: What phat lewtz you have grandmother? */
UPDATE gossip_texts SET content_loc8='Control Orc Grunt' WHERE entry=-3532006; /* content: Control Orc Grunt */
UPDATE gossip_texts SET content_loc8='Control Orc Wolf' WHERE entry=-3532007; /* content: Control Orc Wolf */
UPDATE gossip_texts SET content_loc8='Control Summoned Daemon' WHERE entry=-3532008; /* content: Control Summoned Daemon */
UPDATE gossip_texts SET content_loc8='Control Orc Warlock' WHERE entry=-3532009; /* content: Control Orc Warlock */
UPDATE gossip_texts SET content_loc8='Control Orc Necrolyte' WHERE entry=-3532010; /* content: Control Orc Necrolyte */
UPDATE gossip_texts SET content_loc8='Control Human Footman' WHERE entry=-3532012; /* content: Control Human Footman */
UPDATE gossip_texts SET content_loc8='Control Human Charger' WHERE entry=-3532013; /* content: Control Human Charger */
UPDATE gossip_texts SET content_loc8='Control Conjured Water Elemental' WHERE entry=-3532014; /* content: Control Conjured Water Elemental */
UPDATE gossip_texts SET content_loc8='Control Human Conjurer' WHERE entry=-3532015; /* content: Control Human Conjurer */
UPDATE gossip_texts SET content_loc8='Control Human Cleric' WHERE entry=-3532016; /* content: Control Human Cleric */
UPDATE gossip_texts SET content_loc8='Control King Llane' WHERE entry=-3532017; /* content: Control King Llane */
UPDATE gossip_texts SET content_loc8='Please reset the chess board, we would like to play again.' WHERE entry=-3532018; /* content: Please reset the chess board, we would like to play again. */
UPDATE gossip_texts SET content_loc8='My companions and I are with you, Lady Proudmoore.' WHERE entry=-3534000; /* content: My companions and I are with you, Lady Proudmoore. */
UPDATE gossip_texts SET content_loc8='We are ready for whatever Archimonde might send our way, Lady Proudmoore.' WHERE entry=-3534001; /* content: We are ready for whatever Archimonde might send our way, Lady Proudmoore. */
UPDATE gossip_texts SET content_loc8='Until we meet again, Lady Proudmoore.' WHERE entry=-3534002; /* content: Until we meet again, Lady Proudmoore. */
UPDATE gossip_texts SET content_loc8='I am with you, Thrall.' WHERE entry=-3534003; /* content: I am with you, Thrall. */
UPDATE gossip_texts SET content_loc8='We have nothing to fear.' WHERE entry=-3534004; /* content: We have nothing to fear. */
UPDATE gossip_texts SET content_loc8='Until we meet again, Thrall.' WHERE entry=-3534005; /* content: Until we meet again, Thrall. */
UPDATE gossip_texts SET content_loc8='I would be grateful for any aid you can provide, Priestess.' WHERE entry=-3534006; /* content: I would be grateful for any aid you can provide, Priestess. */
UPDATE gossip_texts SET content_loc8='We\'ll get you out. Taretha. Don\'t worry. I doubt the wizard would wander too far away.' WHERE entry=-3560006; /* content: We\'ll get you out. Taretha. Don\'t worry. I doubt the wizard would wander too far away. */
UPDATE gossip_texts SET content_loc8='I\'m ready, Akama.' WHERE entry=-3564001; /* content: I\'m ready, Akama. */
UPDATE gossip_texts SET content_loc8='We\'re ready to face Illidan.' WHERE entry=-3564002; /* content: We\'re ready to face Illidan. */
UPDATE gossip_texts SET content_loc8='Thanks for the concern, but we intend to explore Zul\'Aman.' WHERE entry=-3568000; /* content: Thanks for the concern, but we intend to explore Zul\'Aman. */
UPDATE gossip_texts SET content_loc8='Chromie, you and I both know what\'s going to happen in this time stream. We\'ve seen this all before.$B$BCan you just skip us ahead to all the real action?' WHERE entry=-3595006; /* content: Chromie, you and I both know what\'s going to happen in this time stream. We\'ve seen this all before.$B$BCan you just skip us ahead to all the real action? */
UPDATE gossip_texts SET content_loc8='Brann, it would be our honor!' WHERE entry=-3599000; /* content: Brann, it would be our honor! */
UPDATE gossip_texts SET content_loc8='Let\'s move Brann, enough of the history lessons!' WHERE entry=-3599001; /* content: Let\'s move Brann, enough of the history lessons! */
UPDATE gossip_texts SET content_loc8='Teleport to the Expedition Base Camp.' WHERE entry=-3603000; /* content: Teleport to the Expedition Base Camp. */
UPDATE gossip_texts SET content_loc8='Teleport to the Formation Grounds.' WHERE entry=-3603001; /* content: Teleport to the Formation Grounds. */
UPDATE gossip_texts SET content_loc8='Teleport to the Colossal Forge.' WHERE entry=-3603002; /* content: Teleport to the Colossal Forge. */
UPDATE gossip_texts SET content_loc8='Teleport to the Scrapyard.' WHERE entry=-3603003; /* content: Teleport to the Scrapyard. */
UPDATE gossip_texts SET content_loc8='Teleport to the Antechamber of Ulduar.' WHERE entry=-3603004; /* content: Teleport to the Antechamber of Ulduar. */
UPDATE gossip_texts SET content_loc8='Teleport to the Shattered Walkway.' WHERE entry=-3603005; /* content: Teleport to the Shattered Walkway. */
UPDATE gossip_texts SET content_loc8='Teleport to the Conservatory of Life.' WHERE entry=-3603006; /* content: Teleport to the Conservatory of Life. */
UPDATE gossip_texts SET content_loc8='Teleport to the Spark of Imagination.' WHERE entry=-3603007; /* content: Teleport to the Spark of Imagination. */
UPDATE gossip_texts SET content_loc8='Teleport to the Prison of Yogg-Saron.' WHERE entry=-3603008; /* content: Teleport to the Prison of Yogg-Saron. */
UPDATE gossip_texts SET content_loc8='We are ready to help!' WHERE entry=-3603009; /* content: We are ready to help! */
UPDATE gossip_texts SET content_loc8='Activate secondary defensive systems.' WHERE entry=-3603010; /* content: Activate secondary defensive systems. */
UPDATE gossip_texts SET content_loc8='Confirmed.' WHERE entry=-3603011; /* content: Confirmed. */
UPDATE gossip_texts SET content_loc8='We\'re ready. Begin the assault!' WHERE entry=-3603012; /* content: We\'re ready. Begin the assault! */
UPDATE gossip_texts SET content_loc8='Lend us your aid, keeper. Together we will defeat Yogg-Saron.' WHERE entry=-3603013; /* content: Lend us your aid, keeper. Together we will defeat Yogg-Saron. */
UPDATE gossip_texts SET content_loc8='Yes.' WHERE entry=-3603014; /* content: Yes. */
UPDATE gossip_texts SET content_loc8='Activate the crystals when we get in trouble, right?' WHERE entry=-3608000; /* content: Activate the crystals when we get in trouble, right? */
UPDATE gossip_texts SET content_loc8='Get your people to safety, we\'ll keep the Blue Dragonflight\'s forces at bay.' WHERE entry=-3608001; /* content: Get your people to safety, we\'ll keep the Blue Dragonflight\'s forces at bay. */
UPDATE gossip_texts SET content_loc8='I\'m not fighting, so send me in now!' WHERE entry=-3608002; /* content: I\'m not fighting, so send me in now! */
UPDATE gossip_texts SET content_loc8='Yes. We are prepared for the challenges ahead of us.' WHERE entry=-3649000; /* content: Yes. We are prepared for the challenges ahead of us. */
UPDATE gossip_texts SET content_loc8='Bring forth the first challenge!' WHERE entry=-3649001; /* content: Bring forth the first challenge! */
UPDATE gossip_texts SET content_loc8='We want another shot at those beasts!' WHERE entry=-3649002; /* content: We want another shot at those beasts! */
UPDATE gossip_texts SET content_loc8='What new challenge awaits us?' WHERE entry=-3649003; /* content: What new challenge awaits us? */
UPDATE gossip_texts SET content_loc8='We\'re ready to fight the sorceror again.' WHERE entry=-3649004; /* content: We\'re ready to fight the sorceror again. */
UPDATE gossip_texts SET content_loc8='Of course!' WHERE entry=-3649005; /* content: Of course! */
UPDATE gossip_texts SET content_loc8='Give the signal! We\'re ready to go!' WHERE entry=-3649006; /* content: Give the signal! We\'re ready to go! */
UPDATE gossip_texts SET content_loc8='That tough, huh?' WHERE entry=-3649007; /* content: That tough, huh? */
UPDATE gossip_texts SET content_loc8='Val\'kyr? We\'re ready for them' WHERE entry=-3649008; /* content: Val\'kyr? We\'re ready for them */
UPDATE gossip_texts SET content_loc8='Your words of praise are appreciated, Coliseum Master.' WHERE entry=-3649009; /* content: Your words of praise are appreciated, Coliseum Master. */
UPDATE gossip_texts SET content_loc8='That is strange...' WHERE entry=-3649010; /* content: That is strange... */
UPDATE gossip_texts SET content_loc8='I am ready. However, I\'d like to skip the pageantry.' WHERE entry=-3650001; /* content: I am ready. However, I\'d like to skip the pageantry. */
UPDATE gossip_texts SET content_loc8='I am ready for the next challenge.' WHERE entry=-3650002; /* content: I am ready for the next challenge. */

SET NAMES 'latin1';
