-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc8`='%s, кажется, больше не может применять заклинания. Проклятие Скверны работает!' WHERE `word_id` = 5570; -- creature_ai_texts - content : entry=-1058
UPDATE `trans_words` SET `content_loc8`='Предсмертный крик |3-1(%s) потревожил соседний улей силитидов!' WHERE `word_id` = 5892; -- creature_ai_texts - content : entry=-748
UPDATE `trans_words` SET `content_loc8`='%s прекращает смеяться...' WHERE `word_id` = 5903; -- creature_ai_texts - content : entry=-646
UPDATE `trans_words` SET `content_loc8`='.. the hunter will become the hunted.' WHERE `word_id` = 6769; -- creature_ai_texts - content : entry=-996
UPDATE `trans_words` SET `content_loc8`='<Angry roar>' WHERE `word_id` = 3077; -- creature_ai_texts - content : entry=-26
UPDATE `trans_words` SET `content_loc8`='Они все... мертвы?..' WHERE `word_id` = 5607; -- creature_ai_texts - content : entry=-981
UPDATE `trans_words` SET `content_loc8`='Наконец-то все кончается...' WHERE `word_id` = 5542; -- creature_ai_texts - content : entry=-1298
UPDATE `trans_words` SET `content_loc8`='Наконец-то один из вас достоин моих знаний. Не беспокойся же, ибо я прозреваю мысли твои. Тебе не причинят зла.' WHERE `word_id` = 5906; -- creature_ai_texts - content : entry=-740
UPDATE `trans_words` SET `content_loc8`='Азерот слишком долго дрожал от страха в нашей тени! А теперь почувствуйте мощь Пылающего Легиона и впадите в отчаяние!' WHERE `word_id` = 5998; -- creature_ai_texts - content : entry=-1206
UPDATE `trans_words` SET `content_loc8`='%s призывает себе в помощь кабалиста-послушника!' WHERE `word_id` = 5968; -- creature_ai_texts - content : entry=-1248
UPDATE `trans_words` SET `content_loc8`='%s призывает себе на помощь кабалиста-пеплоуста!' WHERE `word_id` = 5969; -- creature_ai_texts - content : entry=-1247
UPDATE `trans_words` SET `content_loc8`='Код Проклятия теперь принадлежит нам!' WHERE `word_id` = 6528; -- creature_ai_texts - content : entry=-23
UPDATE `trans_words` SET `content_loc8`='Прячьтесь, жалкие черви! Ваши хилые герои - ничто! Ваши спасители станут нам первым блюдом!' WHERE `word_id` = 5996; -- creature_ai_texts - content : entry=-1208
UPDATE `trans_words` SET `content_loc8`='Разберись с этой помехой, Кельдонус. А когда закончишь, принеси мне голову этого... или этой... |3-1($N) или какое там имя они произносят. Череп послужит украшением моих покоев.' WHERE `word_id` = 6847; -- creature_ai_texts - content : entry=-268280
UPDATE `trans_words` SET `content_loc8`='Друидское ничтожество! Разделение твоей сущности только ослабило тебя и позволило хозяину захватить Изумрудный Сон! Твой дух и тело умрут здесь!' WHERE `word_id` = 6632; -- creature_ai_texts - content : entry=-656
UPDATE `trans_words` SET `content_loc8`='$GГлупый:Глупая; $N, теперь ты служишь мне!' WHERE `word_id` = 5545; -- creature_ai_texts - content : entry=-1295
UPDATE `trans_words` SET `content_loc8`='Идиоты! Так и знал, если надавить моему братцу на жалость, он пришлет \"спасателей\"' WHERE `word_id` = 5898; -- creature_ai_texts - content : entry=-344
UPDATE `trans_words` SET `content_loc8`='Get it while it\'s hot!' WHERE `word_id` = 5895; -- creature_ai_texts - content : entry=-142
UPDATE `trans_words` SET `content_loc8`='Ха! Это место не достойно еще моей кары!' WHERE `word_id` = 5992; -- creature_ai_texts - content : entry=-1212
UPDATE `trans_words` SET `content_loc8`='Как же просто было убедить тебя забрать последний камень Сунтары у этих идиотов из Сумеречного Молота.' WHERE `word_id` = 5899; -- creature_ai_texts - content : entry=-642
UPDATE `trans_words` SET `content_loc8`='Госпожа! Они хотят уничтожить плоды твоих трудов!' WHERE `word_id` = 5603; -- creature_ai_texts - content : entry=-985
UPDATE `trans_words` SET `content_loc8`='Проходи, |3-6($C)!.' WHERE `word_id` = 6125; -- creature_ai_texts - content : entry=-937
UPDATE `trans_words` SET `content_loc8`='Обсидион, встань и служи своему хозяину!' WHERE `word_id` = 5905; -- creature_ai_texts - content : entry=-673
UPDATE `trans_words` SET `content_loc8`='До свидания, $N!' WHERE `word_id` = 6126; -- creature_ai_texts - content : entry=-936
UPDATE `trans_words` SET `content_loc8`='%s откладывает яйцо!' WHERE `word_id` = 5529; -- creature_ai_texts - content : entry=-1317
UPDATE `trans_words` SET `content_loc8`='Such a waste.' WHERE `word_id` = 3078; -- creature_ai_texts - content : entry=-27
UPDATE `trans_words` SET `content_loc8`='$C, Мельницы Агамондов захвачены Плетью. Присоединяйся к нам!' WHERE `word_id` = 5587; -- creature_ai_texts - content : entry=-1034
UPDATE `trans_words` SET `content_loc8`='Темная Госпожа сражалась, покуда могла, но в конце концов... Надеюсь, она выжила. Пожалуйста, помогите!' WHERE `word_id` = 6770; -- creature_ai_texts - content : entry=-1011
UPDATE `trans_words` SET `content_loc8`='Сокол побежден, он уже никогда не возродится вновь! Твое задание бесполезно!' WHERE `word_id` = 6552; -- creature_ai_texts - content : entry=-242
UPDATE `trans_words` SET `content_loc8`='Алый орден обречен на успех!' WHERE `word_id` = 5591; -- creature_ai_texts - content : entry=-1030
UPDATE `trans_words` SET `content_loc8`='Это преступление против синих драконов было замечено. Мне доставит особенное удовольствие отделить источник жизненной энергии от твоего тела!' WHERE `word_id` = 6839; -- creature_ai_texts - content : entry=-268321
UPDATE `trans_words` SET `content_loc8`='Что?! Да как ты смеешь!' WHERE `word_id` = 5897; -- creature_ai_texts - content : entry=-700
UPDATE `trans_words` SET `content_loc8`='Где? Где Осколки? Вы не можете спрятать их от нас!' WHERE `word_id` = 5995; -- creature_ai_texts - content : entry=-1209
UPDATE `trans_words` SET `content_loc8`='Ох! Здесь наносится большой урон от магии смеха, да?' WHERE `word_id` = 6016; -- creature_ai_texts - content : entry=-1118
UPDATE `trans_words` SET `content_loc8`='You are in the presence of a god!' WHERE `word_id` = 5575; -- creature_ai_texts - content : entry=-1048
UPDATE `trans_words` SET `content_loc8`='Азерот, твоя судьба предрешена! Я найду камни Аспектов, и тогда ты не выстоишь против моей мощи!' WHERE `word_id` = 5997; -- creature_ai_texts - content : entry=-1207
UPDATE `trans_words` SET `content_loc8`='Твоя сила наполняет меня, $N!' WHERE `word_id` = 5993; -- creature_ai_texts - content : entry=-1211
UPDATE `trans_words` SET `content_loc8`='Твоя жалкая попытка спастись безнадежна, Кровожад. Отпусти $Gпарня:девушку; и подчинись! Даже со своей броней и оружием ты не сможешь победить древних!' WHERE `word_id` = 6536; -- creature_ai_texts - content : entry=-1320
UPDATE `trans_words` SET `content_loc8`='Ваш мир погибнет, смертные! Вы все обречены!' WHERE `word_id` = 5994; -- creature_ai_texts - content : entry=-1210

SET NAMES 'latin1';
