-- File generated by Mangos Online Translation Editor (MOTE) v2.06
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc8`='Terenthis begins to cast a spell as you take the cloak from him.' WHERE `word_id` = 7067; -- db_script_string - content : entry=2000000006
UPDATE `trans_words` SET `content_loc8`='Greatmother Hawkwind gestures to the pitcher of water sitting on the edge of the well.' WHERE `word_id` = 7687; -- db_script_string - content : entry=2000000027
UPDATE `trans_words` SET `content_loc8`='Follow, $N. I will soon begin the summoning...' WHERE `word_id` = 6954; -- db_script_string - content : entry=2000000029
UPDATE `trans_words` SET `content_loc8`='This makes sense!' WHERE `word_id` = 6955; -- db_script_string - content : entry=2000000030
UPDATE `trans_words` SET `content_loc8`='Gird yourself $N, for the demon in this orb is a fel beast.' WHERE `word_id` = 6956; -- db_script_string - content : entry=2000000032
UPDATE `trans_words` SET `content_loc8`='Glowing Soulgem bursts open!' WHERE `word_id` = 6967; -- db_script_string - content : entry=2000000051
UPDATE `trans_words` SET `content_loc8`='Sarath fades into the mist...' WHERE `word_id` = 7427; -- db_script_string - content : entry=2000000053
UPDATE `trans_words` SET `content_loc8`='Hey there, Belm! Give me a mug of Thunder Ale, and one for my good friend $N.' WHERE `word_id` = 6971; -- db_script_string - content : entry=2000000056
UPDATE `trans_words` SET `content_loc8`='The invisibility liquer is ready for you, $N.' WHERE `word_id` = 7689; -- db_script_string - content : entry=2000000081
UPDATE `trans_words` SET `content_loc8`='My mind. . .my flesh. . .I\'m. . .rotting. . . .!' WHERE `word_id` = 6980; -- db_script_string - content : entry=2000000083
UPDATE `trans_words` SET `content_loc8`='I raise my brew and hope to be rid of the likes of you! Cheers, you no good scoundrel, $N!' WHERE `word_id` = 7690; -- db_script_string - content : entry=2000000084
UPDATE `trans_words` SET `content_loc8`='Denalan removes the seeds from the Glowing Fruit...' WHERE `word_id` = 7692; -- db_script_string - content : entry=2000000086
UPDATE `trans_words` SET `content_loc8`='Denalan plants fruit seeds.' WHERE `word_id` = 7694; -- db_script_string - content : entry=2000000088
UPDATE `trans_words` SET `content_loc8`='Bogling rises from the soil!' WHERE `word_id` = 7695; -- db_script_string - content : entry=2000000089
UPDATE `trans_words` SET `content_loc8`='Onu studies the parchment from the Twilight Tome...' WHERE `word_id` = 6983; -- db_script_string - content : entry=2000000090
UPDATE `trans_words` SET `content_loc8`='Onu is struck by unleashed magic!' WHERE `word_id` = 6982; -- db_script_string - content : entry=2000000091
UPDATE `trans_words` SET `content_loc8`='Denalan hurries to his planter.' WHERE `word_id` = 7696; -- db_script_string - content : entry=2000000093
UPDATE `trans_words` SET `content_loc8`='Zarlman Two-Moons begins chanting as he mixes the well stones and ambercom before the Tribal Fire.' WHERE `word_id` = 7345; -- db_script_string - content : entry=2000000095
UPDATE `trans_words` SET `content_loc8`='Tonga Runetotem inspects the snapjaw shells...' WHERE `word_id` = 7698; -- db_script_string - content : entry=2000000097
UPDATE `trans_words` SET `content_loc8`='Ok, let\'s get started!' WHERE `word_id` = 7422; -- db_script_string - content : entry=2000000103
UPDATE `trans_words` SET `content_loc8`='You were right to come. My wisdom will be yours.' WHERE `word_id` = 6986; -- db_script_string - content : entry=2000000109
UPDATE `trans_words` SET `content_loc8`='There we are, $N. The toxin is ready.' WHERE `word_id` = 6988; -- db_script_string - content : entry=2000000111
UPDATE `trans_words` SET `content_loc8`='Easier then I expected... the sigil of Thoradin is whole, once again.' WHERE `word_id` = 6994; -- db_script_string - content : entry=2000000118
UPDATE `trans_words` SET `content_loc8`='%s takes big swig of ale.' WHERE `word_id` = 6997; -- db_script_string - content : entry=2000000119
UPDATE `trans_words` SET `content_loc8`='I believe the Forsaken are misleading the allies of the Horde... wait... I feel so... dizzy...' WHERE `word_id` = 6995; -- db_script_string - content : entry=2000000121
UPDATE `trans_words` SET `content_loc8`='Wow! $N, that dream dust is powerful stuff!' WHERE `word_id` = 7217; -- db_script_string - content : entry=2000000129
UPDATE `trans_words` SET `content_loc8`='Drink this, you blue brute! Disobey me and I promise you a slow, painful death!' WHERE `word_id` = 7770; -- db_script_string - content : entry=2000000256
UPDATE `trans_words` SET `content_loc8`='I pity you Forsaken, Your soul is devoid of light.' WHERE `word_id` = 7771; -- db_script_string - content : entry=2000000257
UPDATE `trans_words` SET `content_loc8`='The Lorehammer ist reacting. This must be from Stormhoof\'s time.' WHERE `word_id` = 7787; -- db_script_string - content : entry=2000000274
UPDATE `trans_words` SET `content_loc8`='Why do you do this? Did I somehow wrong you in life?' WHERE `word_id` = 7809; -- db_script_string - content : entry=2000000319
UPDATE `trans_words` SET `content_loc8`='Ah, I see it now in your mind. This is the work of one of my former students... Mehlar Dawnblade. It is sad to know that his heart has turned so dark.' WHERE `word_id` = 7810; -- db_script_string - content : entry=2000000320
UPDATE `trans_words` SET `content_loc8`='Return to him. Return to Mehlor and tell him that I forgive him and that I understand why he believes what he does.' WHERE `word_id` = 7811; -- db_script_string - content : entry=2000000321
UPDATE `trans_words` SET `content_loc8`='Ograbisi needs new hat.' WHERE `word_id` = 7360; -- db_script_string - content : entry=2000000326
UPDATE `trans_words` SET `content_loc8`='%s falls into drunken sleep.' WHERE `word_id` = 7828; -- db_script_string - content : entry=2000000342
UPDATE `trans_words` SET `content_loc8`='%s wakes up and slowly rises to his feet.' WHERE `word_id` = 7829; -- db_script_string - content : entry=2000000343
UPDATE `trans_words` SET `content_loc8`='Who... who are you? Who.. what am I?' WHERE `word_id` = 7835; -- db_script_string - content : entry=2000000351
UPDATE `trans_words` SET `content_loc8`='I have awoken to a nightmare?' WHERE `word_id` = 7851; -- db_script_string - content : entry=2000000367
UPDATE `trans_words` SET `content_loc8`='Come, $N. The lake is around the bend.' WHERE `word_id` = 7858; -- db_script_string - content : entry=2000000375
UPDATE `trans_words` SET `content_loc8`='Remulos, old friend. It is good to see you once more. I knew the message would find its way to you - one way or another.' WHERE `word_id` = 7310; -- db_script_string - content : entry=2000000378
UPDATE `trans_words` SET `content_loc8`='I fear for the worst, old friend. Within the Dream we fight a new foe, born of an ancient evil. Ysera\'s noble brood has fallen victim to the old whisperings. It seems as if the Nightmare has broken through the realm to find a new host on Azeroth.' WHERE `word_id` = 7862; -- db_script_string - content : entry=2000000380
UPDATE `trans_words` SET `content_loc8`='Aye Remulos, prepare the mortal races.' WHERE `word_id` = 7864; -- db_script_string - content : entry=2000000382
UPDATE `trans_words` SET `content_loc8`='You have been gone too long, Malfurion. Peace between the Children of Azeroth has become tenuous at best. What of my father? Of your brother? Have you any news?' WHERE `word_id` = 7315; -- db_script_string - content : entry=2000000383
UPDATE `trans_words` SET `content_loc8`='Cenarius fights at my side. Illidan sits atop his throne in Outland - brooding. I\'m afraid that the loss to Arthas proved to be his breaking point. Madness has embraced him, Remulos. He replays the events in his mind a thousand times per day, but in his mind, he is the victor and Arthas is utterly defeated. He is too far gone, old friend. I fear that the time may soon come that our bond is tested and it will not be as it was at the Well in Zin-Azshari.' WHERE `word_id` = 7316; -- db_script_string - content : entry=2000000384
UPDATE `trans_words` SET `content_loc8`='Remulos, I am being drawn back... Tyrande... send her my love... Tell her I am safe... Tell her... Tell her I will return... Farewell...' WHERE `word_id` = 7317; -- db_script_string - content : entry=2000000385
UPDATE `trans_words` SET `content_loc8`='%s scurries away, attempting to flee from Twinkle.' WHERE `word_id` = 7620; -- db_script_string - content : entry=2000000391
UPDATE `trans_words` SET `content_loc8`='Did you find something fun to chase around, Twinkle?' WHERE `word_id` = 7878; -- db_script_string - content : entry=2000000406
UPDATE `trans_words` SET `content_loc8`='Havenshire is lost.' WHERE `word_id` = 7884; -- db_script_string - content : entry=2000000412
UPDATE `trans_words` SET `content_loc8`='%s reads from the book of the dead.' WHERE `word_id` = 268248; -- db_script_string - content : entry=2000000488
UPDATE `trans_words` SET `content_loc8`='Shane Dabiri, Lee, Alex T., Rob F., J. A. B., A. Mayberry!' WHERE `word_id` = 268221; -- db_script_string - content : entry=2000000489
UPDATE `trans_words` SET `content_loc8`='Jeffrey Kaplan! Tom Chilton! Rob Pardo!' WHERE `word_id` = 268222; -- db_script_string - content : entry=2000000490
UPDATE `trans_words` SET `content_loc8`='Justin Thavirat! Roman Kenney! Our entire awesome art and animation team!' WHERE `word_id` = 268223; -- db_script_string - content : entry=2000000491
UPDATE `trans_words` SET `content_loc8`='Kevin Jordan and Jonathan LeCraft!' WHERE `word_id` = 268224; -- db_script_string - content : entry=2000000492
UPDATE `trans_words` SET `content_loc8`='Oh man, I thought I was dead for sure. Ugh... still dizzy...' WHERE `word_id` = 7195; -- db_script_string - content : entry=2000000519
UPDATE `trans_words` SET `content_loc8`='I can get back to Stronghold on my own, I think. Now that you bought me some time, I should be able to stealth out of here. Who ever you are... thank you. May Elune bless you always!' WHERE `word_id` = 7894; -- db_script_string - content : entry=2000000520
UPDATE `trans_words` SET `content_loc8`='I will need to focus my energies onto this knife. By doing so, I should catch some of the stronger psychic impressions associated with it.' WHERE `word_id` = 7361; -- db_script_string - content : entry=2000000521
UPDATE `trans_words` SET `content_loc8`='A History... Hmmmm... Let me examine this for a moment.' WHERE `word_id` = 7363; -- db_script_string - content : entry=2000000523
UPDATE `trans_words` SET `content_loc8`='Amazing! I think I have found it, $N.' WHERE `word_id` = 7365; -- db_script_string - content : entry=2000000525
UPDATE `trans_words` SET `content_loc8`='They will live of only to see the fruits of their labor: the destruction and chaos that will surely ensue as the legion of Blackrock invade the gorge.' WHERE `word_id` = 7371; -- db_script_string - content : entry=2000000531
UPDATE `trans_words` SET `content_loc8`='Freedom at last! I must return to Warsong at once!' WHERE `word_id` = 7897; -- db_script_string - content : entry=2000000560
UPDATE `trans_words` SET `content_loc8`='BY THE LIGHT OF ELUNE! Eredar! Cursed demons, what have you to me? I have not come alone, we will fight you as we have in the past! I...' WHERE `word_id` = 7636; -- db_script_string - content : entry=2000000660
UPDATE `trans_words` SET `content_loc8`='Turning to face Tuluun, the Draenei Artificer sneers contemptuously.' WHERE `word_id` = 7642; -- db_script_string - content : entry=2000000662
UPDATE `trans_words` SET `content_loc8`='Bijou lost! SQUAWK! *cough' WHERE `word_id` = 7062; -- db_script_string - content : entry=2000005002
UPDATE `trans_words` SET `content_loc8`='Yes right away momma!' WHERE `word_id` = 7066; -- db_script_string - content : entry=2000005011
UPDATE `trans_words` SET `content_loc8`='Ah, this must be him now... no?' WHERE `word_id` = 7070; -- db_script_string - content : entry=2000005018
UPDATE `trans_words` SET `content_loc8`='Wouldn\'t you like to bring those days back? I have some friends who know just the way to do that.' WHERE `word_id` = 7469; -- db_script_string - content : entry=2000005022
UPDATE `trans_words` SET `content_loc8`='Our oldest clutch of dragons are still far from maturity, but with patience and study, we are confident the dragons will soon be ready.' WHERE `word_id` = 7078; -- db_script_string - content : entry=2000005029
UPDATE `trans_words` SET `content_loc8`='If you wait to come see me, there may be nothing left!' WHERE `word_id` = 7473; -- db_script_string - content : entry=2000005030
UPDATE `trans_words` SET `content_loc8`='...And then the tauren said, "13 INCHES!"' WHERE `word_id` = 7080; -- db_script_string - content : entry=2000005032
UPDATE `trans_words` SET `content_loc8`='New posting up! Adventurers and heroes, gather round the bulletin board!' WHERE `word_id` = 7482; -- db_script_string - content : entry=2000005042
UPDATE `trans_words` SET `content_loc8`='Hey, you there. Want some candy?' WHERE `word_id` = 7492; -- db_script_string - content : entry=2000005052
UPDATE `trans_words` SET `content_loc8`='What up son! Wait....is anyone there?' WHERE `word_id` = 7931; -- db_script_string - content : entry=2000005055
UPDATE `trans_words` SET `content_loc8`='This is the last time that I buy second-hand equipment from ethereal' WHERE `word_id` = 7466; -- db_script_string - content : entry=2000005067
UPDATE `trans_words` SET `content_loc8`='Not a challenge at all it seems. Let us see how hou handle your second test. Lysta, bring forth the minions of the Lich King.' WHERE `word_id` = 7561; -- db_script_string - content : entry=2000005073
UPDATE `trans_words` SET `content_loc8`='Oh sweet, delicious, spotted eggs - you will be mine...' WHERE `word_id` = 7573; -- db_script_string - content : entry=2000005093
UPDATE `trans_words` SET `content_loc8`='Of Course Im talking to myself. Only way to get a decent conversation in this city.' WHERE `word_id` = 7519; -- db_script_string - content : entry=2000005105
UPDATE `trans_words` SET `content_loc8`='Seems like a hundred times a day I walk all the way to get more water. No respect for their elders I tell ya.' WHERE `word_id` = 5747; -- db_script_string - content : entry=2000005107
UPDATE `trans_words` SET `content_loc8`='Deja vu. For a moment I thought I was back home... before the plague...' WHERE `word_id` = 7093; -- db_script_string - content : entry=2000005108
UPDATE `trans_words` SET `content_loc8`='Children if you would please follow me, we will now be going to see the keep where King Anduin Wrynn himself sits on this throne.' WHERE `word_id` = 7113; -- db_script_string - content : entry=2000005136
UPDATE `trans_words` SET `content_loc8`='Sure Paige. Just be gentle.' WHERE `word_id` = 7141; -- db_script_string - content : entry=2000005181
UPDATE `trans_words` SET `content_loc8`='Fizzles used to be a great wizard. But got turned into a rabbit when one of his spells went bad.' WHERE `word_id` = 7144; -- db_script_string - content : entry=2000005184
UPDATE `trans_words` SET `content_loc8`='Hey, harbringer, how\'s that research coming along? There might be an Ultra-Kinetic Waffle Iron in it for you if you\'re prompt with the results!' WHERE `word_id` = 6158; -- db_script_string - content : entry=2000005201
UPDATE `trans_words` SET `content_loc8`='The Darkmoon Faire is the greatest event in all of Outland' WHERE `word_id` = 7540; -- db_script_string - content : entry=2000005221
UPDATE `trans_words` SET `content_loc8`='Just sit right back and you\'ll hear a ta... *hic* a tai... *hic* a taiii *hic* Damnit!' WHERE `word_id` = 7156; -- db_script_string - content : entry=2000005233
UPDATE `trans_words` SET `content_loc8`='We will act when we know what we need, old friend. The druids have proven wise and capable of making their own decisions.' WHERE `word_id` = 7942; -- db_script_string - content : entry=2000005247
UPDATE `trans_words` SET `content_loc8`='You need to do what? All this science. I don\'t understand... Look, this is just my job, five days a week.' WHERE `word_id` = 7945; -- db_script_string - content : entry=2000005250
UPDATE `trans_words` SET `content_loc8`='Hmm... the readings on the gravimeteric distortions seem to have stabalized. We did it!' WHERE `word_id` = 7955; -- db_script_string - content : entry=2000005260
UPDATE `trans_words` SET `content_loc8`='Hold your tongue, knave! Do not dare use that tone with a priestess of the Light!' WHERE `word_id` = 7968; -- db_script_string - content : entry=2000005273
UPDATE `trans_words` SET `content_loc8`='I\'m surrounded by idiots.' WHERE `word_id` = 7969; -- db_script_string - content : entry=2000005274
UPDATE `trans_words` SET `content_loc8`='Back to the topic... we should focus our attention on these manaforges. We need to learn what the enemy is doing with them and why.' WHERE `word_id` = 7971; -- db_script_string - content : entry=2000005276
UPDATE `trans_words` SET `content_loc8`='Even you must admit that your information from defectors is outdated and unreliable. Let us make calculated attacks on these manaforges and gather what information we can.' WHERE `word_id` = 7974; -- db_script_string - content : entry=2000005279
UPDATE `trans_words` SET `content_loc8`='Who? The Tauren Chieftains! What? A live performance. Where? The World\'s End Tavern! When? The top of the hour! BE THERE!' WHERE `word_id` = 7439; -- db_script_string - content : entry=2000005305
UPDATE `trans_words` SET `content_loc8`='Anaya\'s soft voice trails away into the mists. "Know that I love you always..."' WHERE `word_id` = 7428; -- db_script_string - content : entry=2000005344
UPDATE `trans_words` SET `content_loc8`='Thank you, $N. And luck to you.' WHERE `word_id` = 7184; -- db_script_string - content : entry=2000005346
UPDATE `trans_words` SET `content_loc8`='Grimclaw roars at Terenthis to get his attention.' WHERE `word_id` = 7194; -- db_script_string - content : entry=2000005385
UPDATE `trans_words` SET `content_loc8`='Grimclaw begins to moan and roar at Terenthis while stomping his paws on the ground.' WHERE `word_id` = 7191; -- db_script_string - content : entry=2000005387
UPDATE `trans_words` SET `content_loc8`='Terenthis begins to cast a spell on Grimclaw.' WHERE `word_id` = 7189; -- db_script_string - content : entry=2000005389
UPDATE `trans_words` SET `content_loc8`='Grimclaw roars at Terenthis more, but this time the druid seems to understand the bear.' WHERE `word_id` = 7187; -- db_script_string - content : entry=2000005391
UPDATE `trans_words` SET `content_loc8`='Grimclaw roars in acknowledgement at Terenthis.' WHERE `word_id` = 7185; -- db_script_string - content : entry=2000005393
UPDATE `trans_words` SET `content_loc8`='How dare you take my eye! I will crush your soul and feed it to my blind and wimpering imps!' WHERE `word_id` = 8009; -- db_script_string - content : entry=2000005405
UPDATE `trans_words` SET `content_loc8`='Come to my lair, whelp! Come to me and pay for your insolecne!' WHERE `word_id` = 8010; -- db_script_string - content : entry=2000005406
UPDATE `trans_words` SET `content_loc8`='The boss wants all hands on high alert. The rusty anchor sinks tonight.' WHERE `word_id` = 7225; -- db_script_string - content : entry=2000005408
UPDATE `trans_words` SET `content_loc8`='How dare you trifle with my playthings!' WHERE `word_id` = 6543; -- db_script_string - content : entry=2000005441
UPDATE `trans_words` SET `content_loc8`='The orcs in my citadel will drink your blood and dovour you!' WHERE `word_id` = 8034; -- db_script_string - content : entry=2000005442
UPDATE `trans_words` SET `content_loc8`='I\'ve rigged a few control consoles down the slope. Get one quickly and take control of the fel reaver! You\'ll only have a limited amount of time.' WHERE `word_id` = 8049; -- db_script_string - content : entry=2000005459
UPDATE `trans_words` SET `content_loc8`='And... I we do not?' WHERE `word_id` = 8052; -- db_script_string - content : entry=2000005467
UPDATE `trans_words` SET `content_loc8`='Keep up the good work. Do well and you will be rewarded by the master.' WHERE `word_id` = 8055; -- db_script_string - content : entry=2000005470
UPDATE `trans_words` SET `content_loc8`='Waste no time, fool! Use our power to kill those what stand in our way! Destroy Krasius before you are subdued!' WHERE `word_id` = 8058; -- db_script_string - content : entry=2000005473
UPDATE `trans_words` SET `content_loc8`='Spirits watch for you, $R.' WHERE `word_id` = 8105; -- db_script_string - content : entry=2000005523
UPDATE `trans_words` SET `content_loc8`='%s is chasing you!' WHERE `word_id` = 4035; -- db_script_string - content : entry=2000005546
UPDATE `trans_words` SET `content_loc8`='Who dares step into my domain! Come! Come, and be consumed!' WHERE `word_id` = 7203; -- db_script_string - content : entry=2000005552
UPDATE `trans_words` SET `content_loc8`='Pentarus, you heard the man. Have your mages release the shield and let these brave souls through!' WHERE `word_id` = 8141; -- db_script_string - content : entry=2000005572
UPDATE `trans_words` SET `content_loc8`='Of course, Brann: We will have the shield down momentarily.' WHERE `word_id` = 8142; -- db_script_string - content : entry=2000005573
UPDATE `trans_words` SET `content_loc8`='Okay! Let\'s move out. Get into your machines; I\'ll speak to you from here via the radio.' WHERE `word_id` = 8143; -- db_script_string - content : entry=2000005574
UPDATE `trans_words` SET `content_loc8`='I guess I\'ll go find the athorities. If I\'m lucky they\'ll tell me it\'s the plague and that we\'re all going to die.' WHERE `word_id` = 8190; -- db_script_string - content : entry=2000005622
UPDATE `trans_words` SET `content_loc8`='My legs feels much better now, the remedy must be working. If you will excuse me, I must go report to my superiors about what has transpired here.' WHERE `word_id` = 7246; -- db_script_string - content : entry=2000005630
UPDATE `trans_words` SET `content_loc8`='Your time is night...' WHERE `word_id` = 1379; -- db_script_string - content : entry=2000005640
UPDATE `trans_words` SET `content_loc8`='It is over, your search is done! Let fate choose now, the righteous one.' WHERE `word_id` = 1370; -- db_script_string - content : entry=2000005643
UPDATE `trans_words` SET `content_loc8`='I shall use this time wisely, milord. Thank you.' WHERE `word_id` = 7235; -- db_script_string - content : entry=2000005653
UPDATE `trans_words` SET `content_loc8`='$N, please take a look at the sample of the Vylestem vine that I took from the caverns, so thet you know what to look for...' WHERE `word_id` = 8202; -- db_script_string - content : entry=2000005664
UPDATE `trans_words` SET `content_loc8`='%s combines the herbs with the moonwell water to create the Ward of Waking' WHERE `word_id` = 8205; -- db_script_string - content : entry=2000005667
UPDATE `trans_words` SET `content_loc8`='%s cautiously approaches Wather Elaira.' WHERE `word_id` = 8210; -- db_script_string - content : entry=2000005672
UPDATE `trans_words` SET `content_loc8`='I\'m going to train you to help $N with very important task. After that, I promose you\'ll be free to return home.' WHERE `word_id` = 8211; -- db_script_string - content : entry=2000005673
UPDATE `trans_words` SET `content_loc8`='My the light bless you.' WHERE `word_id` = 8214; -- db_script_string - content : entry=2000005676
UPDATE `trans_words` SET `content_loc8`='Borgrim, this is no time for drinking. We just got here. We need to get settled in.' WHERE `word_id` = 8215; -- db_script_string - content : entry=2000005679
UPDATE `trans_words` SET `content_loc8`='I thought this was going to be our chance to get away from it all? Our vacation?' WHERE `word_id` = 8216; -- db_script_string - content : entry=2000005680
UPDATE `trans_words` SET `content_loc8`='This poster has a bounty on bonelashers. You think I should do that?' WHERE `word_id` = 8221; -- db_script_string - content : entry=2000005685
UPDATE `trans_words` SET `content_loc8`='The bonelashers of the wastes are no laughing matter. I hear they carry diseases!' WHERE `word_id` = 8224; -- db_script_string - content : entry=2000005688
UPDATE `trans_words` SET `content_loc8`='Now we call forth the the arcane acolyte.' WHERE `word_id` = 8253; -- db_script_string - content : entry=2000005720
UPDATE `trans_words` SET `content_loc8`='I am going to practice and become a warrior like my father!' WHERE `word_id` = 7255; -- db_script_string - content : entry=2000005767
UPDATE `trans_words` SET `content_loc8`='Now go back home where you belong!' WHERE `word_id` = 7260; -- db_script_string - content : entry=2000005772
UPDATE `trans_words` SET `content_loc8`='Aaahhh... Another glorious victory for The Horde!' WHERE `word_id` = 7261; -- db_script_string - content : entry=2000005773
UPDATE `trans_words` SET `content_loc8`='When is pappa comming back from the fights in Warsong? It has been so long...' WHERE `word_id` = 7263; -- db_script_string - content : entry=2000005775
UPDATE `trans_words` SET `content_loc8`='I thank you, $N. And my brother thanks you.' WHERE `word_id` = 8280; -- db_script_string - content : entry=2000005776
UPDATE `trans_words` SET `content_loc8`='%s listens to Sigilbringer\'s report...' WHERE `word_id` = 7252; -- db_script_string - content : entry=2000005777
UPDATE `trans_words` SET `content_loc8`='What?? The Burning Blade is spreading! We must investigate!' WHERE `word_id` = 7253; -- db_script_string - content : entry=2000005778
UPDATE `trans_words` SET `content_loc8`='We won. Dimensius no more. Report this proffesor Dabiri.' WHERE `word_id` = 8285; -- db_script_string - content : entry=2000005784
UPDATE `trans_words` SET `content_loc8`='Champion Vranesh arches a sculpted brow at the guards, a disapproving scowl on his face.' WHERE `word_id` = 8322; -- db_script_string - content : entry=2000005822
UPDATE `trans_words` SET `content_loc8`='Champion Vranesh glances from guard to guard.' WHERE `word_id` = 8323; -- db_script_string - content : entry=2000005823
UPDATE `trans_words` SET `content_loc8`='Champion Vranesh surveys the small ranger practice ground with a condescending smirk.' WHERE `word_id` = 8324; -- db_script_string - content : entry=2000005824
UPDATE `trans_words` SET `content_loc8`='Champion Vranesh inclines his head slightly to the pair of guardians in greeting.' WHERE `word_id` = 8325; -- db_script_string - content : entry=2000005825
UPDATE `trans_words` SET `content_loc8`='Glory to the Sun K-- ah.... Silvermoon!' WHERE `word_id` = 8327; -- db_script_string - content : entry=2000005827
UPDATE `trans_words` SET `content_loc8`='Let us hold or discussion in a more... private place. Follow me, $N.' WHERE `word_id` = 8330; -- db_script_string - content : entry=2000005832
UPDATE `trans_words` SET `content_loc8`='And who do we have here?  No doubt th... crzzzk ...ade this communication possible?  I give you greetings fro... psshzzzk... Azure Watch.' WHERE `word_id` = 268219; -- db_script_string - content : entry=2000005839

SET NAMES 'latin1';
