-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc8`='%s seems to no longer be able to cast spells...' WHERE `word_id` = 5570; -- creature_ai_texts - content : entry=-1058
UPDATE `trans_words` SET `content_loc8`='%s\'s death cry has stirred the nearby silithid hive.' WHERE `word_id` = 5892; -- creature_ai_texts - content : entry=-748
UPDATE `trans_words` SET `content_loc8`='%s\'s laughter trails off..' WHERE `word_id` = 5903; -- creature_ai_texts - content : entry=-646
UPDATE `trans_words` SET `content_loc8`='.. the hunter will become the hunted.' WHERE `word_id` = 6769; -- creature_ai_texts - content : entry=-996
UPDATE `trans_words` SET `content_loc8`='<Angry roar>' WHERE `word_id` = 3077; -- creature_ai_texts - content : entry=-26
UPDATE `trans_words` SET `content_loc8`='Are They all.... Dead?' WHERE `word_id` = 5607; -- creature_ai_texts - content : entry=-981
UPDATE `trans_words` SET `content_loc8`='At last, it ends...' WHERE `word_id` = 5542; -- creature_ai_texts - content : entry=-1298
UPDATE `trans_words` SET `content_loc8`='At last: one among you is worthy of my knowledge. Worry not: I have probed your thoughts, no harm will come to you.' WHERE `word_id` = 5906; -- creature_ai_texts - content : entry=-740
UPDATE `trans_words` SET `content_loc8`='Azeroth has cowered too long under our shadow! Now, feel the power of the Burning Crusade, and despair!' WHERE `word_id` = 5998; -- creature_ai_texts - content : entry=-1206
UPDATE `trans_words` SET `content_loc8`='Cabal Summoner summons a Cabal Acolyte to his aid!' WHERE `word_id` = 5968; -- creature_ai_texts - content : entry=-1248
UPDATE `trans_words` SET `content_loc8`='Cabal Summoner summons a Cabal Deathsworn to his aid!' WHERE `word_id` = 5969; -- creature_ai_texts - content : entry=-1247
UPDATE `trans_words` SET `content_loc8`='Cipher of Damnation belongs to us now!' WHERE `word_id` = 6528; -- creature_ai_texts - content : entry=-23
UPDATE `trans_words` SET `content_loc8`='Cower, little worms! Your heroes are nothing! Your saviors will be our first feast!' WHERE `word_id` = 5996; -- creature_ai_texts - content : entry=-1208
UPDATE `trans_words` SET `content_loc8`='Deal with this interruption, Keldonus. After you are through, bring the head of the one they call $N. I will decorate my chambers with their skull.' WHERE `word_id` = 6847; -- creature_ai_texts - content : entry=-268280
UPDATE `trans_words` SET `content_loc8`='Foolish druid! Dividing your essence has weakened you, opening the door for my master to dominate the Emerald Dream. Your spirit and body will die here!' WHERE `word_id` = 6632; -- creature_ai_texts - content : entry=-656
UPDATE `trans_words` SET `content_loc8`='Foolish mortal, you serve me now!' WHERE `word_id` = 5545; -- creature_ai_texts - content : entry=-1295
UPDATE `trans_words` SET `content_loc8`='Fools. I knew that if I played upon my brother\'s feeble emotions, he would send \'rescuers.\'' WHERE `word_id` = 5898; -- creature_ai_texts - content : entry=-344
UPDATE `trans_words` SET `content_loc8`='Get it while it\'s hot!' WHERE `word_id` = 5895; -- creature_ai_texts - content : entry=-142
UPDATE `trans_words` SET `content_loc8`='Ha! This place is not yet worthy of my infliction.' WHERE `word_id` = 5992; -- creature_ai_texts - content : entry=-1212
UPDATE `trans_words` SET `content_loc8`='How easy it was to manipulate you into recovering the last Suntara stone from those imbeciles of the Twilight\'s Hammer..' WHERE `word_id` = 5899; -- creature_ai_texts - content : entry=-642
UPDATE `trans_words` SET `content_loc8`='Mistress!! They seek to destroy your work!' WHERE `word_id` = 5603; -- creature_ai_texts - content : entry=-985
UPDATE `trans_words` SET `content_loc8`='Move along, $C.' WHERE `word_id` = 6125; -- creature_ai_texts - content : entry=-937
UPDATE `trans_words` SET `content_loc8`='Obsidion, Rise and Serve your Master!' WHERE `word_id` = 5905; -- creature_ai_texts - content : entry=-673
UPDATE `trans_words` SET `content_loc8`='Off with you, $N.' WHERE `word_id` = 6126; -- creature_ai_texts - content : entry=-936
UPDATE `trans_words` SET `content_loc8`='Silithid Creeper lays an egg!' WHERE `word_id` = 5529; -- creature_ai_texts - content : entry=-1317
UPDATE `trans_words` SET `content_loc8`='Such a waste.' WHERE `word_id` = 3078; -- creature_ai_texts - content : entry=-27
UPDATE `trans_words` SET `content_loc8`='The Agamand Mills is held by the Scourge, $C. Join us!' WHERE `word_id` = 5587; -- creature_ai_texts - content : entry=-1034
UPDATE `trans_words` SET `content_loc8`='The Dark Lady fought as many as she could, but in the end... I hope she survived. Please help!' WHERE `word_id` = 6770; -- creature_ai_texts - content : entry=-1011
UPDATE `trans_words` SET `content_loc8`='The falcon is vaniquished, doomed never to rise again! Your quest is futile!' WHERE `word_id` = 6552; -- creature_ai_texts - content : entry=-242
UPDATE `trans_words` SET `content_loc8`='The Scarlet Crusade shall not fail in it\'s mission!' WHERE `word_id` = 5591; -- creature_ai_texts - content : entry=-1030
UPDATE `trans_words` SET `content_loc8`='This transgression against the Blue Dragonsflight has been noted. I will take extra pleasure in separating the life energy from your body!' WHERE `word_id` = 6839; -- creature_ai_texts - content : entry=-268321
UPDATE `trans_words` SET `content_loc8`='What? How dare you!' WHERE `word_id` = 5897; -- creature_ai_texts - content : entry=-700
UPDATE `trans_words` SET `content_loc8`='Where? Where are the Shards! You cannot hide them from us!' WHERE `word_id` = 5995; -- creature_ai_texts - content : entry=-1209
UPDATE `trans_words` SET `content_loc8`='Wow! The laughs dont\'t drop very often here, do they?' WHERE `word_id` = 6016; -- creature_ai_texts - content : entry=-1118
UPDATE `trans_words` SET `content_loc8`='You are in the presence of a god!' WHERE `word_id` = 5575; -- creature_ai_texts - content : entry=-1048
UPDATE `trans_words` SET `content_loc8`='Your fate is sealed, Azeroth! I will find the Aspect Shards, and then you will not stand against our might!' WHERE `word_id` = 5997; -- creature_ai_texts - content : entry=-1207
UPDATE `trans_words` SET `content_loc8`='Your own strength feeds me!' WHERE `word_id` = 5993; -- creature_ai_texts - content : entry=-1211
UPDATE `trans_words` SET `content_loc8`='Your pathetic attempt to escape will be short lived, Gorefiend. Let the boy go and submit! Even with your armour and weapons, you cannot defeat the ancients!' WHERE `word_id` = 6536; -- creature_ai_texts - content : entry=-1320
UPDATE `trans_words` SET `content_loc8`='Your world will die, mortals! Your doom is now at hand!' WHERE `word_id` = 5994; -- creature_ai_texts - content : entry=-1210

SET NAMES 'latin1';
