-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE locales_item SET name_loc8='Tomb Rot',description_loc8='Used by rogues to brew poison.' WHERE entry=2929; /* name: Tomb Rot */ .* description: Used by rogues to brew poison. */
UPDATE locales_item SET name_loc8='Torment Vine',description_loc8='Used by rogues to brew poison.' WHERE entry=2932; /* name: Torment Vine */ .* description: Used by rogues to brew poison. */
UPDATE locales_item SET description_loc8='The initials are faded and unreadable.' WHERE entry=3985; /* description: The initials are faded and unreadable. */
UPDATE locales_item SET description_loc8='Teaches Ritual of Doom.' WHERE entry=4213; /* description: Teaches Ritual of Doom. */
UPDATE locales_item SET name_loc8='Harness: Blue Ram',description_loc8='Teaches you how to summon this mount.' WHERE entry=5875; /* name: Harness: Blue Ram */ .* description: Teaches you how to summon this mount. */
UPDATE locales_item SET name_loc8='Horn of the Skeletal Mount',description_loc8='Teaches you how to summon this mount.' WHERE entry=8583; /* name: Horn of the Skeletal Mount */ .* description: Teaches you how to summon this mount. */
UPDATE locales_item SET name_loc8='Old Whistle of the Obsidian Raptor',description_loc8='Teaches you how to summon this mount.' WHERE entry=8590; /* name: Old Whistle of the Obsidian Raptor */ .* description: Teaches you how to summon this mount. */
UPDATE locales_item SET name_loc8='Reins of the Leopard',description_loc8='Teaches you how to summon this mount.' WHERE entry=8633; /* name: Reins of the Leopard */ .* description: Teaches you how to summon this mount. */
UPDATE locales_item SET description_loc8='It doesn\'t appear to work anymore.  Might as well sell it for scrap.' WHERE entry=9173; /* description: It doesn\'t appear to work anymore.  Might as well sell it for scrap. */
UPDATE locales_item SET description_loc8='An ancient, brittle horn.' WHERE entry=10000; /* description: An ancient, brittle horn. */
UPDATE locales_item SET description_loc8='Teaches you how to make a Mighty Troll\'s Blood Elixir.' WHERE entry=20014; /* description: Teaches you how to make a Mighty Troll\'s Blood Elixir. */
UPDATE locales_item SET description_loc8='Only ONE May Rise... (and consequently, only ONE may loot this head)' WHERE entry=20383; /* description: Only ONE May Rise... (and consequently, only ONE may loot this head) */
UPDATE locales_item SET description_loc8='Someone has been holding onto this for a VERY long time.' WHERE entry=22520; /* description: Someone has been holding onto this for a VERY long time. */
UPDATE locales_item SET description_loc8='They look heavily worn, yet still remain razor sharp.' WHERE entry=23687; /* description: They look heavily worn, yet still remain razor sharp. */
UPDATE locales_item SET description_loc8='Bears the mark of the Shattered Hand.' WHERE entry=23881; /* description: Bears the mark of the Shattered Hand. */
UPDATE locales_item SET description_loc8='It smells of death and fear.' WHERE entry=23886; /* description: It smells of death and fear. */
UPDATE locales_item SET description_loc8='His eyes are full of hatred.' WHERE entry=23901; /* description: His eyes are full of hatred. */
UPDATE locales_item SET description_loc8='Softer than any material found on Azeroth.' WHERE entry=28490; /* description: Softer than any material found on Azeroth. */
UPDATE locales_item SET description_loc8='Required by jewelcrafters to transmute mercurial adamantite.' WHERE entry=31080; /* description: Required by jewelcrafters to transmute mercurial adamantite. */
UPDATE locales_item SET description_loc8='Wearing this would be a bad idea, as it would severely hinder your vision.' WHERE entry=31529; /* description: Wearing this would be a bad idea, as it would severely hinder your vision. */
UPDATE locales_item SET description_loc8='Cut cleanly off at the shoulders.' WHERE entry=31706; /* description: Cut cleanly off at the shoulders. */
UPDATE locales_item SET description_loc8='Teaches you how to permanently enchant a cloak to increase defense rating by 12.  Requires a level 35 or higher item.' WHERE entry=35756; /* description: Teaches you how to permanently enchant a cloak to increase defense rating by 12.  Requires a level 35 or higher item. */
UPDATE locales_item SET name_loc8='Solid Sky Sapphire (Unused)',description_loc8='Matches a Blue Socket.' WHERE entry=37430; /* name: Solid Sky Sapphire (Unused) */ .* description: Matches a Blue Socket. */
UPDATE locales_item SET description_loc8='A second test token for the Currency Token system' WHERE entry=37742; /* description: A second test token for the Currency Token system */
UPDATE locales_item SET description_loc8='A weak alcohol, but a technological triumph in brewing technology.' WHERE entry=37906; /* description: A weak alcohol, but a technological triumph in brewing technology. */
UPDATE locales_item SET description_loc8='Speed scales to riding skill.' WHERE entry=40775; /* description: Speed scales to riding skill. */
UPDATE locales_item SET description_loc8='Teaches you how to cook a Gigantic Feast. ' WHERE entry=43505; /* description: Teaches you how to cook a Gigantic Feast. */
UPDATE locales_item SET description_loc8='Teaches you how to cook a Small Feast' WHERE entry=43506; /* description: Teaches you how to cook a Small Feast */
UPDATE locales_item SET description_loc8='Gives the Tailor an increased chance to find cloth on Northrend humanoids.' WHERE entry=43876; /* description: Gives the Tailor an increased chance to find cloth on Northrend humanoids. */
UPDATE locales_item SET name_loc8='Pattern: Fur Lining - Nature Resist ',description_loc8='Teaches you how to make Fur Lining - Nature Resist.' WHERE entry=44562; /* name: Pattern: Fur Lining - Nature Resist */ .* description: Teaches you how to make Fur Lining - Nature Resist. */
UPDATE locales_item SET description_loc8='Teaches you how to make Fur Lining - Arcane Resist.' WHERE entry=44563; /* description: Teaches you how to make Fur Lining - Arcane Resist. */
UPDATE locales_item SET description_loc8='Teaches you how to permanently enchant gloves to increase fishing skill by 5.' WHERE entry=50406; /* description: Teaches you how to permanently enchant gloves to increase fishing skill by 5. */
UPDATE locales_item SET description_loc8='A lament for the days forever lost to the Banshee Queen' WHERE entry=52253; /* description: A lament for the days forever lost to the Banshee Queen */

SET NAMES 'latin1';
