-- File generated by Mangos Online Translation Editor (MOTE) v2.06
SET NAMES 'utf8';
UPDATE `trans_words`SET `content_loc8`='Hey there, $N. How can I help you?' WHERE `word_id`=192037; -- locales_npc_text - Text0_1 : entry=2
UPDATE `trans_words`SET `content_loc8`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text0_1 : entry=354
UPDATE `trans_words`SET `content_loc8`='Well, if it isn\'t a young, bristling $C, no doubt drawn here by talk of my exploits in fields of battle!$B$BNo time for stories now, for there are great, important deeds that need doing!  So if you\'re looking for glory, then luck shines on you today...' WHERE `word_id`=197875; -- locales_npc_text - Text0_1 : entry=1244
UPDATE `trans_words`SET `content_loc8`='You have truly accelled in your knowledge of enchanting. There is much more to learn, if you are willing. Speak to Taladan, in the Craftsmen\'s Terrace in Darnassus.' WHERE `word_id`=193746; -- locales_npc_text - Text0_1 : entry=5191
UPDATE `trans_words`SET `content_loc8`='You have nearly reached the pinnacle of your training. To become the greatest enchanter you can possibly be, you have one more instructor to seek out. Her name is Annora, and you may find her in Uldaman.' WHERE `word_id`=193793; -- locales_npc_text - Text0_1 : entry=5244
UPDATE `trans_words`SET `content_loc8`='You are eager, that is good. However, you are not yet ready to train with the likes of me.' WHERE `word_id`=193794; -- locales_npc_text - Text0_1 : entry=5246
UPDATE `trans_words`SET `content_loc8`='Your education is nearly complete. One final task is all that stands between you and the culmination of all your efforts.' WHERE `word_id`=193801; -- locales_npc_text - Text0_1 : entry=5255
UPDATE `trans_words`SET `content_loc8`='You have worked your way up, time to see the boss. Go to Josef and tell him you are ready.' WHERE `word_id`=193974; -- locales_npc_text - Text0_1 : entry=5557
UPDATE `trans_words`SET `content_loc8`='Crystal Restore is a difficult item to acquire, if you plan on finding it yourself.$B$BI believe that it comes from Un\'Goro Crater, so you\'d best head there. However, you might be able to find someone that is willing to part with their own supply...' WHERE `word_id`=194032; -- locales_npc_text - Text0_1 : entry=5797
UPDATE `trans_words`SET `content_loc8`='The Stormpike Guard is in need of your assistance in the fight against the Frostwolf Clan, $N. Speak to Brogun Stoneshield on the Warrior\'s Terrace and he will help you find your way to Alterac Valley.' WHERE `word_id`=194630; -- locales_npc_text - Text1_1 : entry=7496
UPDATE `trans_words`SET `content_loc8`='The Silverwing Sentinels can use all the help they can get in their fight against the Warsong Outriders. $N, go to Stormwind Keep and speak with Elfarran if you wish to assist them.' WHERE `word_id`=194638; -- locales_npc_text - Text1_0 : entry=7501
UPDATE `trans_words`SET `content_loc8`='There is one that I know of here in Thunder Bluff that can aid you in your journey to Alterac Valley. On the Hunter Rise look for Taim Ragetotem. May you find what you are looking for $N.' WHERE `word_id`=194644; -- locales_npc_text - Text1_0 : entry=7505
UPDATE `trans_words`SET `content_loc8`='<Tears stream down Greatmother Geyahs face.>$B$BI... I... Durotan survived to have a child? The child Draka told me of before they left... It was their greatest fear... To raise a child in this world. On the other side of that gate was their only hope. I dared not tell Durotan, but secretly, I begged the spirits to watch over them - to protect their child and to give them strength.$B$BI... I must see my grandchild. I must see him. Please, I am too weak. You must tell him. Before I leave this world...' WHERE `word_id`=278222; -- locales_npc_text - Text0_1 : entry=9825
UPDATE `trans_words`SET `content_loc8`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text0_1 : entry=10872
UPDATE `trans_words`SET `content_loc8`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text0_1 : entry=11459
UPDATE `trans_words`SET `content_loc8`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text0_1 : entry=11584
UPDATE `trans_words`SET `content_loc8`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text0_1 : entry=11907
UPDATE `trans_words`SET `content_loc8`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text0_1 : entry=13481
UPDATE `trans_words`SET `content_loc8`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text0_1 : entry=14170
UPDATE `trans_words`SET `content_loc8`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text3_0 : entry=14536
UPDATE `trans_words`SET `content_loc8`='UDB Missing US text' WHERE `word_id`=197021; -- locales_npc_text - Text5_0 : entry=14536
UPDATE `trans_words`SET `content_loc8`='Iam Here, Commander' WHERE `word_id`=196931; -- locales_npc_text - Text0_1 : entry=20551
UPDATE `trans_words`SET `content_loc8`='Weve located the mark, commander. Ya-six and i have been seperated. Requesting backup.' WHERE `word_id`=196932; -- locales_npc_text - Text1_0 : entry=20551
UPDATE `trans_words`SET `content_loc8`='Arxes! Send help! Im pinned down in the mines, I...Im not sure where iam exactly but i had the presence of mind to drop tracers on the gro8und behind me' WHERE `word_id`=196933; -- locales_npc_text - Text1_1 : entry=20551
UPDATE `trans_words`SET `content_loc8`='Copy, Status report, Soldier.' WHERE `word_id`=196936; -- locales_npc_text - Text0_1 : entry=20564
UPDATE `trans_words`SET `content_loc8`='Copy that, Araxes. Backup is on the way. Hold your position. I repeat, Hold your Position' WHERE `word_id`=196937; -- locales_npc_text - Text1_0 : entry=20564

SET NAMES 'latin1';
