-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc2`='Ah, I see it now in your mind. This is the work of one of my former students... Mehlar Dawnblade. It is sad to know that his heart has turned so dark.' WHERE `word_id` = 7810; -- db_script_string - content : entry=2000000320
UPDATE `trans_words` SET `content_loc2`='Aman dissipates before your eyes.' WHERE `word_id` = 7998; -- db_script_string - content : entry=2000005361
UPDATE `trans_words` SET `content_loc2`='An Avatar of Terokk! To arms!' WHERE `word_id` = 7599; -- db_script_string - content : entry=2000000025
UPDATE `trans_words` SET `content_loc2`='Anaya\'s soft voice trails away into the mists. "Know that I love you always..."' WHERE `word_id` = 7428; -- db_script_string - content : entry=2000005344
UPDATE `trans_words` SET `content_loc2`='And even more!' WHERE `word_id` = 7598; -- db_script_string - content : entry=2000000024
UPDATE `trans_words` SET `content_loc2`='And who do we have here?  No doubt th... crzzzk ...ade this communication possible?  I give you greetings fro... psshzzzk... Azure Watch.' WHERE `word_id` = 268219; -- db_script_string - content : entry=2000005839
UPDATE `trans_words` SET `content_loc2`='And... I we do not?' WHERE `word_id` = 8052; -- db_script_string - content : entry=2000005467
UPDATE `trans_words` SET `content_loc2`='Back to the topic... we should focus our attention on these manaforges. We need to learn what the enemy is doing with them and why.' WHERE `word_id` = 7971; -- db_script_string - content : entry=2000005276
UPDATE `trans_words` SET `content_loc2`='Bah! $N, this foot won\'t budge!' WHERE `word_id` = 7704; -- db_script_string - content : entry=2000000133
UPDATE `trans_words` SET `content_loc2`='Bogling rises from the soil!' WHERE `word_id` = 7695; -- db_script_string - content : entry=2000000089
UPDATE `trans_words` SET `content_loc2`='Borgrim, this is no time for drinking. We just got here. We need to get settled in.' WHERE `word_id` = 8215; -- db_script_string - content : entry=2000005679
UPDATE `trans_words` SET `content_loc2`='BY THE LIGHT OF ELUNE! Eredar! Cursed demons, what have you to me? I have not come alone, we will fight you as we have in the past! I...' WHERE `word_id` = 7636; -- db_script_string - content : entry=2000000660
UPDATE `trans_words` SET `content_loc2`='Champion Vranesh arches a sculpted brow at the guards, a disapproving scowl on his face.' WHERE `word_id` = 8322; -- db_script_string - content : entry=2000005822
UPDATE `trans_words` SET `content_loc2`='Champion Vranesh glances from guard to guard.' WHERE `word_id` = 8323; -- db_script_string - content : entry=2000005823
UPDATE `trans_words` SET `content_loc2`='Champion Vranesh inclines his head slightly to the pair of guardians in greeting.' WHERE `word_id` = 8325; -- db_script_string - content : entry=2000005825
UPDATE `trans_words` SET `content_loc2`='Champion Vranesh surveys the small ranger practice ground with a condescending smirk.' WHERE `word_id` = 8324; -- db_script_string - content : entry=2000005824
UPDATE `trans_words` SET `content_loc2`='Come to my lair, whelp! Come to me and pay for your insolecne!' WHERE `word_id` = 8010; -- db_script_string - content : entry=2000005406
UPDATE `trans_words` SET `content_loc2`='Damnit. How are we ever going to make it through their security measures?' WHERE `word_id` = 8003; -- db_script_string - content : entry=2000005399
UPDATE `trans_words` SET `content_loc2`='Denalan hurries to his planter.' WHERE `word_id` = 7696; -- db_script_string - content : entry=2000000093
UPDATE `trans_words` SET `content_loc2`='Denalan plants fruit seeds.' WHERE `word_id` = 7694; -- db_script_string - content : entry=2000000088
UPDATE `trans_words` SET `content_loc2`='Denalan removes the seeds from the Glowing Fruit...' WHERE `word_id` = 7692; -- db_script_string - content : entry=2000000086
UPDATE `trans_words` SET `content_loc2`='Derived from cutting edge Shattered Hand Offensive military technology, it blasts away stubborn stains with ease!' WHERE `word_id` = 7532; -- db_script_string - content : entry=2000005207
UPDATE `trans_words` SET `content_loc2`='Did you find something fun to chase around, Twinkle?' WHERE `word_id` = 7878; -- db_script_string - content : entry=2000000406
UPDATE `trans_words` SET `content_loc2`='Drink this, you blue brute! Disobey me and I promise you a slow, painful death!' WHERE `word_id` = 7770; -- db_script_string - content : entry=2000000256
UPDATE `trans_words` SET `content_loc2`='Even you must admit that your information from defectors is outdated and unreliable. Let us make calculated attacks on these manaforges and gather what information we can.' WHERE `word_id` = 7974; -- db_script_string - content : entry=2000005279
UPDATE `trans_words` SET `content_loc2`='Fear not! All fortunes can be discerned for those who know the way.' WHERE `word_id` = 7535; -- db_script_string - content : entry=2000005213
UPDATE `trans_words` SET `content_loc2`='Freedom at last! I must return to Warsong at once!' WHERE `word_id` = 7897; -- db_script_string - content : entry=2000000560
UPDATE `trans_words` SET `content_loc2`='Glad to see you\'re doing so well, Harlan. And I hope to see you again soon' WHERE `word_id` = 7563; -- db_script_string - content : entry=2000000149
UPDATE `trans_words` SET `content_loc2`='Glory to the Sun K-- ah.... Silvermoon!' WHERE `word_id` = 8327; -- db_script_string - content : entry=2000005827
UPDATE `trans_words` SET `content_loc2`='Greatmother Hawkwind gestures to the pitcher of water sitting on the edge of the well.' WHERE `word_id` = 7687; -- db_script_string - content : entry=2000000027
UPDATE `trans_words` SET `content_loc2`='Havenshire is lost.' WHERE `word_id` = 7884; -- db_script_string - content : entry=2000000412
UPDATE `trans_words` SET `content_loc2`='Hey, harbringer, how\'s that research coming along? There might be an Ultra-Kinetic Waffle Iron in it for you if you\'re prompt with the results!' WHERE `word_id` = 6158; -- db_script_string - content : entry=2000005201
UPDATE `trans_words` SET `content_loc2`='Hey, you there. Want some candy?' WHERE `word_id` = 7492; -- db_script_string - content : entry=2000005052
UPDATE `trans_words` SET `content_loc2`='Hmm... the readings on the gravimeteric distortions seem to have stabalized. We did it!' WHERE `word_id` = 7955; -- db_script_string - content : entry=2000005260
UPDATE `trans_words` SET `content_loc2`='Hold your tongue, knave! Do not dare use that tone with a priestess of the Light!' WHERE `word_id` = 7968; -- db_script_string - content : entry=2000005273
UPDATE `trans_words` SET `content_loc2`='How dare you take my eye! I will crush your soul and feed it to my blind and wimpering imps!' WHERE `word_id` = 8009; -- db_script_string - content : entry=2000005405
UPDATE `trans_words` SET `content_loc2`='How dare you trifle with my playthings!' WHERE `word_id` = 6543; -- db_script_string - content : entry=2000005441
UPDATE `trans_words` SET `content_loc2`='I can get back to Stronghold on my own, I think. Now that you bought me some time, I should be able to stealth out of here. Who ever you are... thank you. May Elune bless you always!' WHERE `word_id` = 7894; -- db_script_string - content : entry=2000000520
UPDATE `trans_words` SET `content_loc2`='I can\'t belive you imbeciles went to school for this! Does anybody here know what they\'re doing?' WHERE `word_id` = 7976; -- db_script_string - content : entry=2000005281
UPDATE `trans_words` SET `content_loc2`='I FEEL DEATH ALONGSIDE' WHERE `word_id` = 7546; -- db_script_string - content : entry=2000005231
UPDATE `trans_words` SET `content_loc2`='I guess I\'ll go find the athorities. If I\'m lucky they\'ll tell me it\'s the plague and that we\'re all going to die.' WHERE `word_id` = 8190; -- db_script_string - content : entry=2000005622
UPDATE `trans_words` SET `content_loc2`='I have awoken to a nightmare?' WHERE `word_id` = 7851; -- db_script_string - content : entry=2000000367
UPDATE `trans_words` SET `content_loc2`='I have created the totem. You, $N, must cleanse the well.' WHERE `word_id` = 7711; -- db_script_string - content : entry=2000000171
UPDATE `trans_words` SET `content_loc2`='I pity you Forsaken, Your soul is devoid of light.' WHERE `word_id` = 7771; -- db_script_string - content : entry=2000000257
UPDATE `trans_words` SET `content_loc2`='I raise my brew and hope to be rid of the likes of you! Cheers, you no good scoundrel, $N!' WHERE `word_id` = 7690; -- db_script_string - content : entry=2000000084
UPDATE `trans_words` SET `content_loc2`='I thank you, $N. And my brother thanks you.' WHERE `word_id` = 8280; -- db_script_string - content : entry=2000005776
UPDATE `trans_words` SET `content_loc2`='I think, I\'ll be able to get to Brackenwall. The cargo they carried to the top of the towers. Be careful!' WHERE `word_id` = 8726; -- db_script_string - content : entry=2000000486
UPDATE `trans_words` SET `content_loc2`='I thought this was going to be our chance to get away from it all? Our vacation?' WHERE `word_id` = 8216; -- db_script_string - content : entry=2000005680
UPDATE `trans_words` SET `content_loc2`='I WICKED OGR' WHERE `word_id` = 7545; -- db_script_string - content : entry=2000005230
UPDATE `trans_words` SET `content_loc2`='I WILL DESTROY ALL' WHERE `word_id` = 7483; -- db_script_string - content : entry=2000005043
UPDATE `trans_words` SET `content_loc2`='I will do my best to take care of the children, Grandmother.' WHERE `word_id` = 7481; -- db_script_string - content : entry=2000005041
UPDATE `trans_words` SET `content_loc2`='I\'m going to train you to help $N with very important task. After that, I promose you\'ll be free to return home.' WHERE `word_id` = 8211; -- db_script_string - content : entry=2000005673
UPDATE `trans_words` SET `content_loc2`='I\'m listening..' WHERE `word_id` = 8030; -- db_script_string - content : entry=2000005437
UPDATE `trans_words` SET `content_loc2`='I\'m surrounded by idiots.' WHERE `word_id` = 7969; -- db_script_string - content : entry=2000005274
UPDATE `trans_words` SET `content_loc2`='I\'ve rigged a few control consoles down the slope. Get one quickly and take control of the fel reaver! You\'ll only have a limited amount of time.' WHERE `word_id` = 8049; -- db_script_string - content : entry=2000005459
UPDATE `trans_words` SET `content_loc2`='Is it done yet? What is talking so damned long?' WHERE `word_id` = 7977; -- db_script_string - content : entry=2000005282
UPDATE `trans_words` SET `content_loc2`='Iskalder? You fool! Have you no idea who that is? He\'s only the greatest vrykul warrior who ever lived!' WHERE `word_id` = 6921; -- db_script_string - content : entry=2000000294
UPDATE `trans_words` SET `content_loc2`='It is over, your search is done! Let fate choose now, the righteous one.' WHERE `word_id` = 1370; -- db_script_string - content : entry=2000005643
UPDATE `trans_words` SET `content_loc2`='It is time to force your final challenge young warriors! Prepare for your hardest fight yet.' WHERE `word_id` = 7559; -- db_script_string - content : entry=2000005075
UPDATE `trans_words` SET `content_loc2`='It\'s all here... how the raven\'s followers captured and subdued the sprints of rivals, trapping them forever within stone statues! The tablet even mentions the raven god\'s name -- Anzu. I\'d thought it was lost to history!' WHERE `word_id` = 7581; -- db_script_string - content : entry=2000000072
UPDATE `trans_words` SET `content_loc2`='It\'s good that I managed to make copies of the Felsworn Gas Mask...' WHERE `word_id` = 7804; -- db_script_string - content : entry=2000000312
UPDATE `trans_words` SET `content_loc2`='Jeffrey Kaplan! Tom Chilton! Rob Pardo!' WHERE `word_id` = 268222; -- db_script_string - content : entry=2000000490
UPDATE `trans_words` SET `content_loc2`='Justin Thavirat! Roman Kenney! Our entire awesome art and animation team!' WHERE `word_id` = 268223; -- db_script_string - content : entry=2000000491
UPDATE `trans_words` SET `content_loc2`='Keep up the good work. Do well and you will be rewarded by the master.' WHERE `word_id` = 8055; -- db_script_string - content : entry=2000005470
UPDATE `trans_words` SET `content_loc2`='Kevin Jordan and Jonathan LeCraft!' WHERE `word_id` = 268224; -- db_script_string - content : entry=2000000492
UPDATE `trans_words` SET `content_loc2`='Let us hold or discussion in a more... private place. Follow me, $N.' WHERE `word_id` = 8330; -- db_script_string - content : entry=2000005832
UPDATE `trans_words` SET `content_loc2`='Look out! More are coming!' WHERE `word_id` = 7597; -- db_script_string - content : entry=2000000023
UPDATE `trans_words` SET `content_loc2`='Look! Minions of Terokk are approaching!' WHERE `word_id` = 7596; -- db_script_string - content : entry=2000000022
UPDATE `trans_words` SET `content_loc2`='My legs feels much better now, the remedy must be working. If you will excuse me, I must go report to my superiors about what has transpired here.' WHERE `word_id` = 7246; -- db_script_string - content : entry=2000005630
UPDATE `trans_words` SET `content_loc2`='My the light bless you.' WHERE `word_id` = 8214; -- db_script_string - content : entry=2000005676
UPDATE `trans_words` SET `content_loc2`='New posting up! Adventurers and heroes, gather round the bulletin board!' WHERE `word_id` = 7482; -- db_script_string - content : entry=2000005042
UPDATE `trans_words` SET `content_loc2`='NOBODY WILL GET THROUGH ME' WHERE `word_id` = 7548; -- db_script_string - content : entry=2000005235
UPDATE `trans_words` SET `content_loc2`='Not a challenge at all it seems. Let us see how hou handle your second test. Lysta, bring forth the minions of the Lich King.' WHERE `word_id` = 7561; -- db_script_string - content : entry=2000005073
UPDATE `trans_words` SET `content_loc2`='Now get out of my way, it\'s time to send the Burning Legion back to the nether!' WHERE `word_id` = 7504; -- db_script_string - content : entry=2000005413
UPDATE `trans_words` SET `content_loc2`='Now we call forth the the arcane acolyte.' WHERE `word_id` = 8253; -- db_script_string - content : entry=2000005720
UPDATE `trans_words` SET `content_loc2`='Of Course Im talking to myself. Only way to get a decent conversation in this city.' WHERE `word_id` = 7519; -- db_script_string - content : entry=2000005105
UPDATE `trans_words` SET `content_loc2`='Of course, Brann: We will have the shield down momentarily.' WHERE `word_id` = 8142; -- db_script_string - content : entry=2000005573
UPDATE `trans_words` SET `content_loc2`='Oh sweet, delicious, spotted eggs - you will be mine...' WHERE `word_id` = 7573; -- db_script_string - content : entry=2000005093
UPDATE `trans_words` SET `content_loc2`='Ok, let\'s get started!' WHERE `word_id` = 7422; -- db_script_string - content : entry=2000000103
UPDATE `trans_words` SET `content_loc2`='Okay! Let\'s move out. Get into your machines; I\'ll speak to you from here via the radio.' WHERE `word_id` = 8143; -- db_script_string - content : entry=2000005574
UPDATE `trans_words` SET `content_loc2`='Pentarus, you heard the man. Have your mages release the shield and let these brave souls through!' WHERE `word_id` = 8141; -- db_script_string - content : entry=2000005572
UPDATE `trans_words` SET `content_loc2`='Perry Gatner! What an act! The cantina is open all night long, so please, stay and enjoy yourselves!' WHERE `word_id` = 7550; -- db_script_string - content : entry=2000005301
UPDATE `trans_words` SET `content_loc2`='Please! I must feed on something soon... A mana crystal... a shard... anything! The pain is unbearable!' WHERE `word_id` = 7476; -- db_script_string - content : entry=2000005036
UPDATE `trans_words` SET `content_loc2`='Prizes! Get your prizes right here! Get over here and turn in your Darkmoon Faire Prize Tickets for valuable prizes!' WHERE `word_id` = 7471; -- db_script_string - content : entry=2000005025
UPDATE `trans_words` SET `content_loc2`='Release me immediatley or face my wrath!' WHERE `word_id` = 8059; -- db_script_string - content : entry=2000005474
UPDATE `trans_words` SET `content_loc2`='Rest now, Adaris. You need to recover your strength.' WHERE `word_id` = 7728; -- db_script_string - content : entry=2000000188
UPDATE `trans_words` SET `content_loc2`='Return to him. Return to Mehlor and tell him that I forgive him and that I understand why he believes what he does.' WHERE `word_id` = 7811; -- db_script_string - content : entry=2000000321
UPDATE `trans_words` SET `content_loc2`='Right. We just busted our tails to haul all of this stuff up here, and you want us to work more?' WHERE `word_id` = 7494; -- db_script_string - content : entry=2000005056
UPDATE `trans_words` SET `content_loc2`='Sarath fades into the mist...' WHERE `word_id` = 7427; -- db_script_string - content : entry=2000000053
UPDATE `trans_words` SET `content_loc2`='Shane Dabiri, Lee, Alex T., Rob F., J. A. B., A. Mayberry!' WHERE `word_id` = 268221; -- db_script_string - content : entry=2000000489
UPDATE `trans_words` SET `content_loc2`='Sniff... That\'s the spirit soldier... I only wish we had more soldiers like you in this army. Now go out there and give \'em hell!' WHERE `word_id` = 7503; -- db_script_string - content : entry=2000005414
UPDATE `trans_words` SET `content_loc2`='Speak to the commander at your post, lad, and persuade him to abandon Vor\'takh\'s foolish plan.' WHERE `word_id` = 8609; -- db_script_string - content : entry=2000005850
UPDATE `trans_words` SET `content_loc2`='Spirits of Water, I give you praise, and I beg of you a favour. You have heard $N\'s pleas, and I trust his inent is noble. Please, will you aid us?' WHERE `word_id` = 7572; -- db_script_string - content : entry=2000000057
UPDATE `trans_words` SET `content_loc2`='Spirits watch for you, $R.' WHERE `word_id` = 8105; -- db_script_string - content : entry=2000005523
UPDATE `trans_words` SET `content_loc2`='Strange. Very strange...' WHERE `word_id` = 7700; -- db_script_string - content : entry=2000000099
UPDATE `trans_words` SET `content_loc2`='Thank you for freeing us, mortals. Beware, the Blue Flight is alerted to your presence. Even now, Malygos sends Varos Cloudstrider and his ring guardians to defend the Oculus. You will need our help to stand a chance.' WHERE `word_id` = 8107; -- db_script_string - content : entry=2000005525
UPDATE `trans_words` SET `content_loc2`='Thank you. I thought I was going to die.' WHERE `word_id` = 7625; -- db_script_string - content : entry=2000005545
UPDATE `trans_words` SET `content_loc2`='The bonelashers of the wastes are no laughing matter. I hear they carry diseases!' WHERE `word_id` = 8224; -- db_script_string - content : entry=2000005688
UPDATE `trans_words` SET `content_loc2`='The Darkmoon Faire is the greatest event in all of Outland' WHERE `word_id` = 7540; -- db_script_string - content : entry=2000005221
UPDATE `trans_words` SET `content_loc2`='The invisibility liquer is ready for you, $N.' WHERE `word_id` = 7689; -- db_script_string - content : entry=2000000081
UPDATE `trans_words` SET `content_loc2`='The Lorehammer ist reacting. This must be from Stormhoof\'s time.' WHERE `word_id` = 7787; -- db_script_string - content : entry=2000000274
UPDATE `trans_words` SET `content_loc2`='The mixture! It moves!' WHERE `word_id` = 7747; -- db_script_string - content : entry=2000000232
UPDATE `trans_words` SET `content_loc2`='The orcs in my citadel will drink your blood and dovour you!' WHERE `word_id` = 8034; -- db_script_string - content : entry=2000005442
UPDATE `trans_words` SET `content_loc2`='There\'s something else here, too. After a discription of a bloody battle and the downfall of the raven, there\'s a prophecy. Anzu will haunt the dreams of his enemies, twisting them to affect a return to this world...' WHERE `word_id` = 7582; -- db_script_string - content : entry=2000000073
UPDATE `trans_words` SET `content_loc2`='Think of your younglings, Gul\'dan! You will destroy us all!' WHERE `word_id` = 8044; -- db_script_string - content : entry=2000005454
UPDATE `trans_words` SET `content_loc2`='This is great news! Your efforts have indeed saved us, $N!' WHERE `word_id` = 8633; -- db_script_string - content : entry=2000005841
UPDATE `trans_words` SET `content_loc2`='This is the last time that I buy second-hand equipment from ethereal' WHERE `word_id` = 7466; -- db_script_string - content : entry=2000005067
UPDATE `trans_words` SET `content_loc2`='This poster has a bounty on bonelashers. You think I should do that?' WHERE `word_id` = 8221; -- db_script_string - content : entry=2000005685
UPDATE `trans_words` SET `content_loc2`='Tickets! Redeem your Darkmoon Faire Prize Tickets here! Wondrous and exotic prizes are waiting for you!' WHERE `word_id` = 7534; -- db_script_string - content : entry=2000005212
UPDATE `trans_words` SET `content_loc2`='Tonga Runetotem inspects the snapjaw shells...' WHERE `word_id` = 7698; -- db_script_string - content : entry=2000000097
UPDATE `trans_words` SET `content_loc2`='Turning to face Tuluun, the Draenei Artificer sneers contemptuously.' WHERE `word_id` = 7642; -- db_script_string - content : entry=2000000662
UPDATE `trans_words` SET `content_loc2`='US ALREADY ALL ANYMORE AND ANYMORE' WHERE `word_id` = 7484; -- db_script_string - content : entry=2000005044
UPDATE `trans_words` SET `content_loc2`='Waste no time, fool! Use our power to kill those what stand in our way! Destroy Krasius before you are subdued!' WHERE `word_id` = 8058; -- db_script_string - content : entry=2000005473
UPDATE `trans_words` SET `content_loc2`='We will act when we know what we need, old friend. The druids have proven wise and capable of making their own decisions.' WHERE `word_id` = 7942; -- db_script_string - content : entry=2000005247
UPDATE `trans_words` SET `content_loc2`='We won. Dimensius no more. Report this proffesor Dabiri.' WHERE `word_id` = 8285; -- db_script_string - content : entry=2000005784
UPDATE `trans_words` SET `content_loc2`='Welcome one and all to the Darkmoon Faire, the greatest event in all the worlds! We have it all... delicious food, strong drinks, exotic artifacts, fortunes read, amazing prizes and excitement without end! Don\'t forget to turn in your Darkmoon Faire Prize Tickets to Gelvas Grimegate! All it takes is five or more and you\'re on your way to the most wondrous prizes in all of Outland. Everybody is a winner' WHERE `word_id` = 7475; -- db_script_string - content : entry=2000005034
UPDATE `trans_words` SET `content_loc2`='What up son! Wait....is anyone there?' WHERE `word_id` = 7931; -- db_script_string - content : entry=2000005055
UPDATE `trans_words` SET `content_loc2`='Where do you think you are going soldier? Those are fatal wounds you\'ve got there. Now, get back in tent and let the nurse treat you!' WHERE `word_id` = 7505; -- db_script_string - content : entry=2000005412
UPDATE `trans_words` SET `content_loc2`='Who... who are you? Who.. what am I?' WHERE `word_id` = 7835; -- db_script_string - content : entry=2000000351
UPDATE `trans_words` SET `content_loc2`='Who? The Tauren Chieftains! What? A live performance. Where? The World\'s End Tavern! When? The top of the hour! BE THERE!' WHERE `word_id` = 7439; -- db_script_string - content : entry=2000005305
UPDATE `trans_words` SET `content_loc2`='Why do you do this? Did I somehow wrong you in life?' WHERE `word_id` = 7809; -- db_script_string - content : entry=2000000319
UPDATE `trans_words` SET `content_loc2`='Wouldn\'t you like to bring those days back? I have some friends who know just the way to do that.' WHERE `word_id` = 7469; -- db_script_string - content : entry=2000005022
UPDATE `trans_words` SET `content_loc2`='Yer wearin down, princess, I can sense it!' WHERE `word_id` = 7530; -- db_script_string - content : entry=2000005203
UPDATE `trans_words` SET `content_loc2`='Yes, he\'s second-in-command of the wyrmcult at the Blackwing Coven to the west.' WHERE `word_id` = 7726; -- db_script_string - content : entry=2000000186
UPDATE `trans_words` SET `content_loc2`='You need to do what? All this science. I don\'t understand... Look, this is just my job, five days a week.' WHERE `word_id` = 7945; -- db_script_string - content : entry=2000005250
UPDATE `trans_words` SET `content_loc2`='YOU PRAY SERVANTS MY' WHERE `word_id` = 7539; -- db_script_string - content : entry=2000005220
UPDATE `trans_words` SET `content_loc2`='You want to go do the bounty off of this wanted poster after this shift is over?' WHERE `word_id` = 7487; -- db_script_string - content : entry=2000005047
UPDATE `trans_words` SET `content_loc2`='You will not harm the boy, Mor\'ghor! Quickly, $N, climb on my back!' WHERE `word_id` = 7996; -- db_script_string - content : entry=2000005355
UPDATE `trans_words` SET `content_loc2`='Your body is mine! Our fates are forever intertwined!' WHERE `word_id` = 7595; -- db_script_string - content : entry=2000000031
UPDATE `trans_words` SET `content_loc2`='Your time is night...' WHERE `word_id` = 1379; -- db_script_string - content : entry=2000005640

SET NAMES 'latin1';
