-- File generated by Mangos Online Translation Editor (MOTE) v2.05
SET NAMES 'utf8';
UPDATE `locales_gossip_menu_option` SET `option_text_loc2`='Purchase a Dual Talent Specialization.',`box_text_loc2`='Are you sure you wish to purchase a Dual Talent Specialization?' WHERE `menu_id`=10371 AND `id`=0;

SET NAMES 'latin1';
