-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE trans_words SET content_loc4='[PH] SD3 unknown text' WHERE word_id = 127695;
UPDATE trans_words SET content_loc4='Taruk send me to collect what you owe.' WHERE word_id = 127745;
UPDATE trans_words SET content_loc4='I am ready to travel to you village now.' WHERE word_id = 127747;
UPDATE trans_words SET content_loc4='<Check for pulse...>' WHERE word_id = 127748;
UPDATE trans_words SET content_loc4='I\'m ready - let\'s get out of here.' WHERE word_id = 127749;
UPDATE trans_words SET content_loc4='Go on, you\'re free. Get out of here!' WHERE word_id = 127750;
UPDATE trans_words SET content_loc4='You challenged us and we have come. Where is this master you speak of?' WHERE word_id = 127680;
UPDATE trans_words SET content_loc4='Teleport me to the Guardian\'s Library' WHERE word_id = 127704;
UPDATE trans_words SET content_loc4='What phat lewtz you have grandmother?' WHERE word_id = 127752;
UPDATE trans_words SET content_loc4='Control Human Charger' WHERE word_id = 127717;
UPDATE trans_words SET content_loc4='Control Conjured Water Elemental' WHERE word_id = 127718;
UPDATE trans_words SET content_loc4='We\'ll get you out. Taretha. Don\'t worry. I doubt the wizard would wander too far away.' WHERE word_id = 127736;
UPDATE trans_words SET content_loc4='Let\'s move Brann, enough of the history lessons!' WHERE word_id = 127762;
UPDATE trans_words SET content_loc4='Activate the crystals when we get in trouble, right?' WHERE word_id = 127778;
UPDATE trans_words SET content_loc4='Val\'kyr? We\'re ready for them' WHERE word_id = 127791;

SET NAMES 'latin1';
