-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE locales_item SET description_loc4='Engraved with the words \'For years of service: -EVC.\'' WHERE entry=2239; /* description: Engraved with the words \'For years of service: -EVC.\' */
UPDATE locales_item SET name_loc4='Tomb Rot',description_loc4='Used by rogues to brew poison.' WHERE entry=2929; /* name: Tomb Rot */ .* description: Used by rogues to brew poison. */
UPDATE locales_item SET name_loc4='Torment Vine',description_loc4='Used by rogues to brew poison.' WHERE entry=2932; /* name: Torment Vine */ .* description: Used by rogues to brew poison. */
UPDATE locales_item SET name_loc4='Harness: Black Ram',description_loc4='Teaches you how to summon this mount.' WHERE entry=5874; /* name: Harness: Black Ram */ .* description: Teaches you how to summon this mount. */
UPDATE locales_item SET name_loc4='Harness: Blue Ram',description_loc4='Teaches you how to summon this mount.' WHERE entry=5875; /* name: Harness: Blue Ram */ .* description: Teaches you how to summon this mount. */
UPDATE locales_item SET name_loc4='Tiny Copper Key',description_loc4='A reagent for mage spells.' WHERE entry=8147; /* name: Tiny Copper Key */ .* description: A reagent for mage spells. */
UPDATE locales_item SET name_loc4='Horn of the Skeletal Mount',description_loc4='Teaches you how to summon this mount.' WHERE entry=8583; /* name: Horn of the Skeletal Mount */ .* description: Teaches you how to summon this mount. */
UPDATE locales_item SET name_loc4='Old Whistle of the Ivory Raptor',description_loc4='Teaches you how to summon this mount.' WHERE entry=8589; /* name: Old Whistle of the Ivory Raptor */ .* description: Teaches you how to summon this mount. */
UPDATE locales_item SET name_loc4='Old Whistle of the Obsidian Raptor',description_loc4='Teaches you how to summon this mount.' WHERE entry=8590; /* name: Old Whistle of the Obsidian Raptor */ .* description: Teaches you how to summon this mount. */
UPDATE locales_item SET name_loc4='Reins of the Bengal Tiger',description_loc4='Teaches you how to summon this mount.' WHERE entry=8630; /* name: Reins of the Bengal Tiger */ .* description: Teaches you how to summon this mount. */
UPDATE locales_item SET name_loc4='Reins of the Leopard',description_loc4='Teaches you how to summon this mount.' WHERE entry=8633; /* name: Reins of the Leopard */ .* description: Teaches you how to summon this mount. */
UPDATE locales_item SET name_loc4='Kodo Mount',description_loc4='Teaches you how to summon this mount.' WHERE entry=14062; /* name: Kodo Mount */ .* description: Teaches you how to summon this mount. */
UPDATE locales_item SET description_loc4='Teaches you how to make Thorium Shells.' WHERE entry=16051; /* description: Teaches you how to make Thorium Shells. */
UPDATE locales_item SET name_loc4='zzDEPRECATED Warsong Mark of Honor',description_loc4='Proof of winning a battle in Warsong Gulch' WHERE entry=19322; /* name: zzDEPRECATED Warsong Mark of Honor */ .* description: Proof of winning a battle in Warsong Gulch */
UPDATE locales_item SET description_loc4='Only ONE May Rise... (and consequently, only ONE may loot this head)' WHERE entry=20383; /* description: Only ONE May Rise... (and consequently, only ONE may loot this head) */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=22345; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=22395; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=22396; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=23005; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=23199; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=23200; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='They look heavily worn, yet still remain razor sharp.' WHERE entry=23687; /* description: They look heavily worn, yet still remain razor sharp. */
UPDATE locales_item SET description_loc4='Bears the mark of the Shattered Hand.' WHERE entry=23881; /* description: Bears the mark of the Shattered Hand. */
UPDATE locales_item SET description_loc4='It smells of death and fear.' WHERE entry=23886; /* description: It smells of death and fear. */
UPDATE locales_item SET description_loc4='His eyes are full of hatred.' WHERE entry=23901; /* description: His eyes are full of hatred. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=24413; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=25645; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=27544; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Teaches you how to cook a Sporeling Snack.' WHERE entry=27689; /* description: Teaches you how to cook a Sporeling Snack. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=27815; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=27947; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=27984; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=28066; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=28248; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=28357; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Softer than any material found on Azeroth.' WHERE entry=28490; /* description: Softer than any material found on Azeroth. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=28523; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=29389; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=30023; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=31031; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Required by jewelcrafters to transmute mercurial adamantite.' WHERE entry=31080; /* description: Required by jewelcrafters to transmute mercurial adamantite. */
UPDATE locales_item SET description_loc4='Wearing this would be a bad idea, as it would severely hinder your vision.' WHERE entry=31529; /* description: Wearing this would be a bad idea, as it would severely hinder your vision. */
UPDATE locales_item SET description_loc4='Cut cleanly off at the shoulders.' WHERE entry=31706; /* description: Cut cleanly off at the shoulders. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=32330; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=33078; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=33505; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=33506; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=33507; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=33843; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=33939; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=33940; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=33941; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=33951; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=33952; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=33953; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=35104; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=35105; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=35106; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET name_loc4='Solid Sky Sapphire (Unused)',description_loc4='Matches a Blue Socket.' WHERE entry=37430; /* name: Solid Sky Sapphire (Unused) */ .* description: Matches a Blue Socket. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=37575; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Can be targeted by Armor enchantments to store the enchantment for later use.  Only able to absorb enchantments with a level restriction of 35 or lower.' WHERE entry=37602; /* description: Can be targeted by Armor enchantments to store the enchantment for later use.  Only able to absorb enchantments with a level restriction of 35 or lower. */
UPDATE locales_item SET description_loc4='A second test token for the Currency Token system' WHERE entry=37742; /* description: A second test token for the Currency Token system */
UPDATE locales_item SET description_loc4='A weak alcohol, but a technological triumph in brewing technology.' WHERE entry=37906; /* description: A weak alcohol, but a technological triumph in brewing technology. */
UPDATE locales_item SET name_loc4='Thick Goblin Back Protector ',description_loc4='If you like the Back Protector, we highly recommend the matching Front Protector' WHERE entry=38355; /* name: Thick Goblin Back Protector */ .* description: If you like the Back Protector, we highly recommend the matching Front Protector */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=38361; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=38367; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=38368; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Can be targeted by Weapon enchantments to store the enchantment for later use.  Only able to absorb enchantments with no level restrictions.' WHERE entry=39349; /* description: Can be targeted by Weapon enchantments to store the enchantment for later use.  Only able to absorb enchantments with no level restrictions. */
UPDATE locales_item SET description_loc4='Can be targeted by Weapon enchantments to store the enchantment for later use.  Only able to absorb enchantments with a level restriction of 35 or lower.' WHERE entry=39350; /* description: Can be targeted by Weapon enchantments to store the enchantment for later use.  Only able to absorb enchantments with a level restriction of 35 or lower. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=39728; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET name_loc4='Test Dazzling Talasite',description_loc4='Matches a Yellow or Blue Socket.' WHERE entry=40232; /* name: Test Dazzling Talasite */ .* description: Matches a Yellow or Blue Socket. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=40267; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=40322; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=40708; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=40709; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=40710; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Speed scales to riding skill.' WHERE entry=40775; /* description: Speed scales to riding skill. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=42597; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=42598; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=42599; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=42602; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=42603; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=42604; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=42607; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=42608; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=42609; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Can be targeted by Armor enchantments to store the enchantment for later use.  Only able to absorb enchantments with a level restriction of 60 or lower.' WHERE entry=43145; /* description: Can be targeted by Armor enchantments to store the enchantment for later use.  Only able to absorb enchantments with a level restriction of 60 or lower. */
UPDATE locales_item SET description_loc4='Can be targeted by Weapon enchantments to store the enchantment for later use.  Only able to absorb enchantments with a level restriction of 60 or lower.' WHERE entry=43146; /* description: Can be targeted by Weapon enchantments to store the enchantment for later use.  Only able to absorb enchantments with a level restriction of 60 or lower. */
UPDATE locales_item SET name_loc4='Pattern: Fur Lining - Nature Resist ',description_loc4='Teaches you how to make Fur Lining - Nature Resist.' WHERE entry=44562; /* name: Pattern: Fur Lining - Nature Resist */ .* description: Teaches you how to make Fur Lining - Nature Resist. */
UPDATE locales_item SET description_loc4='Teaches you how to make Fur Lining - Arcane Resist.' WHERE entry=44563; /* description: Teaches you how to make Fur Lining - Arcane Resist. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=45114; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=45169; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=45255; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET name_loc4='Warbot Ignition Key',description_loc4='Teaches you how to summon this companion.' WHERE entry=46767; /* name: Warbot Ignition Key */ .* description: Teaches you how to summon this companion. */
UPDATE locales_item SET description_loc4='Tiffany Cartier of Dalaran would be very interested in this fine powder.' WHERE entry=46849; /* description: Tiffany Cartier of Dalaran would be very interested in this fine powder. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=46978; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=47665; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=47666; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=47667; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Teaches you how to inscribe a Glyph of Rapid Rejuvenation.' WHERE entry=50167; /* description: Teaches you how to inscribe a Glyph of Rapid Rejuvenation. */
UPDATE locales_item SET description_loc4='Teaches you how to permanently enchant gloves to increase fishing skill by 5.' WHERE entry=50406; /* description: Teaches you how to permanently enchant gloves to increase fishing skill by 5. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=50458; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=50463; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=50464; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=51501; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=51507; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='Counts as an Air, Earth, Fire, and Water totem.' WHERE entry=51513; /* description: Counts as an Air, Earth, Fire, and Water totem. */
UPDATE locales_item SET description_loc4='May you always bring light into dark places.' WHERE entry=52252; /* description: May you always bring light into dark places. */
UPDATE locales_item SET description_loc4='A lament for the days forever lost to the Banshee Queen' WHERE entry=52253; /* description: A lament for the days forever lost to the Banshee Queen */

SET NAMES 'latin1';
