-- File generated by Mangos Online Translation Editor (MOTE) v2.0
SET NAMES 'utf8';
UPDATE locales_page_text SET text_loc1='록타르 오가르! 승리가 아니면 죽음뿐! 바로 우리를 호드로서 묶어주는 말이다. 호드의 모든 용사들에게 있어 가장 신성하고 중요한 믿음이기 때문이다.$B$B나는 내 피와 육체를 호드에 바칠 것이다. 나는 대족장님의 뜻을 실천하는 도구가 될 것이다. 나는 대족장님의 명령을 따르는 무기가 될 것이다.$B$B지금 이 순간부터 내 최후의 순간까지, 나는 이 목숨을 다 바칠 것이다. 호드를 위하여!' WHERE entry=3068;
UPDATE locales_page_text SET text_loc1='종들아, 주인의 부름에 응답하라! 리치 왕께서 줄드락에 있는 스컬지를 통치하라는 전권을 드라쿠루에 내리셨다. 모조리 쓸어버리라는 명령이지.$B$B한 놈도 남기지 않겠다!$B$B죽음의 들판에 있는 시체를 전부 처리한 다음, 나바리우스 왕자가 이끄는 무리가 주둔한 제라마스로 보내 스컬지를 만들어 버리겠다! 드라쿠루 감시탑에서는 아무것도 헛되이 버리지 않는다!$B$B곧 우리는 그 예언자들의 피를 마시고 이전보다 훨씬 더 강력한 존재로 거듭나리라! 줄드락과 군드락은 스컬지 앞에 무릎 꿇으리라!' WHERE entry=3279;
UPDATE locales_page_text SET text_loc1='오래전 북풍이 홀로 이 봉우리들을 지배하던 시절, 강력한 타운카 족장의 형제가 이 땅을 탐하여 자신의 것으로 삼고자 했다.' WHERE entry=3280;
UPDATE locales_page_text SET text_loc1='얼어붙은 황무지에서 벌어진 전투 중 스컬지의 손에 죽은 자들을 기리며.' WHERE entry=3605;

SET NAMES 'latin1';
