-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE locales_page_text SET text_loc1='종들아, 주인의 부름에 응답하라! 리치 왕께서 줄드락에 있는 스컬지를 통치하라는 전권을 드라쿠루에 내리셨다. 모조리 쓸어버리라는 명령이지.$b$b한 놈도 남기지 않겠다!$b$b죽음의 들판에 있는 시체를 전부 처리한 다음, 나바리우스 왕자가 이끄는 무리가 주둔한 제라마스로 보내 스컬지를 만들어 버리겠다! 드라쿠루 감시탑에서는 아무것도 헛되이 버리지 않는다!$b$b곧 우리는 그 예언자들의 피를 마시고 이전보다 훨씬 더 강력한 존재로 거듭나리라! 줄드락과 군드락은 스컬지 앞에 무릎 꿇으리라!' WHERE entry=3279; /* text: Minions be hearin\' da call of your masta! Da Lich King be givin\' Drakuru full control of da armies of da Scourge in Zul\'Drak. We be commanded ta kill everyting.$B$BEVERYTING MUST DIE!$B$BWe be processin\' all da corpses in da Dead Fields and sendin\' em up ta Prince Navarius\' crew in  Zeramas for Scourgin\'! Notin\' goes ta waste on Drakuru\'s watch!$B$BSoon we be drinkin\' da blood of da prophets ta become stronger dan eva before! Zul\'Drak and Gundrak gonna fall to da Scourge! */
UPDATE locales_page_text SET text_loc1='오래전 북풍이 홀로 이 봉우리들을 지배하던 시절, 강력한 타운카 족장의 형제가 이 땅을 탐하여 자신의 것으로 삼고자 했다.' WHERE entry=3280; /* text: Long ago, when the North Wind ruled these peaks alone, a powerful Taunka Chieftain\'s brother coveted these lands for himself. */
UPDATE locales_page_text SET text_loc1='얼어붙은 황무지에서 벌어진 전투 중 스컬지의 손에 죽은 자들을 기리며.' WHERE entry=3605; /* text: Dedicated to those that fell to the Scourge during the war in the frozen wastes. */

SET NAMES 'latin1';
