-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE mangos_string SET content_loc1='투명화' WHERE entry=42; /* content: invisible */
UPDATE mangos_string SET content_loc1='DONE' WHERE entry=43; /* content: done */
UPDATE mangos_string SET content_loc1='미사용' WHERE entry=235; /* content: UNUSED */
UPDATE mangos_string SET content_loc1='미사용' WHERE entry=242; /* content: UNUSED */
UPDATE mangos_string SET content_loc1='미사용' WHERE entry=243; /* content: UNUSED */
UPDATE mangos_string SET content_loc1='미사용' WHERE entry=244; /* content: UNUSED */
UPDATE mangos_string SET content_loc1='미사용' WHERE entry=245; /* content: UNUSED */
UPDATE mangos_string SET content_loc1='미사용' WHERE entry=251; /* content: UNUSED */
UPDATE mangos_string SET content_loc1='미점령 지역' WHERE entry=321; /* content: Neutral */
UPDATE mangos_string SET content_loc1='아군' WHERE entry=322; /* content: Friendly */
UPDATE mangos_string SET content_loc1='네' WHERE entry=421; /* content: Yes */
UPDATE mangos_string SET content_loc1='아니요' WHERE entry=422; /* content: No */
UPDATE mangos_string SET content_loc1='얼라이언스' WHERE entry=457; /* content: alliance */
UPDATE mangos_string SET content_loc1='호드' WHERE entry=458; /* content: horde */
UPDATE mangos_string SET content_loc1='얼라이언스가 승리했습니다!' WHERE entry=600; /* content: The Alliance wins! */
UPDATE mangos_string SET content_loc1='호드가 승리했습니다!' WHERE entry=601; /* content: The Horde wins! */
UPDATE mangos_string SET content_loc1='1분 후 전쟁노래 협곡 전투가 시작됩니다!' WHERE entry=602; /* content: The battle for Warsong Gulch begins in 1 minute. */
UPDATE mangos_string SET content_loc1='$n|1이;가; 호드 깃발 쟁탈에 성공했습니다!' WHERE entry=605; /* content: $n captured the Horde flag! */
UPDATE mangos_string SET content_loc1='$n|1이;가; 얼라이언스 깃발 쟁탈에 성공했습니다!' WHERE entry=606; /* content: $n captured the Alliance flag! */
UPDATE mangos_string SET content_loc1='$n|1이;가; 호드 깃발을 떨어뜨렸습니다!' WHERE entry=607; /* content: The Horde flag was dropped by $n! */
UPDATE mangos_string SET content_loc1='$n|1이;가; 얼라이언스 깃발을 떨어뜨렸습니다!' WHERE entry=608; /* content: The Alliance Flag was dropped by $n! */
UPDATE mangos_string SET content_loc1='$n|1이;가; 얼라이언스 깃발을 되찾았습니다!' WHERE entry=609; /* content: The Alliance Flag was returned to its base by $n! */
UPDATE mangos_string SET content_loc1='$n|1이;가; 호드 깃발을 기지로 반환했습니다!' WHERE entry=610; /* content: The Horde flag was returned to its base by $n! */
UPDATE mangos_string SET content_loc1='$n|1이;가; 호드 깃발을 손에 넣었습니다!' WHERE entry=611; /* content: The Horde flag was picked up by $n! */
UPDATE mangos_string SET content_loc1='$n|1이;가; 얼라이언스 깃발을 손에 넣었습니다!' WHERE entry=612; /* content: The Alliance Flag was picked up by $n! */
UPDATE mangos_string SET content_loc1='새로운 깃발이 기지에 생성되었습니다.' WHERE entry=613; /* content: The flags are now placed at their bases. */
UPDATE mangos_string SET content_loc1='얼라이언스 깃발이 기지에 생성되었습니다.' WHERE entry=614; /* content: The Alliance flag is now placed at its base. */
UPDATE mangos_string SET content_loc1='호드 깃발이 기지에 생성되었습니다.' WHERE entry=615; /* content: The Horde flag is now placed at its base. */
UPDATE mangos_string SET content_loc1='얼라이언스' WHERE entry=650; /* content: alliance */
UPDATE mangos_string SET content_loc1='호드' WHERE entry=651; /* content: horde */
UPDATE mangos_string SET content_loc1='마구간' WHERE entry=652; /* content: stables */
UPDATE mangos_string SET content_loc1='대장장이' WHERE entry=653; /* content: blacksmith */
UPDATE mangos_string SET content_loc1='농장' WHERE entry=654; /* content: farm */
UPDATE mangos_string SET content_loc1='제재소' WHERE entry=655; /* content: lumber mill */
UPDATE mangos_string SET content_loc1='내가 접수한다' WHERE entry=656; /* content: mine */
UPDATE mangos_string SET content_loc1='얼라이언스는 지금까지 $1776W의 자원을 모아 승리가 눈앞에 있습니다!' WHERE entry=664; /* content: The Alliance has gathered $1776W resources, and is near victory! */
UPDATE mangos_string SET content_loc1='호드는 지금까지 $1777W의 자원을 모아 승리가 눈앞에 있습니다!' WHERE entry=665; /* content: The Horde has gathered $1777W resources, and is near victory! */
UPDATE mangos_string SET content_loc1='얼라이언스가 마법사 탑을 점령했습니다!' WHERE entry=667; /* content: The Alliance has taken control of the Mage Tower! */
UPDATE mangos_string SET content_loc1='호드가 마법사 탑을 점령했습니다!' WHERE entry=668; /* content: The Horde has taken control of the Mage Tower! */
UPDATE mangos_string SET content_loc1='얼라이언스가 드레나이 폐허를 점령했습니다!' WHERE entry=669; /* content: The Alliance has taken control of the Draenei Ruins! */
UPDATE mangos_string SET content_loc1='호드가 드레나이 폐허를 점령했습니다!' WHERE entry=670; /* content: The Horde has taken control of the Draenei Ruins! */
UPDATE mangos_string SET content_loc1='얼라이언스가 블러드 엘프 경비탑을 점령했습니다!' WHERE entry=671; /* content: The Alliance has taken control of the Blood Elf Tower! */
UPDATE mangos_string SET content_loc1='호드가 블러드 엘프 경비탑을 점령했습니다!' WHERE entry=672; /* content: The Horde has taken control of the Blood Elf Tower! */
UPDATE mangos_string SET content_loc1='얼라이언스가 지옥절단기 폐허를 점령했습니다!' WHERE entry=673; /* content: The Alliance has taken control of the Fel Reaver Ruins! */
UPDATE mangos_string SET content_loc1='호드가 지옥절단기 폐허를 점령했습니다!' WHERE entry=674; /* content: The Horde has taken control of the Fel Reaver Ruins! */
UPDATE mangos_string SET content_loc1='얼라이언스가 마법사 탑을 빼앗겼습니다!' WHERE entry=675; /* content: The Alliance has lost control of the Mage Tower! */
UPDATE mangos_string SET content_loc1='호드가 마법사 탑을 빼앗겼습니다!' WHERE entry=676; /* content: The Horde has lost control of the Mage Tower! */
UPDATE mangos_string SET content_loc1='얼라이언스가 드레나이 폐허를 빼앗겼습니다!' WHERE entry=677; /* content: The Alliance has lost control of the Draenei Ruins! */
UPDATE mangos_string SET content_loc1='호드가 드레나이 폐허를 빼앗겼습니다!' WHERE entry=678; /* content: The Horde has lost control of the Draenei Ruins! */
UPDATE mangos_string SET content_loc1='얼라이언스가 블러드 엘프 경비탑을 빼앗겼습니다!' WHERE entry=679; /* content: The Alliance has lost control of the Blood Elf Tower! */
UPDATE mangos_string SET content_loc1='호드가 블러드 엘프 경비탑을 빼앗겼습니다!' WHERE entry=680; /* content: The Horde has lost control of the Blood Elf Tower! */
UPDATE mangos_string SET content_loc1='얼라이언스가 지옥절단기 폐허를 빼앗겼습니다!' WHERE entry=681; /* content: The Alliance has lost control of the Fel Reaver Ruins! */
UPDATE mangos_string SET content_loc1='호드가 지옥절단기 폐허를 빼앗겼습니다!' WHERE entry=682; /* content: The Horde has lost control of the Fel Reaver Ruins! */
UPDATE mangos_string SET content_loc1='얼라이언스가 깃발을 차지했습니다!' WHERE entry=684; /* content: The Alliance have captured the flag! */
UPDATE mangos_string SET content_loc1='호드가 깃발을 차지했습니다!' WHERE entry=685; /* content: The Horde have captured the flag! */
UPDATE mangos_string SET content_loc1='깃발이 다시 제자리로 돌아갔습니다.' WHERE entry=687; /* content: The flag has been reset. */
UPDATE mangos_string SET content_loc1='투기장 전투 시작 1분 전입니다!' WHERE entry=701; /* content: One minute until the Arena battle begins! */
UPDATE mangos_string SET content_loc1='투기장 전투 시작 30초 전입니다!' WHERE entry=702; /* content: Thirty seconds until the Arena battle begins! */
UPDATE mangos_string SET content_loc1='투기장 전투 시작 15초 전입니다!' WHERE entry=703; /* content: Fifteen seconds until the Arena battle begins! */
UPDATE mangos_string SET content_loc1='투기장 전투가 시작되었습니다!' WHERE entry=704; /* content: The Arena battle has begun! */
UPDATE mangos_string SET content_loc1='깊은무쇠 광산' WHERE entry=766; /* content: Irondeep Mine */
UPDATE mangos_string SET content_loc1='얼음이빨 광산' WHERE entry=767; /* content: Coldtooth Mine */
UPDATE mangos_string SET content_loc1='스톰파이크 보급기지' WHERE entry=768; /* content: Stormpike Aid Station */
UPDATE mangos_string SET content_loc1='남부 던 발다르 참호' WHERE entry=769; /* content: Dun Baldar South Bunker */
UPDATE mangos_string SET content_loc1='북부 던 발다르 참호' WHERE entry=770; /* content: Dun Baldar North Bunker */
UPDATE mangos_string SET content_loc1='스톰파이크 무덤' WHERE entry=771; /* content: Stormpike Graveyard */
UPDATE mangos_string SET content_loc1='1번째 계급 달성: 하사관' WHERE entry=771; /* content: You have reached Rank 1: Corporal */
UPDATE mangos_string SET content_loc1='얼음날개 참호' WHERE entry=772; /* content: Icewing Bunker */
UPDATE mangos_string SET content_loc1='2번째 계급 달성: 부관' WHERE entry=772; /* content: You have reached Rank 2: First Lieutenant */
UPDATE mangos_string SET content_loc1='돌난로 무덤' WHERE entry=773; /* content: Stonehearth Graveyard */
UPDATE mangos_string SET content_loc1='돌난로 참호' WHERE entry=774; /* content: Stonehearth Bunker */
UPDATE mangos_string SET content_loc1='눈사태 무덤' WHERE entry=775; /* content: Snowfall Graveyard */
UPDATE mangos_string SET content_loc1='얼음피 보초탑' WHERE entry=776; /* content: Iceblood Tower */
UPDATE mangos_string SET content_loc1='얼음피 무덤' WHERE entry=777; /* content: Iceblood Graveyard */
UPDATE mangos_string SET content_loc1='거점 보초탑' WHERE entry=778; /* content: Tower Point */
UPDATE mangos_string SET content_loc1='서리늑대 무덤' WHERE entry=779; /* content: Frostwolf Graveyard */
UPDATE mangos_string SET content_loc1='동부 서리늑대 보초탑' WHERE entry=780; /* content: East Frostwolf Tower */
UPDATE mangos_string SET content_loc1='서부 서리늑대 보초탑' WHERE entry=781; /* content: West Frostwolf Tower */
UPDATE mangos_string SET content_loc1='서리늑대 구호막사' WHERE entry=782; /* content: Frostwolf Relief Hut */
UPDATE mangos_string SET content_loc1='알터랙 계곡 전투 개시 1분 전...' WHERE entry=784; /* content: 1 minute until the battle for Alterac Valley begins. */
UPDATE mangos_string SET content_loc1='알터랙 계곡 전투가 시작되었습니다!' WHERE entry=786; /* content: The battle for Alterac Valley has begun! */
UPDATE mangos_string SET content_loc1='얼라이언스의 군사력이 약해지고 있습니다!' WHERE entry=787; /* content: The Alliance Team is running out of reinforcements! */
UPDATE mangos_string SET content_loc1='호드의 군사력이 약해지고 있습니다!' WHERE entry=788; /* content: The Horde Team is running out of reinforcements! */
UPDATE mangos_string SET content_loc1='서리늑대 부족 사령관이 전사했습니다!' WHERE entry=789; /* content: The Frostwolf General is Dead! */
UPDATE mangos_string SET content_loc1='스톰파이크 사령관이 전사했습니다!' WHERE entry=790; /* content: The Stormpike General is Dead! */
UPDATE mangos_string SET content_loc1='길드 사무관' WHERE entry=811; /* content: Guild Master */
UPDATE mangos_string SET content_loc1='경고: 날 수 없는 지역에 진입했으며, 탈것에서 떨어지기 직전입니다!' WHERE entry=816; /* content: Warning: You\'ve entered a no-fly zone and are about to be dismounted! */
UPDATE mangos_string SET content_loc1='경고: 날 수 없는 지역에 진입했으며, 탈것에서 떨어지기 직전입니다!' WHERE entry=817; /* content: Warning: You\'ve entered a no-fly zone and are about to be dismounted! */
UPDATE mangos_string SET content_loc1='녹색 (노란+푸른)' WHERE entry=1170; /* content: Green */
UPDATE mangos_string SET content_loc1='청팀' WHERE entry=1171; /* content: Blue */
UPDATE mangos_string SET content_loc1='보라색 (붉은+푸른)' WHERE entry=1172; /* content: Purple */
UPDATE mangos_string SET content_loc1='오렌지' WHERE entry=1173; /* content: Orange */
UPDATE mangos_string SET content_loc1='노란색' WHERE entry=1174; /* content: Yellow */
UPDATE mangos_string SET content_loc1='녹색 (노란+푸른)' WHERE entry=1185; /* content: Green */
UPDATE mangos_string SET content_loc1='청팀' WHERE entry=1186; /* content: Blue */
UPDATE mangos_string SET content_loc1='보라색 (붉은+푸른)' WHERE entry=1187; /* content: Purple */
UPDATE mangos_string SET content_loc1='오렌지' WHERE entry=1188; /* content: Orange */
UPDATE mangos_string SET content_loc1='노란색' WHERE entry=1189; /* content: Yellow */
UPDATE mangos_string SET content_loc1='1분 후 전투가 시작됩니다.' WHERE entry=1206; /* content: The battle will begin in 1 minute. */
UPDATE mangos_string SET content_loc1='|cffffff00호드가 북부관문 경비탑을 점령했습니다!|r' WHERE entry=1600; /* content: |cffffff00Northpass Tower has been taken by the Horde!|r */
UPDATE mangos_string SET content_loc1='|cffffff00얼라이언스가 북부관문 경비탑을 점령했습니다!|r' WHERE entry=1601; /* content: |cffffff00Northpass Tower has been taken by the Alliance!|r */
UPDATE mangos_string SET content_loc1='|cffffff00호드가 산마루 경비탑을 점령했습니다!|r' WHERE entry=1602; /* content: |cffffff00Crown Guard Tower has been taken by the Horde!|r */
UPDATE mangos_string SET content_loc1='|cffffff00얼라이언스가 산마루 경비탑을 점령했습니다!|r' WHERE entry=1603; /* content: |cffffff00Crown Guard Tower has been taken by the Alliance!|r */
UPDATE mangos_string SET content_loc1='|cffffff00호드가 동부방벽 경비탑을 점령했습니다!|r' WHERE entry=1604; /* content: |cffffff00Eastwall Tower has been taken by the Horde!|r */
UPDATE mangos_string SET content_loc1='|cffffff00얼라이언스가 동부방벽 경비탑을 점령했습니다!!|r' WHERE entry=1605; /* content: |cffffff00Eastwall Tower has been taken by the Alliance!|r */
UPDATE mangos_string SET content_loc1='|cffffff00호드가 역병숲 경비탑을 점령했습니다!|r' WHERE entry=1606; /* content: |cffffff00The Plaguewood Tower has been taken by the Horde!|r */
UPDATE mangos_string SET content_loc1='|cffffff00얼라이언스가 역병숲 경비탑을 점령했습니다!|r' WHERE entry=1607; /* content: |cffffff00The Plaguewood Tower has been taken by the Alliance!|r */
UPDATE mangos_string SET content_loc1='|cffffff00호드가 전망대를 점령했습니다!|r' WHERE entry=1608; /* content: |cffffff00The Overlook has been taken by the Horde!|r */
UPDATE mangos_string SET content_loc1='|cffffff00얼라이언스가 전망대를 점령했습니다!|r' WHERE entry=1609; /* content: |cffffff00The Overlook has been taken by the Alliance!|r */
UPDATE mangos_string SET content_loc1='|cffffff00호드가 경기장을 점령했습니다!|r' WHERE entry=1610; /* content: |cffffff00The Stadium has been taken by the Horde!|r */
UPDATE mangos_string SET content_loc1='|cffffff00얼라이언스가 경기장을 점령했습니다!|r' WHERE entry=1611; /* content: |cffffff00The Stadium has been taken by the Alliance!|r */
UPDATE mangos_string SET content_loc1='|cffffff00호드가 무너진 언덕을 점령했습니다!|r' WHERE entry=1612; /* content: |cffffff00Broken Hill has been taken by the Horde!|r */
UPDATE mangos_string SET content_loc1='|cffffff00얼라이언스가 무너진 언덕을 점령했습니다!|r' WHERE entry=1613; /* content: |cffffff00Broken Hill has been taken by the Alliance!|r */
UPDATE mangos_string SET content_loc1='|cffffff00호드가 동쪽 봉화를 차지했습니다!|r' WHERE entry=1614; /* content: |cffffff00The Horde has taken control of the East Beacon!|r */
UPDATE mangos_string SET content_loc1='|cffffff00얼라이언스가 동쪽 봉화를 차지했습니다!|r' WHERE entry=1615; /* content: |cffffff00The Alliance has taken control of the East Beacon!|r */
UPDATE mangos_string SET content_loc1='|cffffff00호드가 서쪽 봉화를 차지했습니다!|r' WHERE entry=1616; /* content: |cffffff00The Horde has taken control of the West Beacon!|r */
UPDATE mangos_string SET content_loc1='|cffffff00얼라이언스가 서쪽 봉화를 차지했습니다!|r' WHERE entry=1617; /* content: |cffffff00The Alliance has taken control of the West Beacon!|r */
UPDATE mangos_string SET content_loc1='|cffffff00호드가 두 개의 봉화를 모두 차지했습니다!|r' WHERE entry=1618; /* content: |cffffff00The Horde has taken control of both beacons!|r */
UPDATE mangos_string SET content_loc1='|cffffff00얼라이언스가 두 개의 봉화를 모두 차지했습니다!|r' WHERE entry=1619; /* content: |cffffff00The Alliance has taken control of both beacons!|r */
UPDATE mangos_string SET content_loc1='|cffffff00호드 척후병이 전투 깃발을 나눠 주고 있습니다.|r' WHERE entry=1620; /* content: |cffffff00The Horde Field Scout is now issuing battle standards.|r */
UPDATE mangos_string SET content_loc1='|cffffff00얼라이언스 척후병이 전투 깃발을 나눠 주고 있습니다.|r' WHERE entry=1621; /* content: |cffffff00The Alliance Field Scout is now issuing battle standards.|r */
UPDATE mangos_string SET content_loc1='|cffffff00호드가 쌍둥이 첨탑 폐허의 통제권을 차지했습니다!|r' WHERE entry=1622; /* content: |cffffff00The Horde has taken control of Twin Spire Ruins!|r */
UPDATE mangos_string SET content_loc1='|cffffff00얼라이언스가 쌍둥이 첨탑 폐허를 차지했습니다!|r' WHERE entry=1623; /* content: |cffffff00The Alliance has taken control of Twin Spire Ruins!|r */
UPDATE mangos_string SET content_loc1='|cffffff00호드가 영혼의 탑을 차지했습니다!|r' WHERE entry=1624; /* content: |cffffff00The Horde has taken control of a Spirit Tower!|r */
UPDATE mangos_string SET content_loc1='|cffffff00얼라이언스가 영혼의 탑을 차지했습니다!|r' WHERE entry=1625; /* content: |cffffff00The Alliance has taken control of a Spirit Tower!|r */
UPDATE mangos_string SET content_loc1='|cffffff00호드가 영혼의 탑을 빼앗겼습니다!|r' WHERE entry=1626; /* content: |cffffff00The Horde has lost control of a Spirit Tower!|r */
UPDATE mangos_string SET content_loc1='|cffffff00얼라이언스가 영혼의 탑을 빼앗겼습니다!|r' WHERE entry=1627; /* content: |cffffff00The Alliance has lost control of a Spirit Tower!|r */
UPDATE mangos_string SET content_loc1='|cffffff00호드가 해골 무덤을 차지했습니다!|r' WHERE entry=1628; /* content: |cffffff00The Horde has taken control of The Bone Wastes!|r */
UPDATE mangos_string SET content_loc1='|cffffff00얼라이언스가 해골 무덤을 차지했습니다!|r' WHERE entry=1629; /* content: |cffffff00The Alliance has taken control of The Bone Wastes!|r */
UPDATE mangos_string SET content_loc1='|cffffff00호드가 할라아를 차지했습니다!|r' WHERE entry=1630; /* content: |cffffff00The Horde is gaining control of Halaa!|r */
UPDATE mangos_string SET content_loc1='|cffffff00얼라이언스가 할라아를 차지했습니다!|r' WHERE entry=1631; /* content: |cffffff00The Alliance is gaining control of Halaa!|r */
UPDATE mangos_string SET content_loc1='|cffffff00호드가 할라아를 차지했습니다!|r' WHERE entry=1632; /* content: |cffffff00The Horde has taken control of Halaa!|r */
UPDATE mangos_string SET content_loc1='|cffffff00얼라이언스가 할라아를 차지했습니다!|r' WHERE entry=1633; /* content: |cffffff00The Alliance has taken control of Halaa!|r */
UPDATE mangos_string SET content_loc1='|cffffff00할라아가 무방비 상태가 되었습니다!|r' WHERE entry=1634; /* content: |cffffff00Halaa is defenseless!|r */

SET NAMES 'latin1';
