-- File generated by MOTE (Mangos Online Translation Editor) v0.01
SET NAMES 'utf8';
UPDATE locales_gossip_menu_option SET option_text_loc1='드루이드' WHERE menu_id=401 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=401 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=401 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='성기사' WHERE menu_id=401 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=401 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=401 AND id=5; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='주술사' WHERE menu_id=401 AND id=6; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc1='흑마법사' WHERE menu_id=401 AND id=7; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=401 AND id=8; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=421 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=421 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=421 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=421 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=421 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=421 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=421 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=421 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=421 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=421 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=421 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=421 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=421 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='경매장' WHERE menu_id=435 AND id=0; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc1='그리핀 조련사' WHERE menu_id=435 AND id=5; /* option_text: Gryphon Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='길드 사무관' WHERE menu_id=435 AND id=6; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='자물쇠 상인' WHERE menu_id=435 AND id=7; /* option_text: Locksmith */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=435 AND id=8; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='전투모병관' WHERE menu_id=435 AND id=11; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc1='미용사' WHERE menu_id=435 AND id=12; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc1='마력의 사전' WHERE menu_id=435 AND id=13; /* option_text: Lexicon of Power */
UPDATE locales_gossip_menu_option SET option_text_loc1='드루이드' WHERE menu_id=740 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=740 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=740 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=740 AND id=3; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='주술사' WHERE menu_id=740 AND id=4; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=740 AND id=5; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=751 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=751 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=751 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=751 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=751 AND id=4; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=751 AND id=5; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=751 AND id=6; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=751 AND id=7; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=751 AND id=8; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=751 AND id=9; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=751 AND id=10; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=751 AND id=11; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=1942 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=1942 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=1942 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=1942 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=1942 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=1942 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=1942 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=1942 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=1942 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=1942 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=1942 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=1942 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=1942 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=1949 AND id=0; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=1949 AND id=1; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=1949 AND id=2; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='주술사' WHERE menu_id=1949 AND id=3; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=1949 AND id=4; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='흑마법사' WHERE menu_id=1949 AND id=5; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=1949 AND id=6; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='성기사' WHERE menu_id=1949 AND id=7; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc1='미용사' WHERE menu_id=1951 AND id=11; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc1='마력의 사전' WHERE menu_id=1951 AND id=14; /* option_text: Lexicon of Power */
UPDATE locales_gossip_menu_option SET option_text_loc1='경매장' WHERE menu_id=2121 AND id=0; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc1='그리핀 조련사' WHERE menu_id=2121 AND id=3; /* option_text: Gryphon Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='길드 사무관' WHERE menu_id=2121 AND id=4; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='우체통' WHERE menu_id=2121 AND id=6; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=2121 AND id=7; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='전투모병관' WHERE menu_id=2121 AND id=9; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc1='미용사' WHERE menu_id=2121 AND id=10; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc1='마력의 사전' WHERE menu_id=2121 AND id=13; /* option_text: Lexicon of Power */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=2144 AND id=0; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=2144 AND id=1; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='성기사' WHERE menu_id=2144 AND id=2; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=2144 AND id=3; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=2144 AND id=4; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='흑마법사' WHERE menu_id=2144 AND id=5; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=2144 AND id=6; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='주술사' WHERE menu_id=2144 AND id=7; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=2168 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=2168 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=2168 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=2168 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=2168 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=2168 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=2168 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=2168 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=2168 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=2168 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=2168 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=2168 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=2168 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='드루이드' WHERE menu_id=2343 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=2343 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=2343 AND id=2; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=2343 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=2343 AND id=3; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='성기사' WHERE menu_id=2343 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=2343 AND id=4; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=2343 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=2343 AND id=5; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=2343 AND id=6; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=2351 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=2351 AND id=1; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=2351 AND id=2; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=2351 AND id=3; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=2351 AND id=4; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=2351 AND id=5; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=2351 AND id=6; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=2351 AND id=7; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=2351 AND id=8; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=2351 AND id=9; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='경매장' WHERE menu_id=2352 AND id=0; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc1='히포그리프 조련사' WHERE menu_id=2352 AND id=2; /* option_text: Hippogryph Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='길드 사무관' WHERE menu_id=2352 AND id=3; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='우체통' WHERE menu_id=2352 AND id=5; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=2352 AND id=6; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='전투모병관' WHERE menu_id=2352 AND id=8; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc1='마력의 사전' WHERE menu_id=2352 AND id=11; /* option_text: Lexicon of Power */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=2847 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=2847 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=2847 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=2847 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=2847 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=2847 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=2847 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=2847 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=2847 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=2847 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=2847 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=2847 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=2847 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=2848 AND id=0; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='성기사' WHERE menu_id=2848 AND id=1; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=2848 AND id=2; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=2848 AND id=3; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='흑마법사' WHERE menu_id=2848 AND id=4; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=2848 AND id=5; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='미용사' WHERE menu_id=2849 AND id=10; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc1='자물쇠 상인' WHERE menu_id=2849 AND id=14; /* option_text: Locksmith */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=3283 AND id=0; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=3283 AND id=1; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=3283 AND id=2; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=3283 AND id=3; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='주술사' WHERE menu_id=3283 AND id=4; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc1='흑마법사' WHERE menu_id=3283 AND id=5; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=3283 AND id=6; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=3284 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=3284 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=3284 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=3284 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=3284 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=3284 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=3284 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=3284 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=3284 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=3284 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=3284 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=3284 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=3284 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='드루이드' WHERE menu_id=3329 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=3329 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='주술사' WHERE menu_id=3329 AND id=2; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=3329 AND id=3; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=3330 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=3330 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=3330 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=3330 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=3330 AND id=4; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=3330 AND id=5; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=3330 AND id=6; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=3330 AND id=7; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=3330 AND id=8; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=3330 AND id=9; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=3330 AND id=10; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=3330 AND id=11; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=3354 AND id=0; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='성기사' WHERE menu_id=3354 AND id=1; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=3354 AND id=2; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=3354 AND id=3; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='흑마법사' WHERE menu_id=3354 AND id=4; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=3354 AND id=5; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=3355 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=3355 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=3355 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=3355 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=3355 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=3355 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=3355 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=3355 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=3355 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=3355 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=3355 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=3355 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=3355 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='은행' WHERE menu_id=3506 AND id=0; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc1='그리핀 조련사' WHERE menu_id=3506 AND id=1; /* option_text: Gryphon Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='길드 사무관' WHERE menu_id=3506 AND id=2; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='여관' WHERE menu_id=3506 AND id=3; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=3506 AND id=4; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='드루이드' WHERE menu_id=3519 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=3519 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=3519 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='성기사' WHERE menu_id=3519 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=3519 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=3519 AND id=5; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='주술사' WHERE menu_id=3519 AND id=6; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc1='흑마법사' WHERE menu_id=3519 AND id=7; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=3519 AND id=8; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=3532 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=3532 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=3532 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=3532 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=3532 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=3532 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=3532 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=3532 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=3532 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=3532 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=3532 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=3532 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=3532 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='은행' WHERE menu_id=3533 AND id=0; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc1='그리핀 조련사' WHERE menu_id=3533 AND id=1; /* option_text: Gryphon Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='길드 사무관' WHERE menu_id=3533 AND id=2; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=3533 AND id=4; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=3545 AND id=0; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=3545 AND id=1; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='성기사' WHERE menu_id=3545 AND id=2; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=3545 AND id=3; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=3545 AND id=4; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='흑마법사' WHERE menu_id=3545 AND id=5; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=3545 AND id=6; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=3558 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=3558 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=3558 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=3558 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=3558 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=3558 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=3558 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=3558 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=3558 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=3558 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=3558 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=3558 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=3558 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='드루이드' WHERE menu_id=3564 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=3564 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=3564 AND id=2; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=3564 AND id=3; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=3564 AND id=4; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=3572 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=3572 AND id=1; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=3572 AND id=2; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=3572 AND id=3; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=3572 AND id=4; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=3572 AND id=5; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=3572 AND id=6; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=3572 AND id=7; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=3572 AND id=8; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=3572 AND id=9; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=3580 AND id=4; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='굴단' WHERE menu_id=4764 AND id=0; /* option_text: Gul\'dan */
UPDATE locales_gossip_menu_option SET option_text_loc1='켈투자드' WHERE menu_id=4764 AND id=1; /* option_text: Kel\'Thuzad */
UPDATE locales_gossip_menu_option SET option_text_loc1='철퇴' WHERE menu_id=5222 AND id=2; /* option_text: Mace */
UPDATE locales_gossip_menu_option SET option_text_loc1='지팡이 상점' WHERE menu_id=5222 AND id=4; /* option_text: Staff */
UPDATE locales_gossip_menu_option SET option_text_loc1='철퇴' WHERE menu_id=5262 AND id=4; /* option_text: Mace */
UPDATE locales_gossip_menu_option SET option_text_loc1='철퇴' WHERE menu_id=5268 AND id=4; /* option_text: Mace */
UPDATE locales_gossip_menu_option SET option_text_loc1='지팡이 상점' WHERE menu_id=5268 AND id=5; /* option_text: Staff */
UPDATE locales_gossip_menu_option SET option_text_loc1='철퇴' WHERE menu_id=5270 AND id=4; /* option_text: Mace */
UPDATE locales_gossip_menu_option SET option_text_loc1='경매장' WHERE menu_id=6957 AND id=1; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc1='그리핀 조련사' WHERE menu_id=6957 AND id=5; /* option_text: Gryphon Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='길드 사무관' WHERE menu_id=6957 AND id=6; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='우체통' WHERE menu_id=6957 AND id=7; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=6957 AND id=8; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='전투모병관' WHERE menu_id=6957 AND id=11; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc1='미용사' WHERE menu_id=6957 AND id=12; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc1='마력의 사전' WHERE menu_id=6957 AND id=13; /* option_text: Lexicon of Power */
UPDATE locales_gossip_menu_option SET option_text_loc1='경매장' WHERE menu_id=6958 AND id=1; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc1='그리핀 조련사' WHERE menu_id=6958 AND id=5; /* option_text: Gryphon Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='길드 사무관' WHERE menu_id=6958 AND id=6; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='우체통' WHERE menu_id=6958 AND id=7; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=6958 AND id=8; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='전투모병관' WHERE menu_id=6958 AND id=11; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc1='미용사' WHERE menu_id=6958 AND id=12; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc1='마력의 사전' WHERE menu_id=6958 AND id=13; /* option_text: Lexicon of Power */
UPDATE locales_gossip_menu_option SET option_text_loc1='경매장' WHERE menu_id=6999 AND id=1; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc1='히포그리프 조련사' WHERE menu_id=6999 AND id=3; /* option_text: Hippogryph Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='길드 사무관' WHERE menu_id=6999 AND id=4; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='우체통' WHERE menu_id=6999 AND id=6; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=6999 AND id=7; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='전투모병관' WHERE menu_id=6999 AND id=9; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc1='마력의 사전' WHERE menu_id=6999 AND id=12; /* option_text: Lexicon of Power */
UPDATE locales_gossip_menu_option SET option_text_loc1='경매장' WHERE menu_id=7035 AND id=1; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc1='그리핀 조련사' WHERE menu_id=7035 AND id=4; /* option_text: Gryphon Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='길드 사무관' WHERE menu_id=7035 AND id=5; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='우체통' WHERE menu_id=7035 AND id=7; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=7035 AND id=8; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='전투모병관' WHERE menu_id=7035 AND id=10; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc1='미용사' WHERE menu_id=7035 AND id=11; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc1='마력의 사전' WHERE menu_id=7035 AND id=14; /* option_text: Lexicon of Power */
UPDATE locales_gossip_menu_option SET option_text_loc1='경매장' WHERE menu_id=7633 AND id=0; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc1='용매 조련사' WHERE menu_id=7633 AND id=2; /* option_text: Dragonhawk Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='길드 사무관' WHERE menu_id=7633 AND id=3; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='우체통' WHERE menu_id=7633 AND id=5; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=7633 AND id=6; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='무기 전문가' WHERE menu_id=7633 AND id=7; /* option_text: Weapon Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='마나 베틀' WHERE menu_id=7633 AND id=11; /* option_text: Mana Loom */
UPDATE locales_gossip_menu_option SET option_text_loc1='드루이드' WHERE menu_id=7649 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=7649 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=7649 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='성기사' WHERE menu_id=7649 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=7649 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=7649 AND id=5; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='흑마법사' WHERE menu_id=7649 AND id=6; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=7667 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=7667 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=7667 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=7667 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=7667 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=7667 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=7667 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=7667 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=7667 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='보석세공 상점' WHERE menu_id=7667 AND id=9; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=7667 AND id=10; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=7667 AND id=11; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=7667 AND id=12; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=7667 AND id=13; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='경매장' WHERE menu_id=7777 AND id=0; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc1='히포그리프 조련사' WHERE menu_id=7777 AND id=2; /* option_text: Hippogryph Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='길드 사무관' WHERE menu_id=7777 AND id=3; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='우체통' WHERE menu_id=7777 AND id=5; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=7777 AND id=6; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='무기 전문가' WHERE menu_id=7777 AND id=7; /* option_text: Weapon Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='투기장 사무관' WHERE menu_id=7786 AND id=0; /* option_text: Arena Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc1='드루이드' WHERE menu_id=7787 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=7787 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=7787 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='성기사' WHERE menu_id=7787 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=7787 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='주술사' WHERE menu_id=7787 AND id=5; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=7787 AND id=6; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=7788 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=7788 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=7788 AND id=2; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=7788 AND id=3; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=7788 AND id=4; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=7788 AND id=5; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=7788 AND id=6; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=7788 AND id=7; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='보석세공 상점' WHERE menu_id=7788 AND id=8; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=7788 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=7788 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=7788 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=7788 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=7788 AND id=13; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='실버문 여관' WHERE menu_id=7845 AND id=0; /* option_text: Silvermoon City Inn */
UPDATE locales_gossip_menu_option SET option_text_loc1='은행' WHERE menu_id=8129 AND id=0; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc1='히포그리프 조련사' WHERE menu_id=8129 AND id=1; /* option_text: Hippogryph Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='길드 사무관' WHERE menu_id=8129 AND id=2; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='여관' WHERE menu_id=8129 AND id=3; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=8129 AND id=4; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='드루이드' WHERE menu_id=8137 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=8137 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=8137 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='성기사' WHERE menu_id=8137 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=8137 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='주술사' WHERE menu_id=8137 AND id=5; /* option_text: Shaman */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=8137 AND id=6; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=8138 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=8138 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=8138 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=8138 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=8138 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=8138 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=8138 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=8138 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=8138 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='보석세공 상점' WHERE menu_id=8138 AND id=9; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=8138 AND id=10; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=8138 AND id=11; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=8138 AND id=12; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=8138 AND id=13; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='용매 조련사' WHERE menu_id=8185 AND id=0; /* option_text: Dragonhawk Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='길드 사무관' WHERE menu_id=8185 AND id=1; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=8185 AND id=3; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='드루이드' WHERE menu_id=8196 AND id=0; /* option_text: Druid */
UPDATE locales_gossip_menu_option SET option_text_loc1='사냥꾼' WHERE menu_id=8196 AND id=1; /* option_text: Hunter */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=8196 AND id=2; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='성기사' WHERE menu_id=8196 AND id=3; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=8196 AND id=4; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=8196 AND id=5; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='흑마법사' WHERE menu_id=8196 AND id=6; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=8205 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=8205 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=8205 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=8205 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=8205 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=8205 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=8205 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=8205 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=8205 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='보석세공 상점' WHERE menu_id=8205 AND id=9; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=8205 AND id=10; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=8205 AND id=11; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=8205 AND id=12; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=8205 AND id=13; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='은행' WHERE menu_id=8282 AND id=1; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc1='여관' WHERE menu_id=8282 AND id=2; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc1='비행 조련사' WHERE menu_id=8282 AND id=3; /* option_text: Flight Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='우체통' WHERE menu_id=8282 AND id=4; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=8282 AND id=5; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='전투모병관' WHERE menu_id=8282 AND id=6; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc1='마나 베틀' WHERE menu_id=8282 AND id=8; /* option_text: Mana Loom */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 실험대' WHERE menu_id=8282 AND id=9; /* option_text: Alchemy Lab */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=8326 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=8326 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=8326 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=8326 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=8326 AND id=4; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='보석세공 상점' WHERE menu_id=8326 AND id=5; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=8326 AND id=6; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=8326 AND id=7; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='은행' WHERE menu_id=8357 AND id=1; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc1='여관' WHERE menu_id=8357 AND id=2; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc1='비행 조련사' WHERE menu_id=8357 AND id=3; /* option_text: Flight Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='우체통' WHERE menu_id=8357 AND id=4; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=8357 AND id=5; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='전투모병관' WHERE menu_id=8357 AND id=6; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc1='마나 베틀' WHERE menu_id=8357 AND id=8; /* option_text: Mana Loom */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 실험대' WHERE menu_id=8357 AND id=9; /* option_text: Alchemy Lab */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=8403 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=8403 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=8403 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=8403 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=8403 AND id=4; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='보석세공 상점' WHERE menu_id=8403 AND id=5; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=8403 AND id=6; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=8403 AND id=7; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='은행' WHERE menu_id=8419 AND id=1; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc1='여관' WHERE menu_id=8419 AND id=2; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc1='비행 조련사' WHERE menu_id=8419 AND id=3; /* option_text: Flight Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='우체통' WHERE menu_id=8419 AND id=4; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=8419 AND id=5; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='전투모병관' WHERE menu_id=8419 AND id=6; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc1='마나 베틀' WHERE menu_id=8419 AND id=8; /* option_text: Mana Loom */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 실험대' WHERE menu_id=8419 AND id=9; /* option_text: Alchemy Lab */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=8424 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=8424 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=8424 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=8424 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=8424 AND id=4; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='보석세공 상점' WHERE menu_id=8424 AND id=5; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=8424 AND id=6; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=8424 AND id=7; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=8994 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='맥주 사랑 동호회' WHERE menu_id=8994 AND id=4; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc1='맥주 사랑 동호회' WHERE menu_id=8995 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=8996 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='맥주 사랑 동호회' WHERE menu_id=8996 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=8997 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='맥주 사랑 동호회' WHERE menu_id=8997 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=8999 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='맥주 사랑 동호회' WHERE menu_id=8999 AND id=4; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc1='맥주 사랑 동호회' WHERE menu_id=9000 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9001 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='맥주 사랑 동호회' WHERE menu_id=9001 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9002 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='맥주 사랑 동호회' WHERE menu_id=9002 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9017 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='맥주 사랑 동호회' WHERE menu_id=9017 AND id=4; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9018 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='맥주 사랑 동호회' WHERE menu_id=9018 AND id=4; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9025 AND id=0; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='맥주 사랑 동호회' WHERE menu_id=9025 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9026 AND id=0; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='맥주 사랑 동호회' WHERE menu_id=9026 AND id=3; /* option_text: Brew of the Month Club */
UPDATE locales_gossip_menu_option SET option_text_loc1='멜리호' WHERE menu_id=9038 AND id=0; /* option_text: The Lady Mehley */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9038 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9040 AND id=0; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='멜리호' WHERE menu_id=9041 AND id=0; /* option_text: The Lady Mehley */
UPDATE locales_gossip_menu_option SET option_text_loc1='멜리호' WHERE menu_id=9042 AND id=0; /* option_text: The Lady Mehley */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9042 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='멜리호' WHERE menu_id=9043 AND id=0; /* option_text: The Lady Mehley */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9043 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9073 AND id=0; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='처녀의 몽상호' WHERE menu_id=9074 AND id=0; /* option_text: The Maiden\'s Fancy */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9074 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='처녀의 몽상호' WHERE menu_id=9075 AND id=0; /* option_text: The Maiden\'s Fancy */
UPDATE locales_gossip_menu_option SET option_text_loc1='처녀의 몽상호' WHERE menu_id=9076 AND id=0; /* option_text: The Maiden\'s Fancy */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9076 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9558 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='식료품 상인' WHERE menu_id=9559 AND id=1; /* option_text: Food & Drink */
UPDATE locales_gossip_menu_option SET option_text_loc1='투기장' WHERE menu_id=10043 AND id=0; /* option_text: Arena */
UPDATE locales_gossip_menu_option SET option_text_loc1='경매장' WHERE menu_id=10043 AND id=1; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc1='은행' WHERE menu_id=10043 AND id=2; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc1='미용사' WHERE menu_id=10043 AND id=3; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc1='비행 조련사' WHERE menu_id=10043 AND id=6; /* option_text: Flight Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='길드 사무관' WHERE menu_id=10043 AND id=7; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='여관' WHERE menu_id=10043 AND id=8; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc1='자물쇠 상인' WHERE menu_id=10043 AND id=9; /* option_text: Locksmith */
UPDATE locales_gossip_menu_option SET option_text_loc1='우체통' WHERE menu_id=10043 AND id=10; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=10043 AND id=12; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='보랏빛 요새' WHERE menu_id=10056 AND id=3; /* option_text: The Violet Hold */
UPDATE locales_gossip_menu_option SET option_text_loc1='하수구' WHERE menu_id=10056 AND id=4; /* option_text: Sewers */
UPDATE locales_gossip_menu_option SET option_text_loc1='상업 지구' WHERE menu_id=10056 AND id=5; /* option_text: Trade District */
UPDATE locales_gossip_menu_option SET option_text_loc1='마력의 사전' WHERE menu_id=10056 AND id=11; /* option_text: Lexicon of Power */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=10078 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=10078 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=10078 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=10078 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=10078 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=10078 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=10078 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=10078 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=10078 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='보석세공 상점' WHERE menu_id=10078 AND id=9; /* option_text: Jewelcrafting */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=10078 AND id=10; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=10078 AND id=11; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=10078 AND id=12; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=10078 AND id=13; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='비행 교관' WHERE menu_id=10082 AND id=2; /* option_text: Cold Weather Flying Trainer */
UPDATE locales_gossip_menu_option SET option_text_loc1='순간이동 전문 마법사' WHERE menu_id=10082 AND id=3; /* option_text: Portal Trainer */
UPDATE locales_gossip_menu_option SET option_text_loc1='상급 마법사' WHERE menu_id=10082 AND id=3; /* option_text: Mage Trainer */
UPDATE locales_gossip_menu_option SET option_text_loc1='하수구' WHERE menu_id=10084 AND id=2; /* option_text: Sewers */
UPDATE locales_gossip_menu_option SET option_text_loc1='하수구' WHERE menu_id=10089 AND id=2; /* option_text: Sewers */
UPDATE locales_gossip_menu_option SET option_text_loc1='여관' WHERE menu_id=10090 AND id=0; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc1='은행' WHERE menu_id=10090 AND id=1; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc1='투기장' WHERE menu_id=10106 AND id=0; /* option_text: Arena */
UPDATE locales_gossip_menu_option SET option_text_loc1='은행' WHERE menu_id=10106 AND id=1; /* option_text: Bank */
UPDATE locales_gossip_menu_option SET option_text_loc1='여관' WHERE menu_id=10106 AND id=2; /* option_text: Inn */
UPDATE locales_gossip_menu_option SET option_text_loc1='천 방어구 상점' WHERE menu_id=10170 AND id=0; /* option_text: Cloth Armor */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽 방어구 상점' WHERE menu_id=10170 AND id=1; /* option_text: Leather Armor */
UPDATE locales_gossip_menu_option SET option_text_loc1='사슬 방어구 상점' WHERE menu_id=10170 AND id=2; /* option_text: Mail Armor */
UPDATE locales_gossip_menu_option SET option_text_loc1='방패 상점' WHERE menu_id=10170 AND id=4; /* option_text: Shields */
UPDATE locales_gossip_menu_option SET option_text_loc1='일용품 상인' WHERE menu_id=10173 AND id=5; /* option_text: General Goods */
UPDATE locales_gossip_menu_option SET option_text_loc1='전문 보석세공인' WHERE menu_id=10173 AND id=6; /* option_text: Jewelcrafting Trainer */
UPDATE locales_gossip_menu_option SET option_text_loc1='과자 및 빵 상인' WHERE menu_id=10173 AND id=8; /* option_text: Pie, Pastry & Cakes */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법 재료 및 신비한 물건 상인' WHERE menu_id=10173 AND id=9; /* option_text: Reagents & Magical Goods */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법 재료 상인' WHERE menu_id=10173 AND id=9; /* option_text: Reagents */
UPDATE locales_gossip_menu_option SET option_text_loc1='직업용품 상인' WHERE menu_id=10173 AND id=11; /* option_text: Trade Supplies */
UPDATE locales_gossip_menu_option SET option_text_loc1='무기 상점' WHERE menu_id=10173 AND id=13; /* option_text: Weapons */
UPDATE locales_gossip_menu_option SET option_text_loc1='경매장' WHERE menu_id=10265 AND id=0; /* option_text: Auction House */
UPDATE locales_gossip_menu_option SET option_text_loc1='히포그리프 조련사' WHERE menu_id=10265 AND id=2; /* option_text: Hippogryph Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='길드 사무관' WHERE menu_id=10265 AND id=3; /* option_text: Guild Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='우체통' WHERE menu_id=10265 AND id=5; /* option_text: Mailbox */
UPDATE locales_gossip_menu_option SET option_text_loc1='야수 관리인' WHERE menu_id=10265 AND id=6; /* option_text: Stable Master */
UPDATE locales_gossip_menu_option SET option_text_loc1='전투모병관' WHERE menu_id=10265 AND id=8; /* option_text: Battlemaster */
UPDATE locales_gossip_menu_option SET option_text_loc1='마력의 사전' WHERE menu_id=10265 AND id=11; /* option_text: Lexicon of Power */
UPDATE locales_gossip_menu_option SET option_text_loc1='북풍의 땅' WHERE menu_id=10668 AND id=0; /* option_text: Borean Tundra */
UPDATE locales_gossip_menu_option SET option_text_loc1='울부짖는 협만' WHERE menu_id=10668 AND id=1; /* option_text: Howling Fjord */
UPDATE locales_gossip_menu_option SET option_text_loc1='연금술 상점' WHERE menu_id=10767 AND id=0; /* option_text: Alchemy */
UPDATE locales_gossip_menu_option SET option_text_loc1='대장기술' WHERE menu_id=10767 AND id=1; /* option_text: Blacksmithing */
UPDATE locales_gossip_menu_option SET option_text_loc1='요리용품점' WHERE menu_id=10767 AND id=2; /* option_text: Cooking */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법부여용품점' WHERE menu_id=10767 AND id=3; /* option_text: Enchanting */
UPDATE locales_gossip_menu_option SET option_text_loc1='기술용품점' WHERE menu_id=10767 AND id=4; /* option_text: Engineering */
UPDATE locales_gossip_menu_option SET option_text_loc1='응급치료원' WHERE menu_id=10767 AND id=5; /* option_text: First Aid */
UPDATE locales_gossip_menu_option SET option_text_loc1='낚시 상점' WHERE menu_id=10767 AND id=6; /* option_text: Fishing */
UPDATE locales_gossip_menu_option SET option_text_loc1='약초채집' WHERE menu_id=10767 AND id=7; /* option_text: Herbalism */
UPDATE locales_gossip_menu_option SET option_text_loc1='주문각인' WHERE menu_id=10767 AND id=8; /* option_text: Inscription */
UPDATE locales_gossip_menu_option SET option_text_loc1='가죽세공용품점' WHERE menu_id=10767 AND id=9; /* option_text: Leatherworking */
UPDATE locales_gossip_menu_option SET option_text_loc1='채광용품 및 보석세공점' WHERE menu_id=10767 AND id=10; /* option_text: Mining */
UPDATE locales_gossip_menu_option SET option_text_loc1='무두질' WHERE menu_id=10767 AND id=11; /* option_text: Skinning */
UPDATE locales_gossip_menu_option SET option_text_loc1='재봉용품점' WHERE menu_id=10767 AND id=12; /* option_text: Tailoring */
UPDATE locales_gossip_menu_option SET option_text_loc1='마법사' WHERE menu_id=10768 AND id=0; /* option_text: Mage */
UPDATE locales_gossip_menu_option SET option_text_loc1='성기사' WHERE menu_id=10768 AND id=1; /* option_text: Paladin */
UPDATE locales_gossip_menu_option SET option_text_loc1='사제' WHERE menu_id=10768 AND id=2; /* option_text: Priest */
UPDATE locales_gossip_menu_option SET option_text_loc1='도적' WHERE menu_id=10768 AND id=3; /* option_text: Rogue */
UPDATE locales_gossip_menu_option SET option_text_loc1='흑마법사' WHERE menu_id=10768 AND id=4; /* option_text: Warlock */
UPDATE locales_gossip_menu_option SET option_text_loc1='전사' WHERE menu_id=10768 AND id=5; /* option_text: Warrior */
UPDATE locales_gossip_menu_option SET option_text_loc1='미용사' WHERE menu_id=10769 AND id=2; /* option_text: Barber */
UPDATE locales_gossip_menu_option SET option_text_loc1='자물쇠 상인' WHERE menu_id=10769 AND id=7; /* option_text: Locksmith */

SET NAMES 'latin1';
