-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE locales_gossip_menu_option SET option_text_loc9='I would like to inform the secret code to get a pet, murloc.',box_text_loc9='2222' WHERE menu_id=7034 AND id=0;
UPDATE locales_gossip_menu_option SET option_text_loc9='Here\'s a gold, buy yourself something nice.',box_text_loc9='Do you really want to bribe Olga?' WHERE menu_id=9014 AND id=0;
UPDATE locales_gossip_menu_option SET option_text_loc9='Visit a mailbox.',box_text_loc9='Are you sure you wish to purchase a Dual Talent Specialization?' WHERE menu_id=10318 AND id=2;
UPDATE locales_gossip_menu_option SET option_text_loc9='Purchase a Dual Talent Specialization.',box_text_loc9='Are you sure you wish to purchase a Dual Talent Specialization?' WHERE menu_id=10371 AND id=0;
UPDATE locales_gossip_menu_option SET option_text_loc9='I no longer wish to gain experience.',box_text_loc9='Are you certain you wish to stop gaining experience?' WHERE menu_id=10638 AND id=0;

SET NAMES 'latin1';
