-- File generated by MOTE (Mangos Online Translation Editor) v0.01
SET NAMES 'utf8';
UPDATE locales_item SET description_loc9='Teaches you how to cook Westfall Stew.' WHERE entry=728; /* description: Teaches you how to cook Westfall Stew. */
UPDATE locales_item SET description_loc9='This large crate is sealed tight, but it reeks of dead things.' WHERE entry=1349; /* description: This large crate is sealed tight, but it reeks of dead things. */
UPDATE locales_item SET name_loc9='The First Troll Legend',description_loc9='Moon over the Vale' WHERE entry=2005; /* name: The First Troll Legend */ .* description: Moon over the Vale */
UPDATE locales_item SET name_loc9='The Second Troll Legend',description_loc9='Gri\'lek the Wanderer' WHERE entry=2006; /* name: The Second Troll Legend */ .* description: Gri\'lek the Wanderer */
UPDATE locales_item SET name_loc9='The Third Troll Legend',description_loc9='Fall of Gurubashi' WHERE entry=2007; /* name: The Third Troll Legend */ .* description: Fall of Gurubashi */
UPDATE locales_item SET name_loc9='The Fourth Troll Legend',description_loc9='The Emperor\'s Tomb' WHERE entry=2008; /* name: The Fourth Troll Legend */ .* description: The Emperor\'s Tomb */
UPDATE locales_item SET description_loc9='In remarkably good condition all things considered.' WHERE entry=5424; /* description: In remarkably good condition all things considered. */
UPDATE locales_item SET description_loc9='Something doesn\'t seem quite right about the soot-covered stone.' WHERE entry=5493; /* description: Something doesn\'t seem quite right about the soot-covered stone. */
UPDATE locales_item SET description_loc9='Venture Company Supplies' WHERE entry=6357; /* description: Venture Company Supplies */
UPDATE locales_item SET description_loc9='By Magus Tirth' WHERE entry=7274; /* description: By Magus Tirth */
UPDATE locales_item SET description_loc9='Use near a mana rift disturbance' WHERE entry=7308; /* description: Use near a mana rift disturbance */
UPDATE locales_item SET description_loc9='It\'s huge!' WHERE entry=8564; /* description: It\'s huge! */
UPDATE locales_item SET description_loc9='The flame never falters' WHERE entry=10515; /* description: The flame never falters */
UPDATE locales_item SET description_loc9='Bears the mark of Kalaran the Deceiver' WHERE entry=10569; /* description: Bears the mark of Kalaran the Deceiver */
UPDATE locales_item SET description_loc9='Etched into the face of the hammer are the letters: F.F.F.' WHERE entry=10999; /* description: Etched into the face of the hammer are the letters: F.F.F. */
UPDATE locales_item SET description_loc9='Gor\'tesh\'s severed head, propped up on a pike.' WHERE entry=11079; /* description: Gor\'tesh\'s severed head, propped up on a pike. */
UPDATE locales_item SET description_loc9='Squishy, Smelly, Slimy' WHERE entry=11080; /* description: Squishy, Smelly, Slimy */
UPDATE locales_item SET description_loc9='Property of Marshal Expeditions.' WHERE entry=11112; /* description: Property of Marshal Expeditions. */
UPDATE locales_item SET description_loc9='Property of Marshal Expeditions.' WHERE entry=11113; /* description: Property of Marshal Expeditions. */
UPDATE locales_item SET description_loc9='Something seems to shake from within' WHERE entry=12467; /* description: Something seems to shake from within */
UPDATE locales_item SET description_loc9='A ritual candle from the depths of Jaedenar, new home of the Shadow Council.' WHERE entry=12924; /* description: A ritual candle from the depths of Jaedenar, new home of the Shadow Council. */
UPDATE locales_item SET description_loc9='The pages are tattered and worn...' WHERE entry=13313; /* description: The pages are tattered and worn... */
UPDATE locales_item SET description_loc9='Carries the Seal of Barov.' WHERE entry=13448; /* description: Carries the Seal of Barov. */
UPDATE locales_item SET description_loc9='Carries the Seal of Barov.' WHERE entry=13450; /* description: Carries the Seal of Barov. */
UPDATE locales_item SET description_loc9='Carries the Seal of Barov.' WHERE entry=13451; /* description: Carries the Seal of Barov. */
UPDATE locales_item SET description_loc9='Carries the Seal of Barov.' WHERE entry=13471; /* description: Carries the Seal of Barov. */
UPDATE locales_item SET description_loc9='All of the pages are torn out.' WHERE entry=13585; /* description: All of the pages are torn out. */
UPDATE locales_item SET description_loc9='Not to be confused with gloom weed, womb weed, or broom weed.  Or doom seed.' WHERE entry=13702; /* description: Not to be confused with gloom weed, womb weed, or broom weed.  Or doom seed. */
UPDATE locales_item SET description_loc9='Order of the Silver Hand' WHERE entry=14625; /* description: Order of the Silver Hand */
UPDATE locales_item SET description_loc9='Keep away from fire.' WHERE entry=15736; /* description: Keep away from fire. */
UPDATE locales_item SET description_loc9='This book emits a faint glow.' WHERE entry=15847; /* description: This book emits a faint glow. */
UPDATE locales_item SET description_loc9='Magic stirs deep inside.' WHERE entry=16581; /* description: Magic stirs deep inside. */
UPDATE locales_item SET description_loc9='Keep away from Thorium Brotherhood.' WHERE entry=18922; /* description: Keep away from Thorium Brotherhood. */
UPDATE locales_item SET description_loc9='Chapter I' WHERE entry=21103; /* description: Chapter I */
UPDATE locales_item SET description_loc9='Chapter II' WHERE entry=21104; /* description: Chapter II */
UPDATE locales_item SET description_loc9='Chapter III' WHERE entry=21105; /* description: Chapter III */
UPDATE locales_item SET description_loc9='Chapter IV' WHERE entry=21106; /* description: Chapter IV */
UPDATE locales_item SET description_loc9='Chapter V' WHERE entry=21107; /* description: Chapter V */
UPDATE locales_item SET description_loc9='Chapter VI' WHERE entry=21108; /* description: Chapter VI */
UPDATE locales_item SET description_loc9='Chapter VII' WHERE entry=21109; /* description: Chapter VII */
UPDATE locales_item SET description_loc9='Chapter VIII' WHERE entry=21110; /* description: Chapter VIII */
UPDATE locales_item SET description_loc9='Amazingly, between the ghouls and the corrosive slime, it appears undamaged.' WHERE entry=22583; /* description: Amazingly, between the ghouls and the corrosive slime, it appears undamaged. */
UPDATE locales_item SET description_loc9='These contain a detailed map and tactical situation for An\'daroth.' WHERE entry=22590; /* description: These contain a detailed map and tactical situation for An\'daroth. */
UPDATE locales_item SET description_loc9='These contain a detailed map and tactical situation for An\'owyn.' WHERE entry=22591; /* description: These contain a detailed map and tactical situation for An\'owyn. */
UPDATE locales_item SET description_loc9='These plans talk of using the high elf moon crystals to scry upon the blood elves!' WHERE entry=22592; /* description: These plans talk of using the high elf moon crystals to scry upon the blood elves! */
UPDATE locales_item SET description_loc9='It shakes nonstop, as though the hatchling could emerge at any moment.' WHERE entry=23217; /* description: It shakes nonstop, as though the hatchling could emerge at any moment. */
UPDATE locales_item SET description_loc9='Although torn and stained, this pack shows unmistakable signs of blood elf craftsmanship.' WHERE entry=23343; /* description: Although torn and stained, this pack shows unmistakable signs of blood elf craftsmanship. */
UPDATE locales_item SET description_loc9='An unhatched gryphon egg rescued from the Witherbark trolls.' WHERE entry=23694; /* description: An unhatched gryphon egg rescued from the Witherbark trolls. */
UPDATE locales_item SET description_loc9='A shimmering silver vessel somehow untarnished by its long exposure to corrupt influences.' WHERE entry=23760; /* description: A shimmering silver vessel somehow untarnished by its long exposure to corrupt influences. */
UPDATE locales_item SET description_loc9='The equipment appears unharmed, if a bit slimy.' WHERE entry=23830; /* description: The equipment appears unharmed, if a bit slimy. */
UPDATE locales_item SET description_loc9='A bright, juicy fruit favored by the elekk.' WHERE entry=23927; /* description: A bright, juicy fruit favored by the elekk. */
UPDATE locales_item SET description_loc9='A little rusty, but it appears to be in working order.' WHERE entry=23981; /* description: A little rusty, but it appears to be in working order. */
UPDATE locales_item SET description_loc9='These mushroom remains are desiccated and have likely been here a while.' WHERE entry=24233; /* description: These mushroom remains are desiccated and have likely been here a while. */
UPDATE locales_item SET description_loc9='It certainly has a \'passionate\' fragrance.' WHERE entry=24246; /* description: It certainly has a \'passionate\' fragrance. */
UPDATE locales_item SET description_loc9='A soft, spongy fungus that can explode into a toxic cloud if not handled properly.' WHERE entry=24468; /* description: A soft, spongy fungus that can explode into a toxic cloud if not handled properly. */
UPDATE locales_item SET description_loc9='A cage filled with baby murlocs.' WHERE entry=24470; /* description: A cage filled with baby murlocs. */
UPDATE locales_item SET description_loc9='Soft blue light pulses within the crystal.' WHERE entry=25635; /* description: Soft blue light pulses within the crystal. */
UPDATE locales_item SET description_loc9='The globe emits a soft blue glow.' WHERE entry=25638; /* description: The globe emits a soft blue glow. */
UPDATE locales_item SET description_loc9='Dark energies swirl within the orb.' WHERE entry=25642; /* description: Dark energies swirl within the orb. */
UPDATE locales_item SET description_loc9='It\'s sealed.  Maybe you should shake it?' WHERE entry=25727; /* description: It\'s sealed.  Maybe you should shake it? */
UPDATE locales_item SET description_loc9='The locations of the Allerian Stronghold and Stonebreaker Hold are clearly marked on this map along with a series of bold ink strokes and assorted orders.' WHERE entry=25765; /* description: The locations of the Allerian Stronghold and Stonebreaker Hold are clearly marked on this map along with a series of bold ink strokes and assorted orders. */
UPDATE locales_item SET description_loc9='The remains are suffused with a soft, white glow.' WHERE entry=25842; /* description: The remains are suffused with a soft, white glow. */
UPDATE locales_item SET description_loc9='A scroll containing stories from the life of the great arakkoa hero Terokk.' WHERE entry=27634; /* description: A scroll containing stories from the life of the great arakkoa hero Terokk. */
UPDATE locales_item SET description_loc9='You wonder if it\'s safe to handle these while they\'re still glowing?' WHERE entry=28364; /* description: You wonder if it\'s safe to handle these while they\'re still glowing? */
UPDATE locales_item SET description_loc9='Emanates with a sickly, evil aura.' WHERE entry=29477; /* description: Emanates with a sickly, evil aura. */
UPDATE locales_item SET description_loc9='You can\'t quite make out what is etched upon this old Thunderlord clan tablet.' WHERE entry=30434; /* description: You can\'t quite make out what is etched upon this old Thunderlord clan tablet. */
UPDATE locales_item SET description_loc9='The large spear vibrates with immense power.' WHERE entry=30435; /* description: The large spear vibrates with immense power. */
UPDATE locales_item SET description_loc9='Whatever\'s in it, it feels powerful.' WHERE entry=31349; /* description: Whatever\'s in it, it feels powerful. */
UPDATE locales_item SET description_loc9='Crates filled with leaflets denouncing Lady Jaina and encouraging Theramore guards to join with the deserters.' WHERE entry=33008; /* description: Crates filled with leaflets denouncing Lady Jaina and encouraging Theramore guards to join with the deserters. */
UPDATE locales_item SET description_loc9='This diving gear would certainly kill anyone who tried to use it in its present condition.' WHERE entry=33038; /* description: This diving gear would certainly kill anyone who tried to use it in its present condition. */
UPDATE locales_item SET description_loc9='Grimy, rusty tools that only a desperate person would attempt to use.' WHERE entry=33039; /* description: Grimy, rusty tools that only a desperate person would attempt to use. */
UPDATE locales_item SET description_loc9='The nearly rancid remains from a recent hunting trip.' WHERE entry=33070; /* description: The nearly rancid remains from a recent hunting trip. */
UPDATE locales_item SET description_loc9='This doesn\'t do a body good....' WHERE entry=33083; /* description: This doesn\'t do a body good.... */
UPDATE locales_item SET description_loc9='This old banner is tattered and foul-smelling, but nonetheless embodies Stonemaul pride.' WHERE entry=33095; /* description: This old banner is tattered and foul-smelling, but nonetheless embodies Stonemaul pride. */
UPDATE locales_item SET description_loc9='It seems to have survived the crash intact... mostly.' WHERE entry=33163; /* description: It seems to have survived the crash intact... mostly. */
UPDATE locales_item SET description_loc9='Can only be used at the Ancestral Grounds in Nagrand.' WHERE entry=33851; /* description: Can only be used at the Ancestral Grounds in Nagrand. */
UPDATE locales_item SET description_loc9='Requires the smoldering corpse of an Abyssal Flamebringer.' WHERE entry=33852; /* description: Requires the smoldering corpse of an Abyssal Flamebringer. */
UPDATE locales_item SET description_loc9='Drop it then rock it!' WHERE entry=34051; /* description: Drop it then rock it! */
UPDATE locales_item SET description_loc9='This egg is hatching into something.' WHERE entry=39878; /* description: This egg is hatching into something. */
UPDATE locales_item SET description_loc9='A fallen soldier, stripped of flesh.' WHERE entry=43609; /* description: A fallen soldier, stripped of flesh. */
UPDATE locales_item SET description_loc9='Just holding this heavy and unwieldy tome makes you feel a little clumsy....' WHERE entry=45849; /* description: Just holding this heavy and unwieldy tome makes you feel a little clumsy.... */

SET NAMES 'latin1';
