-- File generated by Mangos Online Translation Editor (MOTE) v2.06
SET NAMES 'utf8';
UPDATE `trans_words`SET `content_loc9`='Here\'s a gold, buy yourself something nice.' WHERE `word_id`=128310; -- locales_gossip_menu_option - option_text : menu_id=9014-id=0
UPDATE `trans_words`SET `content_loc9`='Do you really want to bribe Olga?' WHERE `word_id`=128311; -- locales_gossip_menu_option - box_text : menu_id=9014-id=0
UPDATE `trans_words`SET `content_loc9`='Purchase a Dual Talent Specialization.' WHERE `word_id`=129155; -- locales_gossip_menu_option - option_text : menu_id=10371-id=0
UPDATE `trans_words`SET `content_loc9`='Are you sure you wish to purchase a Dual Talent Specialization?' WHERE `word_id`=129156; -- locales_gossip_menu_option - box_text : menu_id=10371-id=0
UPDATE `trans_words`SET `content_loc9`='I no longer wish to gain experience.' WHERE `word_id`=128963; -- locales_gossip_menu_option - option_text : menu_id=10638-id=0
UPDATE `trans_words`SET `content_loc9`='Are you certain you wish to stop gaining experience?' WHERE `word_id`=128964; -- locales_gossip_menu_option - box_text : menu_id=10638-id=0

SET NAMES 'latin1';
