-- File generated by Mangos Online Translation Editor (MOTE) v1.90
SET NAMES 'utf8';
UPDATE gossip_texts SET content_loc6='[PH] SD2 unknown text' WHERE entry=-3000000; /* content: [PH] SD2 unknown text */
UPDATE gossip_texts SET content_loc6='Taruk send me to collect what you owe.' WHERE entry=-3000101; /* content: Taruk send me to collect what you owe. */
UPDATE gossip_texts SET content_loc6='I am ready to travel to you village now.' WHERE entry=-3000103; /* content: I am ready to travel to you village now. */
UPDATE gossip_texts SET content_loc6='<Check for pulse...>' WHERE entry=-3000104; /* content: <Check for pulse...> */
UPDATE gossip_texts SET content_loc6='Why... yes, of course. I\'ve something to show you right inside this building, Mr. Anvilward.' WHERE entry=-3000110; /* content: Why... yes, of course. I\'ve something to show you right inside this building, Mr. Anvilward. */
UPDATE gossip_texts SET content_loc6='I\'m ready - let\'s get out of here.' WHERE entry=-3000112; /* content: I\'m ready - let\'s get out of here. */
UPDATE gossip_texts SET content_loc6='Go on, you\'re free. Get out of here!' WHERE entry=-3000113; /* content: Go on, you\'re free. Get out of here! */
UPDATE gossip_texts SET content_loc6='I am ready, Anchorite. Let us begin the exorcism.' WHERE entry=-3006669; /* content: I am ready, Anchorite. Let us begin the exorcism. */
UPDATE gossip_texts SET content_loc6='Your bondage is at an end, Doom\'rel. I challenge you!' WHERE entry=-3230002; /* content: Your bondage is at an end, Doom\'rel. I challenge you! */
UPDATE gossip_texts SET content_loc6='You challenged us and we have come. Where is this master you speak of?' WHERE entry=-3409002; /* content: You challenged us and we have come. Where is this master you speak of? */
UPDATE gossip_texts SET content_loc6='Teleport me to the Guardian\'s Library' WHERE entry=-3532000; /* content: Teleport me to the Guardian\'s Library */
UPDATE gossip_texts SET content_loc6='What phat lewtz you have grandmother?' WHERE entry=-3532005; /* content: What phat lewtz you have grandmother? */
UPDATE gossip_texts SET content_loc6='Control Human Charger' WHERE entry=-3532013; /* content: Control Human Charger */
UPDATE gossip_texts SET content_loc6='Control Conjured Water Elemental' WHERE entry=-3532014; /* content: Control Conjured Water Elemental */
UPDATE gossip_texts SET content_loc6='We\'ll get you out. Taretha. Don\'t worry. I doubt the wizard would wander too far away.' WHERE entry=-3560006; /* content: We\'ll get you out. Taretha. Don\'t worry. I doubt the wizard would wander too far away. */
UPDATE gossip_texts SET content_loc6='Chromie, you and I both know what\'s going to happen in this time stream. We\'ve seen this all before.$B$BCan you just skip us ahead to all the real action?' WHERE entry=-3595006; /* content: Chromie, you and I both know what\'s going to happen in this time stream. We\'ve seen this all before.$B$BCan you just skip us ahead to all the real action? */
UPDATE gossip_texts SET content_loc6='Let\'s move Brann, enough of the history lessons!' WHERE entry=-3599001; /* content: Let\'s move Brann, enough of the history lessons! */
UPDATE gossip_texts SET content_loc6='Activate the crystals when we get in trouble, right?' WHERE entry=-3608000; /* content: Activate the crystals when we get in trouble, right? */
UPDATE gossip_texts SET content_loc6='Val\'kyr? We\'re ready for them' WHERE entry=-3649008; /* content: Val\'kyr? We\'re ready for them */
UPDATE gossip_texts SET content_loc6='I am ready. However, I\'d like to skip the pageantry.' WHERE entry=-3650001; /* content: I am ready. However, I\'d like to skip the pageantry. */

SET NAMES 'latin1';
