-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc7`='$N versus the ferocious clefthoof, Brokentoe!' WHERE `word_id` = 7594; -- db_script_string - content : entry=2000000003
UPDATE `trans_words` SET `content_loc7`='$N, please take a look at the sample of the Vylestem vine that I took from the caverns, so thet you know what to look for...' WHERE `word_id` = 8202; -- db_script_string - content : entry=2000005664
UPDATE `trans_words` SET `content_loc7`='$R, do you know who Kolphis Darkscale is?' WHERE `word_id` = 7725; -- db_script_string - content : entry=2000000185
UPDATE `trans_words` SET `content_loc7`='%s cautiously approaches Wather Elaira.' WHERE `word_id` = 8210; -- db_script_string - content : entry=2000005672
UPDATE `trans_words` SET `content_loc7`='%s combines the herbs with the moonwell water to create the Ward of Waking' WHERE `word_id` = 8205; -- db_script_string - content : entry=2000005667
UPDATE `trans_words` SET `content_loc7`='%s falls into drunken sleep.' WHERE `word_id` = 7828; -- db_script_string - content : entry=2000000342
UPDATE `trans_words` SET `content_loc7`='%s is chasing you!' WHERE `word_id` = 4035; -- db_script_string - content : entry=2000005546
UPDATE `trans_words` SET `content_loc7`='%s listens to Sigilbringer\'s report...' WHERE `word_id` = 7252; -- db_script_string - content : entry=2000005777
UPDATE `trans_words` SET `content_loc7`='%s reads from the book of the dead.' WHERE `word_id` = 268248; -- db_script_string - content : entry=2000000488
UPDATE `trans_words` SET `content_loc7`='%s scurries away, attempting to flee from Twinkle.' WHERE `word_id` = 7620; -- db_script_string - content : entry=2000000391
UPDATE `trans_words` SET `content_loc7`='%s takes big swig of ale.' WHERE `word_id` = 6997; -- db_script_string - content : entry=2000000119
UPDATE `trans_words` SET `content_loc7`='%s wakes up and slowly rises to his feet.' WHERE `word_id` = 7829; -- db_script_string - content : entry=2000000343
UPDATE `trans_words` SET `content_loc7`='...And then the tauren said, "13 INCHES!"' WHERE `word_id` = 7080; -- db_script_string - content : entry=2000005032
UPDATE `trans_words` SET `content_loc7`='A History... Hmmmm... Let me examine this for a moment.' WHERE `word_id` = 7363; -- db_script_string - content : entry=2000000523
UPDATE `trans_words` SET `content_loc7`='Ah, I see it now in your mind. This is the work of one of my former students... Mehlar Dawnblade. It is sad to know that his heart has turned so dark.' WHERE `word_id` = 7810; -- db_script_string - content : entry=2000000320
UPDATE `trans_words` SET `content_loc7`='Ah, this must be him now... no?' WHERE `word_id` = 7070; -- db_script_string - content : entry=2000005018
UPDATE `trans_words` SET `content_loc7`='Ahh, much appreciated, Corbett. We\'ll get these on the racks immediately.' WHERE `word_id` = 7019; -- db_script_string - content : entry=2000000148
UPDATE `trans_words` SET `content_loc7`='Aman dissipates before your eyes.' WHERE `word_id` = 7998; -- db_script_string - content : entry=2000005361
UPDATE `trans_words` SET `content_loc7`='Amazing! I think I have found it, $N.' WHERE `word_id` = 7365; -- db_script_string - content : entry=2000000525
UPDATE `trans_words` SET `content_loc7`='An Avatar of Terokk! To arms!' WHERE `word_id` = 7599; -- db_script_string - content : entry=2000000025
UPDATE `trans_words` SET `content_loc7`='Anaya\'s soft voice trails away into the mists. "Know that I love you always..."' WHERE `word_id` = 7428; -- db_script_string - content : entry=2000005344
UPDATE `trans_words` SET `content_loc7`='And even more!' WHERE `word_id` = 7598; -- db_script_string - content : entry=2000000024
UPDATE `trans_words` SET `content_loc7`='And that\'s how Lother killed thirty six orcs with his bare hands!' WHERE `word_id` = 7099; -- db_script_string - content : entry=2000005115
UPDATE `trans_words` SET `content_loc7`='And who do we have here?  No doubt th... crzzzk ...ade this communication possible?  I give you greetings fro... psshzzzk... Azure Watch.' WHERE `word_id` = 268219; -- db_script_string - content : entry=2000005839
UPDATE `trans_words` SET `content_loc7`='And... I we do not?' WHERE `word_id` = 8052; -- db_script_string - content : entry=2000005467
UPDATE `trans_words` SET `content_loc7`='Ask me how you can get a free drink at the Blue Recluse!' WHERE `word_id` = 7149; -- db_script_string - content : entry=2000005191
UPDATE `trans_words` SET `content_loc7`='Aye Remulos, prepare the mortal races.' WHERE `word_id` = 7864; -- db_script_string - content : entry=2000000382
UPDATE `trans_words` SET `content_loc7`='Back to the topic... we should focus our attention on these manaforges. We need to learn what the enemy is doing with them and why.' WHERE `word_id` = 7971; -- db_script_string - content : entry=2000005276
UPDATE `trans_words` SET `content_loc7`='Bah! $N, this foot won\'t budge!' WHERE `word_id` = 7704; -- db_script_string - content : entry=2000000133
UPDATE `trans_words` SET `content_loc7`='Be patient $N. The torch is almost complete.' WHERE `word_id` = 6948; -- db_script_string - content : entry=2000000019
UPDATE `trans_words` SET `content_loc7`='Bijou lost! SQUAWK! *cough' WHERE `word_id` = 7062; -- db_script_string - content : entry=2000005002
UPDATE `trans_words` SET `content_loc7`='Bogling rises from the soil!' WHERE `word_id` = 7695; -- db_script_string - content : entry=2000000089
UPDATE `trans_words` SET `content_loc7`='Borgrim, this is no time for drinking. We just got here. We need to get settled in.' WHERE `word_id` = 8215; -- db_script_string - content : entry=2000005679
UPDATE `trans_words` SET `content_loc7`='But isn\'t that what caused the initial problems with Adept Syleria\'s magical formula?' WHERE `word_id` = 7121; -- db_script_string - content : entry=2000005160
UPDATE `trans_words` SET `content_loc7`='BY THE LIGHT OF ELUNE! Eredar! Cursed demons, what have you to me? I have not come alone, we will fight you as we have in the past! I...' WHERE `word_id` = 7636; -- db_script_string - content : entry=2000000660
UPDATE `trans_words` SET `content_loc7`='Cenarius fights at my side. Illidan sits atop his throne in Outland - brooding. I\'m afraid that the loss to Arthas proved to be his breaking point. Madness has embraced him, Remulos. He replays the events in his mind a thousand times per day, but in his mind, he is the victor and Arthas is utterly defeated. He is too far gone, old friend. I fear that the time may soon come that our bond is tested and it will not be as it was at the Well in Zin-Azshari.' WHERE `word_id` = 7316; -- db_script_string - content : entry=2000000384
UPDATE `trans_words` SET `content_loc7`='Champion Vranesh arches a sculpted brow at the guards, a disapproving scowl on his face.' WHERE `word_id` = 8322; -- db_script_string - content : entry=2000005822
UPDATE `trans_words` SET `content_loc7`='Champion Vranesh glances from guard to guard.' WHERE `word_id` = 8323; -- db_script_string - content : entry=2000005823
UPDATE `trans_words` SET `content_loc7`='Champion Vranesh inclines his head slightly to the pair of guardians in greeting.' WHERE `word_id` = 8325; -- db_script_string - content : entry=2000005825
UPDATE `trans_words` SET `content_loc7`='Champion Vranesh surveys the small ranger practice ground with a condescending smirk.' WHERE `word_id` = 8324; -- db_script_string - content : entry=2000005824
UPDATE `trans_words` SET `content_loc7`='Children if you would please follow me, we will now be going to see the keep where King Anduin Wrynn himself sits on this throne.' WHERE `word_id` = 7113; -- db_script_string - content : entry=2000005136
UPDATE `trans_words` SET `content_loc7`='Come to my lair, whelp! Come to me and pay for your insolecne!' WHERE `word_id` = 8010; -- db_script_string - content : entry=2000005406
UPDATE `trans_words` SET `content_loc7`='Come, $N. The lake is around the bend.' WHERE `word_id` = 7858; -- db_script_string - content : entry=2000000375
UPDATE `trans_words` SET `content_loc7`='Corbett, dear. Harlan needs a load of knitted shirts and pants as soon as we can manage.' WHERE `word_id` = 7010; -- db_script_string - content : entry=2000000139
UPDATE `trans_words` SET `content_loc7`='Damnit. How are we ever going to make it through their security measures?' WHERE `word_id` = 8003; -- db_script_string - content : entry=2000005399
UPDATE `trans_words` SET `content_loc7`='Deja vu. For a moment I thought I was back home... before the plague...' WHERE `word_id` = 7093; -- db_script_string - content : entry=2000005108
UPDATE `trans_words` SET `content_loc7`='Denalan hurries to his planter.' WHERE `word_id` = 7696; -- db_script_string - content : entry=2000000093
UPDATE `trans_words` SET `content_loc7`='Denalan plants fruit seeds.' WHERE `word_id` = 7694; -- db_script_string - content : entry=2000000088
UPDATE `trans_words` SET `content_loc7`='Denalan removes the seeds from the Glowing Fruit...' WHERE `word_id` = 7692; -- db_script_string - content : entry=2000000086
UPDATE `trans_words` SET `content_loc7`='Derived from cutting edge Shattered Hand Offensive military technology, it blasts away stubborn stains with ease!' WHERE `word_id` = 7532; -- db_script_string - content : entry=2000005207
UPDATE `trans_words` SET `content_loc7`='Did you find something fun to chase around, Twinkle?' WHERE `word_id` = 7878; -- db_script_string - content : entry=2000000406
UPDATE `trans_words` SET `content_loc7`='Drink this, you blue brute! Disobey me and I promise you a slow, painful death!' WHERE `word_id` = 7770; -- db_script_string - content : entry=2000000256
UPDATE `trans_words` SET `content_loc7`='Easier then I expected... the sigil of Thoradin is whole, once again.' WHERE `word_id` = 6994; -- db_script_string - content : entry=2000000118
UPDATE `trans_words` SET `content_loc7`='Even you must admit that your information from defectors is outdated and unreliable. Let us make calculated attacks on these manaforges and gather what information we can.' WHERE `word_id` = 7974; -- db_script_string - content : entry=2000005279
UPDATE `trans_words` SET `content_loc7`='Fear not! All fortunes can be discerned for those who know the way.' WHERE `word_id` = 7535; -- db_script_string - content : entry=2000005213
UPDATE `trans_words` SET `content_loc7`='Fizzles used to be a great wizard. But got turned into a rabbit when one of his spells went bad.' WHERE `word_id` = 7144; -- db_script_string - content : entry=2000005184
UPDATE `trans_words` SET `content_loc7`='Follow me, good $C. I\'ll have your barding done faster than I could down a Dwarven stout. Mmmm... stout.' WHERE `word_id` = 6975; -- db_script_string - content : entry=2000000063
UPDATE `trans_words` SET `content_loc7`='Follow, $N. I will soon begin the summoning...' WHERE `word_id` = 6954; -- db_script_string - content : entry=2000000029
UPDATE `trans_words` SET `content_loc7`='Freedom at last! I must return to Warsong at once!' WHERE `word_id` = 7897; -- db_script_string - content : entry=2000000560
UPDATE `trans_words` SET `content_loc7`='Gird yourself $N, for the demon in this orb is a fel beast.' WHERE `word_id` = 6956; -- db_script_string - content : entry=2000000032
UPDATE `trans_words` SET `content_loc7`='Glad to see you\'re doing so well, Harlan. And I hope to see you again soon' WHERE `word_id` = 7563; -- db_script_string - content : entry=2000000149
UPDATE `trans_words` SET `content_loc7`='Glory to the Sun K-- ah.... Silvermoon!' WHERE `word_id` = 8327; -- db_script_string - content : entry=2000005827
UPDATE `trans_words` SET `content_loc7`='Glowing Soulgem bursts open!' WHERE `word_id` = 6967; -- db_script_string - content : entry=2000000051
UPDATE `trans_words` SET `content_loc7`='Go, my servant. Send word of Stonetalon to Apothecary Zamah.' WHERE `word_id` = 7051; -- db_script_string - content : entry=2000000213
UPDATE `trans_words` SET `content_loc7`='Good day. Elling! Hullo Elaine! Let me have a wheel of blue cheese, eh?' WHERE `word_id` = 7024; -- db_script_string - content : entry=2000000153
UPDATE `trans_words` SET `content_loc7`='Greatmother Hawkwind gestures to the pitcher of water sitting on the edge of the well.' WHERE `word_id` = 7687; -- db_script_string - content : entry=2000000027
UPDATE `trans_words` SET `content_loc7`='Grimclaw begins to moan and roar at Terenthis while stomping his paws on the ground.' WHERE `word_id` = 7191; -- db_script_string - content : entry=2000005387
UPDATE `trans_words` SET `content_loc7`='Grimclaw roars at Terenthis more, but this time the druid seems to understand the bear.' WHERE `word_id` = 7187; -- db_script_string - content : entry=2000005391
UPDATE `trans_words` SET `content_loc7`='Grimclaw roars at Terenthis to get his attention.' WHERE `word_id` = 7194; -- db_script_string - content : entry=2000005385
UPDATE `trans_words` SET `content_loc7`='Grimclaw roars in acknowledgement at Terenthis.' WHERE `word_id` = 7185; -- db_script_string - content : entry=2000005393
UPDATE `trans_words` SET `content_loc7`='Havenshire is lost.' WHERE `word_id` = 7884; -- db_script_string - content : entry=2000000412
UPDATE `trans_words` SET `content_loc7`='Hear ye, denizens of Tanaris! Let it be known $N is an exalted member of the Mithril Order. A blacksmith of honor, dedication, and infinite patience. Three cheers for $N!' WHERE `word_id` = 6979; -- db_script_string - content : entry=2000000076
UPDATE `trans_words` SET `content_loc7`='Here\'s a beacon, $N. Keep it to yourself, if you\'re gonna find mutilated things that we need.' WHERE `word_id` = 7059; -- db_script_string - content : entry=2000000318
UPDATE `trans_words` SET `content_loc7`='Hey there, Belm! Give me a mug of Thunder Ale, and one for my good friend $N.' WHERE `word_id` = 6971; -- db_script_string - content : entry=2000000056
UPDATE `trans_words` SET `content_loc7`='Hey, harbringer, how\'s that research coming along? There might be an Ultra-Kinetic Waffle Iron in it for you if you\'re prompt with the results!' WHERE `word_id` = 6158; -- db_script_string - content : entry=2000005201
UPDATE `trans_words` SET `content_loc7`='Hey, you there. Want some candy?' WHERE `word_id` = 7492; -- db_script_string - content : entry=2000005052
UPDATE `trans_words` SET `content_loc7`='Hi Corbett! Here, you go! I trust business is faring well at your clothier shop...?' WHERE `word_id` = 7026; -- db_script_string - content : entry=2000000155
UPDATE `trans_words` SET `content_loc7`='Hmm... the readings on the gravimeteric distortions seem to have stabalized. We did it!' WHERE `word_id` = 7955; -- db_script_string - content : entry=2000005260
UPDATE `trans_words` SET `content_loc7`='Hold your tongue, knave! Do not dare use that tone with a priestess of the Light!' WHERE `word_id` = 7968; -- db_script_string - content : entry=2000005273
UPDATE `trans_words` SET `content_loc7`='How dare you take my eye! I will crush your soul and feed it to my blind and wimpering imps!' WHERE `word_id` = 8009; -- db_script_string - content : entry=2000005405
UPDATE `trans_words` SET `content_loc7`='How dare you trifle with my playthings!' WHERE `word_id` = 6543; -- db_script_string - content : entry=2000005441
UPDATE `trans_words` SET `content_loc7`='Hullo, Trias clan! A ball of your smoked mozzarella, if you please!' WHERE `word_id` = 7023; -- db_script_string - content : entry=2000000152
UPDATE `trans_words` SET `content_loc7`='I am going to practice and become a warrior like my father!' WHERE `word_id` = 7255; -- db_script_string - content : entry=2000005767
UPDATE `trans_words` SET `content_loc7`='I believe the Forsaken are misleading the allies of the Horde... wait... I feel so... dizzy...' WHERE `word_id` = 6995; -- db_script_string - content : entry=2000000121
UPDATE `trans_words` SET `content_loc7`='I can get back to Stronghold on my own, I think. Now that you bought me some time, I should be able to stealth out of here. Who ever you are... thank you. May Elune bless you always!' WHERE `word_id` = 7894; -- db_script_string - content : entry=2000000520
UPDATE `trans_words` SET `content_loc7`='I can\'t belive you imbeciles went to school for this! Does anybody here know what they\'re doing?' WHERE `word_id` = 7976; -- db_script_string - content : entry=2000005281
UPDATE `trans_words` SET `content_loc7`='I fear for the worst, old friend. Within the Dream we fight a new foe, born of an ancient evil. Ysera\'s noble brood has fallen victim to the old whisperings. It seems as if the Nightmare has broken through the realm to find a new host on Azeroth.' WHERE `word_id` = 7862; -- db_script_string - content : entry=2000000380
UPDATE `trans_words` SET `content_loc7`='I FEEL DEATH ALONGSIDE' WHERE `word_id` = 7546; -- db_script_string - content : entry=2000005231
UPDATE `trans_words` SET `content_loc7`='I guess I\'ll go find the athorities. If I\'m lucky they\'ll tell me it\'s the plague and that we\'re all going to die.' WHERE `word_id` = 8190; -- db_script_string - content : entry=2000005622
UPDATE `trans_words` SET `content_loc7`='I have awoken to a nightmare?' WHERE `word_id` = 7851; -- db_script_string - content : entry=2000000367
UPDATE `trans_words` SET `content_loc7`='I have created the totem. You, $N, must cleanse the well.' WHERE `word_id` = 7711; -- db_script_string - content : entry=2000000171
UPDATE `trans_words` SET `content_loc7`='I need to consult Noram and Horatio.' WHERE `word_id` = 6950; -- db_script_string - content : entry=2000000021
UPDATE `trans_words` SET `content_loc7`='I pity you Forsaken, Your soul is devoid of light.' WHERE `word_id` = 7771; -- db_script_string - content : entry=2000000257
UPDATE `trans_words` SET `content_loc7`='I raise my brew and hope to be rid of the likes of you! Cheers, you no good scoundrel, $N!' WHERE `word_id` = 7690; -- db_script_string - content : entry=2000000084
UPDATE `trans_words` SET `content_loc7`='I shall use this time wisely, milord. Thank you.' WHERE `word_id` = 7235; -- db_script_string - content : entry=2000005653
UPDATE `trans_words` SET `content_loc7`='I swear, people have actualy seen them. Pandaren really do exist!!' WHERE `word_id` = 7096; -- db_script_string - content : entry=2000005112
UPDATE `trans_words` SET `content_loc7`='I thank you, $N. And my brother thanks you.' WHERE `word_id` = 8280; -- db_script_string - content : entry=2000005776
UPDATE `trans_words` SET `content_loc7`='I think, I\'ll be able to get to Brackenwall. The cargo they carried to the top of the towers. Be careful!' WHERE `word_id` = 8726; -- db_script_string - content : entry=2000000486
UPDATE `trans_words` SET `content_loc7`='I thought this was going to be our chance to get away from it all? Our vacation?' WHERE `word_id` = 8216; -- db_script_string - content : entry=2000005680
UPDATE `trans_words` SET `content_loc7`='I WICKED OGR' WHERE `word_id` = 7545; -- db_script_string - content : entry=2000005230
UPDATE `trans_words` SET `content_loc7`='I WILL DESTROY ALL' WHERE `word_id` = 7483; -- db_script_string - content : entry=2000005043
UPDATE `trans_words` SET `content_loc7`='I will do my best to take care of the children, Grandmother.' WHERE `word_id` = 7481; -- db_script_string - content : entry=2000005041
UPDATE `trans_words` SET `content_loc7`='I will need to focus my energies onto this knife. By doing so, I should catch some of the stronger psychic impressions associated with it.' WHERE `word_id` = 7361; -- db_script_string - content : entry=2000000521
UPDATE `trans_words` SET `content_loc7`='I\'m going to train you to help $N with very important task. After that, I promose you\'ll be free to return home.' WHERE `word_id` = 8211; -- db_script_string - content : entry=2000005673
UPDATE `trans_words` SET `content_loc7`='I\'m listening..' WHERE `word_id` = 8030; -- db_script_string - content : entry=2000005437
UPDATE `trans_words` SET `content_loc7`='I\'m surrounded by idiots.' WHERE `word_id` = 7969; -- db_script_string - content : entry=2000005274
UPDATE `trans_words` SET `content_loc7`='I\'ve rigged a few control consoles down the slope. Get one quickly and take control of the fel reaver! You\'ll only have a limited amount of time.' WHERE `word_id` = 8049; -- db_script_string - content : entry=2000005459
UPDATE `trans_words` SET `content_loc7`='Is it done yet? What is talking so damned long?' WHERE `word_id` = 7977; -- db_script_string - content : entry=2000005282
UPDATE `trans_words` SET `content_loc7`='Iskalder? You fool! Have you no idea who that is? He\'s only the greatest vrykul warrior who ever lived!' WHERE `word_id` = 6921; -- db_script_string - content : entry=2000000294
UPDATE `trans_words` SET `content_loc7`='It is over, your search is done! Let fate choose now, the righteous one.' WHERE `word_id` = 1370; -- db_script_string - content : entry=2000005643
UPDATE `trans_words` SET `content_loc7`='It is time to force your final challenge young warriors! Prepare for your hardest fight yet.' WHERE `word_id` = 7559; -- db_script_string - content : entry=2000005075
UPDATE `trans_words` SET `content_loc7`='It\'s all here... how the raven\'s followers captured and subdued the sprints of rivals, trapping them forever within stone statues! The tablet even mentions the raven god\'s name -- Anzu. I\'d thought it was lost to history!' WHERE `word_id` = 7581; -- db_script_string - content : entry=2000000072
UPDATE `trans_words` SET `content_loc7`='It\'s good that I managed to make copies of the Felsworn Gas Mask...' WHERE `word_id` = 7804; -- db_script_string - content : entry=2000000312
UPDATE `trans_words` SET `content_loc7`='Jeffrey Kaplan! Tom Chilton! Rob Pardo!' WHERE `word_id` = 268222; -- db_script_string - content : entry=2000000490
UPDATE `trans_words` SET `content_loc7`='Just sit right back and you\'ll hear a ta... *hic* a tai... *hic* a taiii *hic* Damnit!' WHERE `word_id` = 7156; -- db_script_string - content : entry=2000005233
UPDATE `trans_words` SET `content_loc7`='Justin Thavirat! Roman Kenney! Our entire awesome art and animation team!' WHERE `word_id` = 268223; -- db_script_string - content : entry=2000000491
UPDATE `trans_words` SET `content_loc7`='Keep up the good work. Do well and you will be rewarded by the master.' WHERE `word_id` = 8055; -- db_script_string - content : entry=2000005470
UPDATE `trans_words` SET `content_loc7`='Kevin Jordan and Jonathan LeCraft!' WHERE `word_id` = 268224; -- db_script_string - content : entry=2000000492
UPDATE `trans_words` SET `content_loc7`='Let us hold or discussion in a more... private place. Follow me, $N.' WHERE `word_id` = 8330; -- db_script_string - content : entry=2000005832
UPDATE `trans_words` SET `content_loc7`='Look out! More are coming!' WHERE `word_id` = 7597; -- db_script_string - content : entry=2000000023
UPDATE `trans_words` SET `content_loc7`='Look! Minions of Terokk are approaching!' WHERE `word_id` = 7596; -- db_script_string - content : entry=2000000022
UPDATE `trans_words` SET `content_loc7`='Lord Uther...' WHERE `word_id` = 8287; -- db_script_string - content : entry=2000005786
UPDATE `trans_words` SET `content_loc7`='My legs feels much better now, the remedy must be working. If you will excuse me, I must go report to my superiors about what has transpired here.' WHERE `word_id` = 7246; -- db_script_string - content : entry=2000005630
UPDATE `trans_words` SET `content_loc7`='My the light bless you.' WHERE `word_id` = 8214; -- db_script_string - content : entry=2000005676
UPDATE `trans_words` SET `content_loc7`='New posting up! Adventurers and heroes, gather round the bulletin board!' WHERE `word_id` = 7482; -- db_script_string - content : entry=2000005042
UPDATE `trans_words` SET `content_loc7`='NOBODY WILL GET THROUGH ME' WHERE `word_id` = 7548; -- db_script_string - content : entry=2000005235
UPDATE `trans_words` SET `content_loc7`='Not a challenge at all it seems. Let us see how hou handle your second test. Lysta, bring forth the minions of the Lich King.' WHERE `word_id` = 7561; -- db_script_string - content : entry=2000005073
UPDATE `trans_words` SET `content_loc7`='Now get out of my way, it\'s time to send the Burning Legion back to the nether!' WHERE `word_id` = 7504; -- db_script_string - content : entry=2000005413
UPDATE `trans_words` SET `content_loc7`='Now we call forth the the arcane acolyte.' WHERE `word_id` = 8253; -- db_script_string - content : entry=2000005720
UPDATE `trans_words` SET `content_loc7`='Of Course Im talking to myself. Only way to get a decent conversation in this city.' WHERE `word_id` = 7519; -- db_script_string - content : entry=2000005105
UPDATE `trans_words` SET `content_loc7`='Of course, Brann: We will have the shield down momentarily.' WHERE `word_id` = 8142; -- db_script_string - content : entry=2000005573
UPDATE `trans_words` SET `content_loc7`='Ograbisi needs new hat.' WHERE `word_id` = 7360; -- db_script_string - content : entry=2000000326
UPDATE `trans_words` SET `content_loc7`='Oh man, I thought I was dead for sure. Ugh... still dizzy...' WHERE `word_id` = 7195; -- db_script_string - content : entry=2000000519
UPDATE `trans_words` SET `content_loc7`='Oh no! Here they come!' WHERE `word_id` = 7207; -- db_script_string - content : entry=2000005547
UPDATE `trans_words` SET `content_loc7`='Oh sweet, delicious, spotted eggs - you will be mine...' WHERE `word_id` = 7573; -- db_script_string - content : entry=2000005093
UPDATE `trans_words` SET `content_loc7`='Oh, no...' WHERE `word_id` = 8315; -- db_script_string - content : entry=2000005814
UPDATE `trans_words` SET `content_loc7`='Ok, let\'s get started!' WHERE `word_id` = 7422; -- db_script_string - content : entry=2000000103
UPDATE `trans_words` SET `content_loc7`='Okay! Let\'s move out. Get into your machines; I\'ll speak to you from here via the radio.' WHERE `word_id` = 8143; -- db_script_string - content : entry=2000005574
UPDATE `trans_words` SET `content_loc7`='Onu is struck by unleashed magic!' WHERE `word_id` = 6982; -- db_script_string - content : entry=2000000091
UPDATE `trans_words` SET `content_loc7`='Onu studies the parchment from the Twilight Tome...' WHERE `word_id` = 6983; -- db_script_string - content : entry=2000000090
UPDATE `trans_words` SET `content_loc7`='Our oldest clutch of dragons are still far from maturity, but with patience and study, we are confident the dragons will soon be ready.' WHERE `word_id` = 7078; -- db_script_string - content : entry=2000005029
UPDATE `trans_words` SET `content_loc7`='Pentarus, you heard the man. Have your mages release the shield and let these brave souls through!' WHERE `word_id` = 8141; -- db_script_string - content : entry=2000005572
UPDATE `trans_words` SET `content_loc7`='Perry Gatner! What an act! The cantina is open all night long, so please, stay and enjoy yourselves!' WHERE `word_id` = 7550; -- db_script_string - content : entry=2000005301
UPDATE `trans_words` SET `content_loc7`='Please! I must feed on something soon... A mana crystal... a shard... anything! The pain is unbearable!' WHERE `word_id` = 7476; -- db_script_string - content : entry=2000005036
UPDATE `trans_words` SET `content_loc7`='Prizes! Get your prizes right here! Get over here and turn in your Darkmoon Faire Prize Tickets for valuable prizes!' WHERE `word_id` = 7471; -- db_script_string - content : entry=2000005025
UPDATE `trans_words` SET `content_loc7`='Release me immediatley or face my wrath!' WHERE `word_id` = 8059; -- db_script_string - content : entry=2000005474
UPDATE `trans_words` SET `content_loc7`='Remulos, I am being drawn back... Tyrande... send her my love... Tell her I am safe... Tell her... Tell her I will return... Farewell...' WHERE `word_id` = 7317; -- db_script_string - content : entry=2000000385
UPDATE `trans_words` SET `content_loc7`='Remulos, old friend. It is good to see you once more. I knew the message would find its way to you - one way or another.' WHERE `word_id` = 7310; -- db_script_string - content : entry=2000000378
UPDATE `trans_words` SET `content_loc7`='Rest now, Adaris. You need to recover your strength.' WHERE `word_id` = 7728; -- db_script_string - content : entry=2000000188
UPDATE `trans_words` SET `content_loc7`='Return to him. Return to Mehlor and tell him that I forgive him and that I understand why he believes what he does.' WHERE `word_id` = 7811; -- db_script_string - content : entry=2000000321
UPDATE `trans_words` SET `content_loc7`='Right. We just busted our tails to haul all of this stuff up here, and you want us to work more?' WHERE `word_id` = 7494; -- db_script_string - content : entry=2000005056
UPDATE `trans_words` SET `content_loc7`='Sarath fades into the mist...' WHERE `word_id` = 7427; -- db_script_string - content : entry=2000000053
UPDATE `trans_words` SET `content_loc7`='Seems like a hundred times a day I walk all the way to get more water. No respect for their elders I tell ya.' WHERE `word_id` = 5747; -- db_script_string - content : entry=2000005107
UPDATE `trans_words` SET `content_loc7`='Shane Dabiri, Lee, Alex T., Rob F., J. A. B., A. Mayberry!' WHERE `word_id` = 268221; -- db_script_string - content : entry=2000000489
UPDATE `trans_words` SET `content_loc7`='Sniff... That\'s the spirit soldier... I only wish we had more soldiers like you in this army. Now go out there and give \'em hell!' WHERE `word_id` = 7503; -- db_script_string - content : entry=2000005414
UPDATE `trans_words` SET `content_loc7`='Speak to the commander at your post, lad, and persuade him to abandon Vor\'takh\'s foolish plan.' WHERE `word_id` = 8609; -- db_script_string - content : entry=2000005850
UPDATE `trans_words` SET `content_loc7`='Spirits of Water, I give you praise, and I beg of you a favour. You have heard $N\'s pleas, and I trust his inent is noble. Please, will you aid us?' WHERE `word_id` = 7572; -- db_script_string - content : entry=2000000057
UPDATE `trans_words` SET `content_loc7`='Spirits watch for you, $R.' WHERE `word_id` = 8105; -- db_script_string - content : entry=2000005523
UPDATE `trans_words` SET `content_loc7`='Strange. Very strange...' WHERE `word_id` = 7700; -- db_script_string - content : entry=2000000099
UPDATE `trans_words` SET `content_loc7`='Sure Paige. Just be gentle.' WHERE `word_id` = 7141; -- db_script_string - content : entry=2000005181
UPDATE `trans_words` SET `content_loc7`='Terenthis begins to cast a spell as you take the cloak from him.' WHERE `word_id` = 7067; -- db_script_string - content : entry=2000000006
UPDATE `trans_words` SET `content_loc7`='Terenthis begins to cast a spell on Grimclaw.' WHERE `word_id` = 7189; -- db_script_string - content : entry=2000005389
UPDATE `trans_words` SET `content_loc7`='Thank you again, $N. This rare earth will be very helpful in my experiments.' WHERE `word_id` = 6965; -- db_script_string - content : entry=2000000049
UPDATE `trans_words` SET `content_loc7`='Thank you for freeing us, mortals. Beware, the Blue Flight is alerted to your presence. Even now, Malygos sends Varos Cloudstrider and his ring guardians to defend the Oculus. You will need our help to stand a chance.' WHERE `word_id` = 8107; -- db_script_string - content : entry=2000005525
UPDATE `trans_words` SET `content_loc7`='Thank you great spirit. Thank you!' WHERE `word_id` = 6973; -- db_script_string - content : entry=2000000058
UPDATE `trans_words` SET `content_loc7`='Thank you, $N. And luck to you.' WHERE `word_id` = 7184; -- db_script_string - content : entry=2000005346
UPDATE `trans_words` SET `content_loc7`='Thank you. I thought I was going to die.' WHERE `word_id` = 7625; -- db_script_string - content : entry=2000005545
UPDATE `trans_words` SET `content_loc7`='That\'s interesting...' WHERE `word_id` = 6949; -- db_script_string - content : entry=2000000020
UPDATE `trans_words` SET `content_loc7`='The bonelashers of the wastes are no laughing matter. I hear they carry diseases!' WHERE `word_id` = 8224; -- db_script_string - content : entry=2000005688
UPDATE `trans_words` SET `content_loc7`='The boss wants all hands on high alert. The rusty anchor sinks tonight.' WHERE `word_id` = 7225; -- db_script_string - content : entry=2000005408
UPDATE `trans_words` SET `content_loc7`='The Darkmoon Faire is the greatest event in all of Outland' WHERE `word_id` = 7540; -- db_script_string - content : entry=2000005221
UPDATE `trans_words` SET `content_loc7`='The invisibility liquer is ready for you, $N.' WHERE `word_id` = 7689; -- db_script_string - content : entry=2000000081
UPDATE `trans_words` SET `content_loc7`='The Lorehammer ist reacting. This must be from Stormhoof\'s time.' WHERE `word_id` = 7787; -- db_script_string - content : entry=2000000274
UPDATE `trans_words` SET `content_loc7`='The mixture! It moves!' WHERE `word_id` = 7747; -- db_script_string - content : entry=2000000232
UPDATE `trans_words` SET `content_loc7`='The orcs in my citadel will drink your blood and dovour you!' WHERE `word_id` = 8034; -- db_script_string - content : entry=2000005442
UPDATE `trans_words` SET `content_loc7`='There we are, $N. The toxin is ready.' WHERE `word_id` = 6988; -- db_script_string - content : entry=2000000111
UPDATE `trans_words` SET `content_loc7`='There\'s something else here, too. After a discription of a bloody battle and the downfall of the raven, there\'s a prophecy. Anzu will haunt the dreams of his enemies, twisting them to affect a return to this world...' WHERE `word_id` = 7582; -- db_script_string - content : entry=2000000073
UPDATE `trans_words` SET `content_loc7`='They all go to the Spire but none never come back... just like Bijou.' WHERE `word_id` = 5673; -- db_script_string - content : entry=2000005006
UPDATE `trans_words` SET `content_loc7`='They will live of only to see the fruits of their labor: the destruction and chaos that will surely ensue as the legion of Blackrock invade the gorge.' WHERE `word_id` = 7371; -- db_script_string - content : entry=2000000531
UPDATE `trans_words` SET `content_loc7`='Think of your younglings, Gul\'dan! You will destroy us all!' WHERE `word_id` = 8044; -- db_script_string - content : entry=2000005454
UPDATE `trans_words` SET `content_loc7`='This is a shiney rock. I\'ll put it in my bucket. Ok, I just need a few more...' WHERE `word_id` = 7292; -- db_script_string - content : entry=2000005325
UPDATE `trans_words` SET `content_loc7`='This is great news! Your efforts have indeed saved us, $N!' WHERE `word_id` = 8633; -- db_script_string - content : entry=2000005841
UPDATE `trans_words` SET `content_loc7`='This is the last time that I buy second-hand equipment from ethereal' WHERE `word_id` = 7466; -- db_script_string - content : entry=2000005067
UPDATE `trans_words` SET `content_loc7`='This makes sense!' WHERE `word_id` = 6955; -- db_script_string - content : entry=2000000030
UPDATE `trans_words` SET `content_loc7`='This poster has a bounty on bonelashers. You think I should do that?' WHERE `word_id` = 8221; -- db_script_string - content : entry=2000005685
UPDATE `trans_words` SET `content_loc7`='Tickets! Redeem your Darkmoon Faire Prize Tickets here! Wondrous and exotic prizes are waiting for you!' WHERE `word_id` = 7534; -- db_script_string - content : entry=2000005212
UPDATE `trans_words` SET `content_loc7`='Tonga Runetotem inspects the snapjaw shells...' WHERE `word_id` = 7698; -- db_script_string - content : entry=2000000097
UPDATE `trans_words` SET `content_loc7`='Turning to face Tuluun, the Draenei Artificer sneers contemptuously.' WHERE `word_id` = 7642; -- db_script_string - content : entry=2000000662
UPDATE `trans_words` SET `content_loc7`='US ALREADY ALL ANYMORE AND ANYMORE' WHERE `word_id` = 7484; -- db_script_string - content : entry=2000005044
UPDATE `trans_words` SET `content_loc7`='Waste no time, fool! Use our power to kill those what stand in our way! Destroy Krasius before you are subdued!' WHERE `word_id` = 8058; -- db_script_string - content : entry=2000005473
UPDATE `trans_words` SET `content_loc7`='We will act when we know what we need, old friend. The druids have proven wise and capable of making their own decisions.' WHERE `word_id` = 7942; -- db_script_string - content : entry=2000005247
UPDATE `trans_words` SET `content_loc7`='We won. Dimensius no more. Report this proffesor Dabiri.' WHERE `word_id` = 8285; -- db_script_string - content : entry=2000005784
UPDATE `trans_words` SET `content_loc7`='Welcome one and all to the Darkmoon Faire, the greatest event in all the worlds! We have it all... delicious food, strong drinks, exotic artifacts, fortunes read, amazing prizes and excitement without end! Don\'t forget to turn in your Darkmoon Faire Prize Tickets to Gelvas Grimegate! All it takes is five or more and you\'re on your way to the most wondrous prizes in all of Outland. Everybody is a winner' WHERE `word_id` = 7475; -- db_script_string - content : entry=2000005034
UPDATE `trans_words` SET `content_loc7`='Well, I am off than. Take care, Harlan!' WHERE `word_id` = 7021; -- db_script_string - content : entry=2000000150
UPDATE `trans_words` SET `content_loc7`='Well, that should do it. Come now, back to the shop to finish our business!' WHERE `word_id` = 6976; -- db_script_string - content : entry=2000000064
UPDATE `trans_words` SET `content_loc7`='What up son! Wait....is anyone there?' WHERE `word_id` = 7931; -- db_script_string - content : entry=2000005055
UPDATE `trans_words` SET `content_loc7`='What? How dare you say that to me?!?' WHERE `word_id` = 7205; -- db_script_string - content : entry=2000005549
UPDATE `trans_words` SET `content_loc7`='What?? The Burning Blade is spreading! We must investigate!' WHERE `word_id` = 7253; -- db_script_string - content : entry=2000005778
UPDATE `trans_words` SET `content_loc7`='When is pappa comming back from the fights in Warsong? It has been so long...' WHERE `word_id` = 7263; -- db_script_string - content : entry=2000005775
UPDATE `trans_words` SET `content_loc7`='Where do you think you are going soldier? Those are fatal wounds you\'ve got there. Now, get back in tent and let the nurse treat you!' WHERE `word_id` = 7505; -- db_script_string - content : entry=2000005412
UPDATE `trans_words` SET `content_loc7`='Who dares step into my domain! Come! Come, and be consumed!' WHERE `word_id` = 7203; -- db_script_string - content : entry=2000005552
UPDATE `trans_words` SET `content_loc7`='Who... who are you? Who.. what am I?' WHERE `word_id` = 7835; -- db_script_string - content : entry=2000000351
UPDATE `trans_words` SET `content_loc7`='Who? The Tauren Chieftains! What? A live performance. Where? The World\'s End Tavern! When? The top of the hour! BE THERE!' WHERE `word_id` = 7439; -- db_script_string - content : entry=2000005305
UPDATE `trans_words` SET `content_loc7`='Why do you do this? Did I somehow wrong you in life?' WHERE `word_id` = 7809; -- db_script_string - content : entry=2000000319
UPDATE `trans_words` SET `content_loc7`='Worm goes on the hook, hook goes in the water, Fish is in the water, our fish.' WHERE `word_id` = 7104; -- db_script_string - content : entry=2000005122
UPDATE `trans_words` SET `content_loc7`='Wouldn\'t you like to bring those days back? I have some friends who know just the way to do that.' WHERE `word_id` = 7469; -- db_script_string - content : entry=2000005022
UPDATE `trans_words` SET `content_loc7`='Wow! $N, that dream dust is powerful stuff!' WHERE `word_id` = 7217; -- db_script_string - content : entry=2000000129
UPDATE `trans_words` SET `content_loc7`='Yer wearin down, princess, I can sense it!' WHERE `word_id` = 7530; -- db_script_string - content : entry=2000005203
UPDATE `trans_words` SET `content_loc7`='Yes, he\'s second-in-command of the wyrmcult at the Blackwing Coven to the west.' WHERE `word_id` = 7726; -- db_script_string - content : entry=2000000186
UPDATE `trans_words` SET `content_loc7`='You have been gone too long, Malfurion. Peace between the Children of Azeroth has become tenuous at best. What of my father? Of your brother? Have you any news?' WHERE `word_id` = 7315; -- db_script_string - content : entry=2000000383
UPDATE `trans_words` SET `content_loc7`='You know why Orcs eyes glow red? It\'s because they drink blood!' WHERE `word_id` = 7097; -- db_script_string - content : entry=2000005113
UPDATE `trans_words` SET `content_loc7`='You need to do what? All this science. I don\'t understand... Look, this is just my job, five days a week.' WHERE `word_id` = 7945; -- db_script_string - content : entry=2000005250
UPDATE `trans_words` SET `content_loc7`='YOU PRAY SERVANTS MY' WHERE `word_id` = 7539; -- db_script_string - content : entry=2000005220
UPDATE `trans_words` SET `content_loc7`='You want to go do the bounty off of this wanted poster after this shift is over?' WHERE `word_id` = 7487; -- db_script_string - content : entry=2000005047
UPDATE `trans_words` SET `content_loc7`='You were right to come. My wisdom will be yours.' WHERE `word_id` = 6986; -- db_script_string - content : entry=2000000109
UPDATE `trans_words` SET `content_loc7`='You will not harm the boy, Mor\'ghor! Quickly, $N, climb on my back!' WHERE `word_id` = 7996; -- db_script_string - content : entry=2000005355
UPDATE `trans_words` SET `content_loc7`='Your body is mine! Our fates are forever intertwined!' WHERE `word_id` = 7595; -- db_script_string - content : entry=2000000031
UPDATE `trans_words` SET `content_loc7`='Your time is night...' WHERE `word_id` = 1379; -- db_script_string - content : entry=2000005640
UPDATE `trans_words` SET `content_loc7`='Zarlman Two-Moons begins chanting as he mixes the well stones and ambercom before the Tribal Fire.' WHERE `word_id` = 7345; -- db_script_string - content : entry=2000000095

SET NAMES 'latin1';
