-- File generated by Mangos Online Translation Editor (MOTE) v2.00
SET NAMES 'utf8';
UPDATE locales_gossip_menu_option SET option_text_loc1='I would like to inform the secret code to get a pet, murloc.',box_text_loc1='2222' WHERE menu_id=7034 AND id=0;
UPDATE locales_gossip_menu_option SET option_text_loc1='Purchase a Dual Talent Specialization.',box_text_loc1='Are you sure you wish to purchase a Dual Talent Specialization?' WHERE menu_id=10371 AND id=0;

SET NAMES 'latin1';
