-- File generated by MOTE (Mangos Online Translation Editor) v0.01
SET NAMES 'utf8';
UPDATE db_script_string SET content_loc2='Frénécœur va vous tuer si vous revenez. On veut plus vous voir !' WHERE entry=2000000163; /* content: Frenzyheart kill you if you come back. You no welcome here no more! */
UPDATE db_script_string SET content_loc2='Victoire !' WHERE entry=2000000637; /* content: Success! */
UPDATE db_script_string SET content_loc2='Feu à volonté !' WHERE entry=2000005635; /* content: FIRE AT WILL! */

SET NAMES 'latin1';
