-- File generated by Mangos Online Translation Editor (MOTE) v3.04
SET NAMES 'utf8';
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Cloth Belt' WHERE `word_id` = 27939; -- locales_item - name : entry=26128
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Cloth Boot' WHERE `word_id` = 27940; -- locales_item - name : entry=26129
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Cloth Chest' WHERE `word_id` = 27941; -- locales_item - name : entry=26130
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Cloth Cloak' WHERE `word_id` = 27947; -- locales_item - name : entry=26513
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Cloth Hand' WHERE `word_id` = 27942; -- locales_item - name : entry=26131
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Cloth Head' WHERE `word_id` = 27943; -- locales_item - name : entry=26132
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Cloth Legs' WHERE `word_id` = 27944; -- locales_item - name : entry=26133
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Cloth Necklace' WHERE `word_id` = 27949; -- locales_item - name : entry=26541
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Cloth Ring' WHERE `word_id` = 27948; -- locales_item - name : entry=26527
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Cloth Shoulder' WHERE `word_id` = 27945; -- locales_item - name : entry=26134
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Cloth Wrist' WHERE `word_id` = 27946; -- locales_item - name : entry=26135
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Off Hand' WHERE `word_id` = 27950; -- locales_item - name : entry=26569
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Spell Dagger' WHERE `word_id` = 27952; -- locales_item - name : entry=26779
UPDATE `trans_words` SET `content_loc5`='68 TEST Green Wand' WHERE `word_id` = 27951; -- locales_item - name : entry=26765
UPDATE `trans_words` SET `content_loc5`='A crystalline key that is seemingly held together by beams of light.' WHERE `word_id` = 31763; -- locales_item - description : entry=31704
UPDATE `trans_words` SET `content_loc5`='A reagent for mage spells.' WHERE `word_id` = 12315; -- locales_item - description : entry=5517
UPDATE `trans_words` SET `content_loc5`='A second test token for the Currency Token system' WHERE `word_id` = 47411; -- locales_item - description : entry=37742
UPDATE `trans_words` SET `content_loc5`='A test token for the Currency Token system' WHERE `word_id` = 47409; -- locales_item - description : entry=37711
UPDATE `trans_words` SET `content_loc5`='A third test token for the Currency Token system' WHERE `word_id` = 47414; -- locales_item - description : entry=38644
UPDATE `trans_words` SET `content_loc5`='Agmond\'s Belt Pouch' WHERE `word_id` = 24228; -- locales_item - name : entry=4981
UPDATE `trans_words` SET `content_loc5`='Alex\'s Ring of Audacity' WHERE `word_id` = 16991; -- locales_item - name : entry=12947
UPDATE `trans_words` SET `content_loc5`='Alex\'s Test Beatdown Staff' WHERE `word_id` = 21820; -- locales_item - name : entry=19879
UPDATE `trans_words` SET `content_loc5`='Archaedic Shard' WHERE `word_id` = 24322; -- locales_item - name : entry=9417
UPDATE `trans_words` SET `content_loc5`='Auchenai Key' WHERE `word_id` = 30711; -- locales_item - name : entry=30633
UPDATE `trans_words` SET `content_loc5`='Bears the mark of the Shattered Hand.' WHERE `word_id` = 25781; -- locales_item - description : entry=23881
UPDATE `trans_words` SET `content_loc5`='Bears the seal of Arazzius.' WHERE `word_id` = 28474; -- locales_item - description : entry=28046
UPDATE `trans_words` SET `content_loc5`='Bind On Acquire Test Item' WHERE `word_id` = 24319; -- locales_item - name : entry=8688
UPDATE `trans_words` SET `content_loc5`='Blessed Relic' WHERE `word_id` = 24187; -- locales_item - name : entry=2921
UPDATE `trans_words` SET `content_loc5`='Blue Bryanite of Agility' WHERE `word_id` = 25230; -- locales_item - name : entry=23234
UPDATE `trans_words` SET `content_loc5`='Cache of the Legion Key' WHERE `word_id` = 30546; -- locales_item - name : entry=30438
UPDATE `trans_words` SET `content_loc5`='Can be targeted by Armor enchantments to store the enchantment for later use. Only able to absorb enchantments with a level restriction of 35 or lower.' WHERE `word_id` = 37246; -- locales_item - description : entry=37602
UPDATE `trans_words` SET `content_loc5`='Can be targeted by Armor enchantments to store the enchantment for later use. Only able to absorb enchantments with a level restriction of 60 or lower.' WHERE `word_id` = 41560; -- locales_item - description : entry=43145
UPDATE `trans_words` SET `content_loc5`='Can be targeted by Weapon enchantments to store the enchantment for later use. Only able to absorb enchantments with a level restriction of 35 or lower.' WHERE `word_id` = 38683; -- locales_item - description : entry=39350
UPDATE `trans_words` SET `content_loc5`='Can be targeted by Weapon enchantments to store the enchantment for later use. Only able to absorb enchantments with a level restriction of 60 or lower.' WHERE `word_id` = 41562; -- locales_item - description : entry=43146
UPDATE `trans_words` SET `content_loc5`='Can be targeted by Weapon enchantments to store the enchantment for later use. Only able to absorb enchantments with no level restrictions.' WHERE `word_id` = 38681; -- locales_item - description : entry=39349
UPDATE `trans_words` SET `content_loc5`='Celestial Planetarium Key' WHERE `word_id` = 44125; -- locales_item - name : entry=45796
UPDATE `trans_words` SET `content_loc5`='Cornmeal' WHERE `word_id` = 43432; -- locales_item - name : entry=44852
UPDATE `trans_words` SET `content_loc5`='Counts as an Air, Earth, Fire, and Water totem.' WHERE `word_id` = 23479; -- locales_item - description : entry=22345
UPDATE `trans_words` SET `content_loc5`='Currency Token Test Token 1' WHERE `word_id` = 47408; -- locales_item - name : entry=37711
UPDATE `trans_words` SET `content_loc5`='Currency Token Test Token 2' WHERE `word_id` = 47410; -- locales_item - name : entry=37742
UPDATE `trans_words` SET `content_loc5`='Currency Token Test Token 3' WHERE `word_id` = 47413; -- locales_item - name : entry=38644
UPDATE `trans_words` SET `content_loc5`='Cut cleanly off at the shoulders.' WHERE `word_id` = 31766; -- locales_item - description : entry=31706
UPDATE `trans_words` SET `content_loc5`='Demon Hunter Blindfold' WHERE `word_id` = 24215; -- locales_item - name : entry=3536
UPDATE `trans_words` SET `content_loc5`='Deprecated Feathered Helm' WHERE `word_id` = 24225; -- locales_item - name : entry=4193
UPDATE `trans_words` SET `content_loc5`='Deprecated Rogue\'s Vest' WHERE `word_id` = 24128; -- locales_item - name : entry=119
UPDATE `trans_words` SET `content_loc5`='Deprecated Silver Totem of Aquementas' WHERE `word_id` = 24337; -- locales_item - name : entry=11170
UPDATE `trans_words` SET `content_loc5`='Deprecated Silver-thread Cowl' WHERE `word_id` = 24198; -- locales_item - name : entry=3068
UPDATE `trans_words` SET `content_loc5`='Deprecated Stormrage Boots' WHERE `word_id` = 24383; -- locales_item - name : entry=13242
UPDATE `trans_words` SET `content_loc5`='Deprecated Tauren Trapper\'s Pants' WHERE `word_id` = 24129; -- locales_item - name : entry=128
UPDATE `trans_words` SET `content_loc5`='Diet McWeaksauce' WHERE `word_id` = 24081; -- locales_item - name : entry=23578
UPDATE `trans_words` SET `content_loc5`='Discovery!' WHERE `word_id` = 42806; -- locales_item - name : entry=44508
UPDATE `trans_words` SET `content_loc5`='Dragonstalker Tunic' WHERE `word_id` = 24377; -- locales_item - name : entry=13092
UPDATE `trans_words` SET `content_loc5`='Dreadmaster\'s Shroud' WHERE `word_id` = 24407; -- locales_item - name : entry=13936
UPDATE `trans_words` SET `content_loc5`='Elven Protector' WHERE `word_id` = 24326; -- locales_item - name : entry=9888
UPDATE `trans_words` SET `content_loc5`='Engraved with the words \'For years of service: -EVC.\'' WHERE `word_id` = 9700; -- locales_item - description : entry=2239
UPDATE `trans_words` SET `content_loc5`='Essence of the Firelord DEPRECATED' WHERE `word_id` = 24442; -- locales_item - name : entry=18566
UPDATE `trans_words` SET `content_loc5`='Etched on the side: Wazat will not be held accountable for any accidents that occur as a result of using the Jump-a-tron 4000.' WHERE `word_id` = 28303; -- locales_item - description : entry=27808
UPDATE `trans_words` SET `content_loc5`='Explosive Shell' WHERE `word_id` = 11998; -- locales_item - name : entry=5105
UPDATE `trans_words` SET `content_loc5`='First Sergeant\'s Cloak' WHERE `word_id` = 24428; -- locales_item - name : entry=16340
UPDATE `trans_words` SET `content_loc5`='Flamewrought Key' WHERE `word_id` = 30699; -- locales_item - name : entry=30622
UPDATE `trans_words` SET `content_loc5`='Food for the Mind' WHERE `word_id` = 24082; -- locales_item - description : entry=23578
UPDATE `trans_words` SET `content_loc5`='Formula: Enchant Boots - Minor Stamina' WHERE `word_id` = 24293; -- locales_item - name : entry=6376
UPDATE `trans_words` SET `content_loc5`='Formula: Imbue Cloak - Protection' WHERE `word_id` = 24290; -- locales_item - name : entry=6345
UPDATE `trans_words` SET `content_loc5`='Foror\'s Crate of Endless Resist Gear Storage' WHERE `word_id` = 25208; -- locales_item - name : entry=23162
UPDATE `trans_words` SET `content_loc5`='G.E.H.T.A.' WHERE `word_id` = 36766; -- locales_item - name : entry=37018
UPDATE `trans_words` SET `content_loc5`='G.N.E.R.D.S.' WHERE `word_id` = 37233; -- locales_item - name : entry=37583
UPDATE `trans_words` SET `content_loc5`='Glaive of the Defender' WHERE `word_id` = 23918; -- locales_item - name : entry=23051
UPDATE `trans_words` SET `content_loc5`='Glyph of Chromatic Warding' WHERE `word_id` = 30936; -- locales_item - name : entry=30845
UPDATE `trans_words` SET `content_loc5`='Glyphic Rune' WHERE `word_id` = 14757; -- locales_item - name : entry=9572
UPDATE `trans_words` SET `content_loc5`='Goblin "Boom" Box' WHERE `word_id` = 34951; -- locales_item - name : entry=10580
UPDATE `trans_words` SET `content_loc5`='Gor\'tesh\'s severed head, propped up on a pike.' WHERE `word_id` = 15848; -- locales_item - description : entry=11079
UPDATE `trans_words` SET `content_loc5`='Gordok Inner Door Key' WHERE `word_id` = 20591; -- locales_item - name : entry=18268
UPDATE `trans_words` SET `content_loc5`='Harness: Black Ram' WHERE `word_id` = 24280; -- locales_item - name : entry=5874
UPDATE `trans_words` SET `content_loc5`='Harness: Blue Ram' WHERE `word_id` = 24281; -- locales_item - name : entry=5875
UPDATE `trans_words` SET `content_loc5`='His eyes are full of hatred.' WHERE `word_id` = 25802; -- locales_item - description : entry=23901
UPDATE `trans_words` SET `content_loc5`='Horn of the Skeletal Mount' WHERE `word_id` = 24313; -- locales_item - name : entry=8583
UPDATE `trans_words` SET `content_loc5`='It smells of death and fear.' WHERE `word_id` = 25787; -- locales_item - description : entry=23886
UPDATE `trans_words` SET `content_loc5`='James\' Key' WHERE `word_id` = 20248; -- locales_item - name : entry=17262
UPDATE `trans_words` SET `content_loc5`='Jump-a-tron 4000 Key' WHERE `word_id` = 28302; -- locales_item - name : entry=27808
UPDATE `trans_words` SET `content_loc5`='Key of Time' WHERE `word_id` = 30715; -- locales_item - name : entry=30635
UPDATE `trans_words` SET `content_loc5`='Key to Salem\'s Chest' WHERE `word_id` = 20246; -- locales_item - name : entry=17242
UPDATE `trans_words` SET `content_loc5`='Kodo Mount' WHERE `word_id` = 24408; -- locales_item - name : entry=14062
UPDATE `trans_words` SET `content_loc5`='Large Moneybag' WHERE `word_id` = 24298; -- locales_item - name : entry=6754
UPDATE `trans_words` SET `content_loc5`='Lesser Firestone (DEPRECATED)' WHERE `word_id` = 34705; -- locales_item - name : entry=1254
UPDATE `trans_words` SET `content_loc5`='Librarian\'s Satchel' WHERE `word_id` = 24223; -- locales_item - name : entry=3762
UPDATE `trans_words` SET `content_loc5`='Lok\'delar, Stave of the Ancient Keepers DEP' WHERE `word_id` = 22194; -- locales_item - name : entry=20487
UPDATE `trans_words` SET `content_loc5`='Looks great. Less filling.' WHERE `word_id` = 16992; -- locales_item - description : entry=12947
UPDATE `trans_words` SET `content_loc5`='Manual: The Path of Defense' WHERE `word_id` = 24297; -- locales_item - name : entry=6619
UPDATE `trans_words` SET `content_loc5`='Master Key to the Depths, Courtesy of F.F.F.' WHERE `word_id` = 15831; -- locales_item - description : entry=11000
UPDATE `trans_words` SET `content_loc5`='May you always bring light into dark places.' WHERE `word_id` = 47299; -- locales_item - description : entry=52252
UPDATE `trans_words` SET `content_loc5`='MOLL-E' WHERE `word_id` = 39944; -- locales_item - name : entry=40768
UPDATE `trans_words` SET `content_loc5`='Mystical Powder' WHERE `word_id` = 24284; -- locales_item - name : entry=6216
UPDATE `trans_words` SET `content_loc5`='Naga Treasure Map - Questgiver (PH)' WHERE `word_id` = 30529; -- locales_item - name : entry=30427
UPDATE `trans_words` SET `content_loc5`='NYI - THIS ITEM WILL SPAWN A QUEST' WHERE `word_id` = 24221; -- locales_item - description : entry=3744
UPDATE `trans_words` SET `content_loc5`='Obsidian Golem Shard' WHERE `word_id` = 24306; -- locales_item - name : entry=7681
UPDATE `trans_words` SET `content_loc5`='Old Whistle of the Ivory Raptor' WHERE `word_id` = 24314; -- locales_item - name : entry=8589
UPDATE `trans_words` SET `content_loc5`='Old Whistle of the Obsidian Raptor' WHERE `word_id` = 24315; -- locales_item - name : entry=8590
UPDATE `trans_words` SET `content_loc5`='Only ONE May Rise... (and consequently, only ONE may loot this head)' WHERE `word_id` = 22115; -- locales_item - description : entry=20383
UPDATE `trans_words` SET `content_loc5`='Open for a prize!' WHERE `word_id` = 24277; -- locales_item - description : entry=5858
UPDATE `trans_words` SET `content_loc5`='Opens Dark Cleric Salem\'s Chest' WHERE `word_id` = 20247; -- locales_item - description : entry=17242
UPDATE `trans_words` SET `content_loc5`='Opens the stolen chest from the Cathedral of Light' WHERE `word_id` = 20249; -- locales_item - description : entry=17262
UPDATE `trans_words` SET `content_loc5`='P.T.T.' WHERE `word_id` = 35364; -- locales_item - description : entry=34785
UPDATE `trans_words` SET `content_loc5`='Plans: Goblin Rocket Boots' WHERE `word_id` = 24303; -- locales_item - name : entry=7192
UPDATE `trans_words` SET `content_loc5`='QA Test Blank Purple Gem' WHERE `word_id` = 37922; -- locales_item - name : entry=38498
UPDATE `trans_words` SET `content_loc5`='QR 9863 Warrior Chest' WHERE `word_id` = 27451; -- locales_item - name : entry=25573
UPDATE `trans_words` SET `content_loc5`='QR 9867 Hunter Gloves' WHERE `word_id` = 27459; -- locales_item - name : entry=25581
UPDATE `trans_words` SET `content_loc5`='QR 9867 Warrior Legs' WHERE `word_id` = 27458; -- locales_item - name : entry=25580
UPDATE `trans_words` SET `content_loc5`='QR 9922 Shield' WHERE `word_id` = 27497; -- locales_item - name : entry=25627
UPDATE `trans_words` SET `content_loc5`='Random quantity of essence or dust.' WHERE `word_id` = 45940; -- locales_item - description : entry=49640
UPDATE `trans_words` SET `content_loc5`='Randomly discover a new Alchemy recipe.' WHERE `word_id` = 42807; -- locales_item - description : entry=44508
UPDATE `trans_words` SET `content_loc5`='Red Bryanite of Strength stuff' WHERE `word_id` = 25229; -- locales_item - name : entry=23233
UPDATE `trans_words` SET `content_loc5`='Reins of the Spotted Nightsaber' WHERE `word_id` = 14355; -- locales_item - name : entry=8628
UPDATE `trans_words` SET `content_loc5`='Relic of the Dead' WHERE `word_id` = 24194; -- locales_item - name : entry=3004
UPDATE `trans_words` SET `content_loc5`='Relic of the Eye' WHERE `word_id` = 24193; -- locales_item - name : entry=3003
UPDATE `trans_words` SET `content_loc5`='Relic of Truth' WHERE `word_id` = 24195; -- locales_item - name : entry=3005
UPDATE `trans_words` SET `content_loc5`='Required by jewelcrafters to transmute mercurial adamantite.' WHERE `word_id` = 31170; -- locales_item - description : entry=31080
UPDATE `trans_words` SET `content_loc5`='Resembles a key used to open underwater treasure chests...' WHERE `word_id` = 42030; -- locales_item - description : entry=43650
UPDATE `trans_words` SET `content_loc5`='Reservoir Key' WHERE `word_id` = 30701; -- locales_item - name : entry=30623
UPDATE `trans_words` SET `content_loc5`='Rhok\'delar, Longbow of the Ancient Keepers DEP' WHERE `word_id` = 22195; -- locales_item - name : entry=20488
UPDATE `trans_words` SET `content_loc5`='Ring of Critical Testing 2' WHERE `word_id` = 21161; -- locales_item - name : entry=18970
UPDATE `trans_words` SET `content_loc5`='Rusty Prison Key' WHERE `word_id` = 42029; -- locales_item - name : entry=43650
UPDATE `trans_words` SET `content_loc5`='Sacred Relic' WHERE `word_id` = 24186; -- locales_item - name : entry=2920
UPDATE `trans_words` SET `content_loc5`='Sergeant Major\'s Cape' WHERE `word_id` = 24426; -- locales_item - name : entry=16315
UPDATE `trans_words` SET `content_loc5`='Sergeant\'s Insignia' WHERE `word_id` = 24427; -- locales_item - name : entry=16334
UPDATE `trans_words` SET `content_loc5`='SGM-3' WHERE `word_id` = 42511; -- locales_item - name : entry=44212
UPDATE `trans_words` SET `content_loc5`='Shadowforge Key' WHERE `word_id` = 15830; -- locales_item - name : entry=11000
UPDATE `trans_words` SET `content_loc5`='Skeleton Key' WHERE `word_id` = 17505; -- locales_item - name : entry=13704
UPDATE `trans_words` SET `content_loc5`='Softer than any material found on Azeroth.' WHERE `word_id` = 28864; -- locales_item - description : entry=28490
UPDATE `trans_words` SET `content_loc5`='Spirit Relic' WHERE `word_id` = 24188; -- locales_item - name : entry=2922
UPDATE `trans_words` SET `content_loc5`='Stormwind Seasoning Salts' WHERE `word_id` = 24177; -- locales_item - name : entry=2693
UPDATE `trans_words` SET `content_loc5`='Talisman of Binding Shard' WHERE `word_id` = 20467; -- locales_item - name : entry=17782
UPDATE `trans_words` SET `content_loc5`='TCHILTON TEST DAWNSTONE' WHERE `word_id` = 28769; -- locales_item - name : entry=28389
UPDATE `trans_words` SET `content_loc5`='TCHILTON TEST RUBY' WHERE `word_id` = 28768; -- locales_item - name : entry=28388
UPDATE `trans_words` SET `content_loc5`='Teaches Conjure Mana Gem (Rank 2).' WHERE `word_id` = 268239; -- locales_item - description : entry=8840
UPDATE `trans_words` SET `content_loc5`='Teaches you how to cook a Herb Baked Egg.' WHERE `word_id` = 24301; -- locales_item - description : entry=6891
UPDATE `trans_words` SET `content_loc5`='Teaches you how to cook a Sporeling Snack.' WHERE `word_id` = 28173; -- locales_item - description : entry=27689
UPDATE `trans_words` SET `content_loc5`='Teaches you how to inscribe a Glyph of Rapid Rejuvenation.' WHERE `word_id` = 46394; -- locales_item - description : entry=50167
UPDATE `trans_words` SET `content_loc5`='Teaches you how to make Goblin Rocket Boots.' WHERE `word_id` = 24304; -- locales_item - description : entry=7192
UPDATE `trans_words` SET `content_loc5`='Teaches you how to make Thorium Shells.' WHERE `word_id` = 19461; -- locales_item - description : entry=16051
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a cloak to give 10 additional armor.' WHERE `word_id` = 24291; -- locales_item - description : entry=6345
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant a pair of boots to grant +1 Stamina.' WHERE `word_id` = 24294; -- locales_item - description : entry=6376
UPDATE `trans_words` SET `content_loc5`='Teaches you how to permanently enchant gloves to increase fishing skill by 5.' WHERE `word_id` = 47325; -- locales_item - description : entry=50406
UPDATE `trans_words` SET `content_loc5`='Test Arcane Res Legs Mail' WHERE `word_id` = 19488; -- locales_item - name : entry=16165
UPDATE `trans_words` SET `content_loc5`='Test Dazzling Talasite' WHERE `word_id` = 39477; -- locales_item - name : entry=40232
UPDATE `trans_words` SET `content_loc5`='Test Stationery' WHERE `word_id` = 14090; -- locales_item - name : entry=8164
UPDATE `trans_words` SET `content_loc5`='The bottom of the crate is leaking. Leaking tears...' WHERE `word_id` = 25209; -- locales_item - description : entry=23162
UPDATE `trans_words` SET `content_loc5`='The completed amulet of Rakh\'likh.' WHERE `word_id` = 15727; -- locales_item - description : entry=10757
UPDATE `trans_words` SET `content_loc5`='The Fall of Ameth\'Aran' WHERE `word_id` = 24269; -- locales_item - name : entry=5563
UPDATE `trans_words` SET `content_loc5`='The Lay of Ameth\'Aran' WHERE `word_id` = 24268; -- locales_item - name : entry=5562
UPDATE `trans_words` SET `content_loc5`='The Master\'s Key' WHERE `word_id` = 26403; -- locales_item - name : entry=24490
UPDATE `trans_words` SET `content_loc5`='The McWeaksauce Classic' WHERE `word_id` = 24083; -- locales_item - name : entry=23579
UPDATE `trans_words` SET `content_loc5`='The Original.' WHERE `word_id` = 24084; -- locales_item - description : entry=23579
UPDATE `trans_words` SET `content_loc5`='The Tempest Key' WHERE `word_id` = 31762; -- locales_item - name : entry=31704
UPDATE `trans_words` SET `content_loc5`='The totem\'s inscription identifies the bearer as an ally of the water elemental Naias.' WHERE `word_id` = 25572; -- locales_item - description : entry=23680
UPDATE `trans_words` SET `content_loc5`='They look heavily worn, yet still remain razor sharp.' WHERE `word_id` = 25579; -- locales_item - description : entry=23687
UPDATE `trans_words` SET `content_loc5`='This blade is dimensional. It appears to be fading from this plane of existence.' WHERE `word_id` = 23739; -- locales_item - description : entry=22736
UPDATE `trans_words` SET `content_loc5`='Throwing Tomahawk' WHERE `word_id` = 24227; -- locales_item - name : entry=4959
UPDATE `trans_words` SET `content_loc5`='Tier 5 Druid Test Gear Box 2' WHERE `word_id` = 32519; -- locales_item - name : entry=32544
UPDATE `trans_words` SET `content_loc5`='Tiffany Cartier of Dalaran would be very interested in this fine powder.' WHERE `word_id` = 44638; -- locales_item - description : entry=46849
UPDATE `trans_words` SET `content_loc5`='Tomb Rot' WHERE `word_id` = 24189; -- locales_item - name : entry=2929
UPDATE `trans_words` SET `content_loc5`='Torment Vine' WHERE `word_id` = 24190; -- locales_item - name : entry=2932
UPDATE `trans_words` SET `content_loc5`='U.D.E.D.' WHERE `word_id` = 39871; -- locales_item - name : entry=40686
UPDATE `trans_words` SET `content_loc5`='Unlocks access to  Heroic mode for Auchindoun dungeons.' WHERE `word_id` = 30712; -- locales_item - description : entry=30633
UPDATE `trans_words` SET `content_loc5`='Unlocks Heroic Difficulty for Caverns of Time dungeons.' WHERE `word_id` = 30716; -- locales_item - description : entry=30635
UPDATE `trans_words` SET `content_loc5`='Unlocks Heroic Difficulty for Coilfang Reservoir dungeons.' WHERE `word_id` = 30702; -- locales_item - description : entry=30623
UPDATE `trans_words` SET `content_loc5`='Unlocks Heroic Difficulty for Hellfire Citadel dungeons.' WHERE `word_id` = 30700; -- locales_item - description : entry=30622
UPDATE `trans_words` SET `content_loc5`='Unlocks Heroic Difficulty for Tempest Keep dungeons.' WHERE `word_id` = 30714; -- locales_item - description : entry=30634
UPDATE `trans_words` SET `content_loc5`='Used by Enchanters to enchant items.' WHERE `word_id` = 24285; -- locales_item - description : entry=6216
UPDATE `trans_words` SET `content_loc5`='Used Monster Sample' WHERE `word_id` = 24323; -- locales_item - name : entry=9443
UPDATE `trans_words` SET `content_loc5`='Viewing Room Key' WHERE `word_id` = 17548; -- locales_item - name : entry=13873
UPDATE `trans_words` SET `content_loc5`='Warpforged Key' WHERE `word_id` = 30713; -- locales_item - name : entry=30634
UPDATE `trans_words` SET `content_loc5`='Weapon of Mass Destruction (test)' WHERE `word_id` = 12211; -- locales_item - name : entry=5418
UPDATE `trans_words` SET `content_loc5`='Weapon of Massive Destruction (test)' WHERE `word_id` = 12210; -- locales_item - name : entry=5417
UPDATE `trans_words` SET `content_loc5`='Wearing this would be a bad idea, as it would severely hinder your vision.' WHERE `word_id` = 31592; -- locales_item - description : entry=31529
UPDATE `trans_words` SET `content_loc5`='Work Shirt' WHERE `word_id` = 10340; -- locales_item - name : entry=3148
UPDATE `trans_words` SET `content_loc5`='X marksss the ssspot.' WHERE `word_id` = 30530; -- locales_item - description : entry=30427
UPDATE `trans_words` SET `content_loc5`='Yellow Bryanite of Stamina' WHERE `word_id` = 25231; -- locales_item - name : entry=23235
UPDATE `trans_words` SET `content_loc5`='zzDEPRECATED Warsong Mark of Honor' WHERE `word_id` = 24446; -- locales_item - name : entry=19322
UPDATE `trans_words` SET `content_loc5`='zzDEPRECATEDHeart of the Sky' WHERE `word_id` = 25274; -- locales_item - name : entry=23364
UPDATE `trans_words` SET `content_loc5`='zzDEPRECATEDPerfect Diamond' WHERE `word_id` = 25275; -- locales_item - name : entry=23366
UPDATE `trans_words` SET `content_loc5`='ZZOLD Spellthread' WHERE `word_id` = 24681; -- locales_item - name : entry=21878
UPDATE `trans_words` SET `content_loc5`='zzOLDBold Ornate Ruby' WHERE `word_id` = 28515; -- locales_item - name : entry=28117
UPDATE `trans_words` SET `content_loc5`='zzOLDEnscribed Ornate Topaz' WHERE `word_id` = 28520; -- locales_item - name : entry=28122
UPDATE `trans_words` SET `content_loc5`='zzOLDMighty Blood Garnet' WHERE `word_id` = 28268; -- locales_item - name : entry=27774
UPDATE `trans_words` SET `content_loc5`='zzzOLDDaily Quest Faction Token' WHERE `word_id` = 47417; -- locales_item - name : entry=43949

SET NAMES 'latin1';
